### ISSUE TITLE
New Use Case: Satellite verification of sea surface temperature (GHRSST) against RTOFS output

### ISSUE THREAD

**Issue by mrinalbiswas** [dtcenter/METplus#1004]
*Replace italics below with details for this issue.*

## Describe the New Use Case ##
This new use case will duplicate the efforts of Todd Spindler's VLab-Redmine code, specifically its calculations for satellite verification of sea surface temperature using GHRSST as obs, RTOFS output as model forecasts, WOA as climatology to calculate anomaly and OSTIA ice for masking. 
It still needs to be determined if the graphical output currently produced and displayed at the site listed below need to be produced in this use case.
As a final step, these new data sources will be logged in the METplus Verification Datasets Guide.

This is part of the larger Marine layer Verification package integration, which is tracked in [#800](https://github.com/dtcenter/METplus/issues/800).

Useful weblink : https://polar.ncep.noaa.gov/global/class-1/

### Use Case Name and Category ###
*Provide use case name, following Contributor's Guide naming template, and list which category the use case will reside in.*
*If a new category is needed for this use case, provide its name and brief justification*

### Input Data ###
GHRSST: https://podaac.jpl.nasa.gov/dataset/AVHRR_OI-NCEI-L4-GLOB-v2.0 
Climo data: https://www.nodc.noaa.gov/OC5/woa13/

### Acceptance Testing ###
A successful output from this use case will duplicate ongoing efforts currently completed with Todd's VLab code.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] Stats between the two models (weighted mean, bias, std dev, correlation coefficient, scatter index, RMSE)

### Relevant Deadlines ###
NONE

### Funding Source ###
2788881

### Assignee ###
- [ ] @j-opatz 
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by mrinalbiswas** [comment]
@j-opatz  Created an issue. Unable to assign you. The link is disabled.

**Comment by georgemccabe** [comment]
Closed with #1182
