### ISSUE TITLE
Update MET component labels for Grid-to-Grid and Grid-to-Point verification.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1012]
## Describe the Task ##
Replace existing label "MET: Traditional Verification" with two new labels "MET: Grid-to-Grid Verification" and "MET: Grid-to-Point Verification". Verifying against point observations results in many more questions and answers. Having a specific label for point verification will help categorize the questions better.

Will need to reassign the existing use of "MET: Traditional Verification" to one of the new ones.

### Time Estimate ###
1 hour.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
None.

### Funding Source ###
None.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: none needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
