### ISSUE TITLE
Add list of METplus statistics to documentation

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/METplus#1049]
*Replace italics below with details for this issue.*

## Describe the Task ##
NOAA and the Air Force are making this an upcoming deliverable.
We need a giant list/table on the web that lists out all
Statistics, Tools and References
This may or may not stay with the METplus User's Guide
It may be broken out into its own entity later on.

Much of this data has already been collected in tables within the User's Guide.
Tara also started a collection on the google drive:
[Laundry List of METplus Statistics slide 1.pptx](https://docs.google.com/presentation/d/1Qx3G_2fgDYfTyDIyeMAi31Uu10P_4iSE/edit#slide=id.p1)
[Laundry List of METplus Statistics slide 2 probability.pptx](https://docs.google.com/presentation/d/1-14ArEHpOPxtGxAbX1KxDIVSqmnmGCXs/edit#slide=id.p1)
[Laundry List of METplus Statistics slide 3 objects.pptx](https://docs.google.com/presentation/d/1iJJwOO8u9kAL_MUez51-ZZEyAgQOMLGu/edit#slide=id.p1)

From the tables of statistics in the User's Guide, remove the column numbers and name the statistic and the tool or tools that use it along with any references.  Using the "search docs" feature could be useful for this collection.

Link to work so far:
https://metplus.readthedocs.io/en/feature_1049_statistics_list/Users_Guide/statistics_list.html

### Time Estimate ###
40 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] This may be added as we go along

### Relevant Deadlines ###
There is a deadline.  It will be attached to an upcoming deliverable. 
Currently (7/29/21) that date is unknown

### Funding Source ###
2793541

### Assignee ###
- [x] Select **engineer(s)** Julie Prestopnik & Lisa Goodrich
- [x] Select **scientist(s)** Tara Jensen

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)**
- [x] Select **Milestone** 

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
This is documentation, it shouldn't impact any of the components.
The goal of this documentation is to provide more options for users to easily access
the tools and statistics available across many MET platforms.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_1049_statistics_list`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by lisagoodrich** [comment]
No pull request submitted. 
Per Tara, "Looks good.  I'd suggest pushing this into develop and being done with this ;-)"
