### ISSUE TITLE
Add support for using filename templates for defining input level in PCPCombine

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1062]
PCPCombine currently does not support using filename templates in the PCP_COMBINE_INPUT_LEVELS variables. This would be useful for defining NetCDF time dimensions.

## Describe the Enhancement ##
*Provide a description of the enhancement request here.*

### Time Estimate ###
~2-3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by RachelNorth** [comment]
Attaching a sample file containing hourly rainfall accumulations from a single forecast initialisation (0000UTC 2019/09/30), for a single ensemble member (named 'e00' here).  This file is as originally supplied, with minimal dimensions, coordinates and attributes. We're wanting to produce daily and potentially 3-hourly accumulations with this.
[20190930_prec_1hracc_75hrfcst_e00.nc.gz](https://github.com/dtcenter/METplus/files/6944628/20190930_prec_1hracc_75hrfcst_e00.nc.gz)

Thanks!

**Comment by georgemccabe** [comment]
@RachelNorth, thank you for sending the input file. I will use this file to test the changes.

From Discussion #1078, @mpm-meto brought to attention that the level value is not passed into the command when running with -subtract mode. This should be fixed with this work.

**Comment by georgemccabe** [comment]
Hi @RachelNorth, I downloaded your file and did some initial testing using plot_data_plane. I noticed that the time units are "hours since 1-1-1 00:00:00." It looks like MET can interpret these units, however the time range of the data are between 20191002_010000 to 20191005_030000 even though the file should have data starting at 20190930_00. I ran some date commands and confirmed that the first and last value in the file match these times:

`date -ud '1-1-1 UTC '17695993' hours' +%Y%m%d_%H`
20191002_01

`date -ud '1-1-1 UTC '17696067' hours' +%Y%m%d_%H`
20191005_03

It looks like the first time is 49 hours after the expected initialization time. Do you know why that would be?
