### ISSUE TITLE
Enhance TC-Pairs wrapper to make valid_inc, valid_exc, and write_valid configurable options.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1069]
## Describe the Enhancement ##
dtcenter/MET#1870 adds 3 new configurable options for TC-Pairs. This task is to enhance the METplus TC-Pairs wrapper to make those options configurable:
```
valid_inc   = [];
valid_exc   = [];
write_valid = [];
```
All 3 are arrays of strings that are empty be default. The can be filled with a comma-separated list of double-quoted string in "YYYYMMDD[_HH[MMSS]]" format. They configuration of them is exactly the same as the existing init_inc and init_exc options.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541 (copied from dtcenter/MET#1870)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: George
- [x] Select **scientist(s)** or **no scientist** required: Molly Smith

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
Assigned to the beta2 cycle, but this can be moved to beta3 if needed.
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by mollybsmith-noaa** [comment]
I'll test on Jet with my realtime data once this issue is completed.
