### ISSUE TITLE
Add Grid-Stat configuration options for distance_map dictionary

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1089]
## Describe the Enhancement ##
The issue dtcenter/met#1673 and corresponding pull request dtcenter/met#1857 add new columns to the distance map (DMAP) line type created by the Grid-Stat tool.

This includes one change to the Grid-Stat configuration file in the "distance_map" dictionary:
```
distance_map = {
   baddeley_p        = 2;
   baddeley_max_dist = NA;
   fom_alpha         = 0.1;
   zhu_weight        = 0.5;
   beta_value(n)     = n * n / 2.0;
}
```
The beta_value(n) function is a new configuration option. The wrapped Grid-Stat config file in METplus should be updated to handle it.

Please see existing documentation for more details about the [configuration options](https://met.readthedocs.io/en/develop/Users_Guide/grid-stat.html?highlight=gbeta#distance-map), [science](https://met.readthedocs.io/en/develop/Users_Guide/grid-stat.html#beta-and-g-beta), and [equations](https://met.readthedocs.io/en/develop/Users_Guide/appendixC.html?highlight=gbeta#g-and-g-beta).

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
Prior to the METplus 4.1.0 release.

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: George
- [x] Select **scientist(s)** or **no scientist** required: no scientist needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This is a sub-issue of #896
