### ISSUE TITLE
CyclonePlotter, create options to format output grid area to user-desired area

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1091]
## Describe the New Feature ##
Guang Ping discovered that the current build of CyclonePlotter does not allow for an area-focused output. Instead, the script hard-codes the entire globe output, regardless of where the storm tracks actually occur (ex. Atlantic Basin only).
The new feature desired would be to allow users to input a area of focus, either by a lower left lat/lon point and total gridpoints in the x and y directions, or by a 4-point grid domain. 

### Acceptance Testing ###
For testing purposes, I've acquired a GFS global trak file from Guang Ping. It's located on Seneca, under /d1/projects/METplus/METplus_Data/development/feature_1091
A successful feature upgrade to CyclonePlotter will result in a .png output that is focused on a user-defined area, rather than global.

### Time Estimate ###
More input on this is needed from the engineer

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] Setup config file to allow user to determine whether to use a global extent or define lons and lats defining a
        region
- [x] Set up plotting in cartopy to set the extent
- [x] Set up wrapper code to support further filtering of data to only those points that lie within the user-specified region/extent

### Relevant Deadlines ###
This ties into ongoing work with the GFDL tracker and extra-TC tracking capabilities

### Funding Source ###
2788881

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
