### ISSUE TITLE
Add instructions to update old METplus configuration files that reference user-defined wrapped MET config files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1147]
Related to discussion #996

## Describe the Enhancement ##
Add useful instructions to assist users who need to update their configurations to use the wrapped MET config files in parm/met_config instead of their own MET config files. This involves determining which variables in the user's wrapped MET config file differ from the wrapped version in parm/met_config (considering the variables in the parm/met_config version that mistakenly differ from the default MET values before v4.0.0).

Respond to GitHub Discussion topic listed above with info and consider adding this information to User's Guide

### Time Estimate ###
~3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add logic for writing metplus_final.conf to move variables that are specific to that run (i.e. CLOCK_TIME) to a runtime section so that it is clear which variables are relevant if rerunning*

### Relevant Deadlines ###
4.1.0-beta3 (if possible)

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Updated #996 to include a detailed summary of the process to update old wrapped MET config files. Directing users to this discussion topic is likely sufficient for providing this information, so adding the same content to the User's Guide may not be necessary. Closing this issue, but please re-open if adding to the user's guide is desired.
