### ISSUE TITLE
Internal: Document GitHub Discussions procedure for the Contributor's Guide

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#1159]
## Describe the Task ##
Document GitHub Discussions procedure for the Contributor's Guide

### Time Estimate ###
< 1 day of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
From Slack: 
-----
 
George McCabe

When you are the point person for METplus Support:
Review the Tips/Tricks page: https://github.com/dtcenter/METplus/discussions/categories/tips-tricks

Check if there are any new discussions that have been added by users that are actually questions. If so, move the discussion to a more appropriate category so that it can be found when filtering for unanswered discussions.

Note that if you have filtered by "Unanswered" and navigate to the Tips/Tricks category, no results will be found because these discussions are not answerable.

Review the Unanswered discussions: https://github.com/dtcenter/METplus/discussions?discussions_q=is%3Aunanswered

New discussions that have been posted within 24 hours:
If the issue is time sensitive, i.e. related to an upcoming training series session, take action (see "Actions for Handling New Discussion")

Otherwise leave unanswered to allow the user community to respond

New discussions that have 0 responses posted over 24 hours ago:
Take action (see "Actions for Handling New Discussion")

Remaining Unanswered discussions:

Review the latest on discussion history to see if any additional action is required

If an obvious answer exists, consider marking it as the answer and locking the discussion to prevent future posts.

If the user has not responded in 7 or more days, consider following up to see if the user's issue is resolved or if they need more assistance.

If unsure how to proceed, post in the #user-support channel tagging the person who has been assisting the user.
Review Answered Discussions that are Unlocked: https://github.com/dtcenter/METplus/discussions?discussions_q=is%3Aanswered+is%3Aunlocked

If there's any recent activity on an ANSWERED question that indicates the questioner is "satisfied" with our response, click on the button to LOCK that Discussion to prevent future activity.

Actions for Handling New Discussion:

Check to see if it should be reassigned from it's current category to some other category.

Review the labels and pick at least one of the blue one to further categorize it.

If you can answer it yourself, do so. Or if you can answer it with help from someone, post to this Slack channel asking for advice.

If it'd be better to have someone else answer, coordinate that on this Slack channel, or comment on the Discussion with something like:
"@George McCabe would be the best person to address your question. He should respond within a couple of days."
Or if it's obvious that we also need test data, ask the user to send that data.

-----
 
George McCabe
Lock discussion request:

Here is text from a recently post from @John Halley Gotway requesting that the user mark the best answer so we can lock the discussion. This text may need to be modified to match a specific situation, but this is a good starting point. I'm going to pin this post so that it is easy to find.

I'd like to mark this discussion as being answered and "lock it" to prevent future posts. That's how we encourage users to create new discussions for new questions. But I wanted to give you an opportunity to comment on it before doing so. Please feel free to select one of the responses as being the best answer to your original question. That'll help future users with similar questions find answers.


-----
 
George McCabe
Response to new met_help@ucar.edu RT emails:
Hi,

We switched from providing support through this email address to providing support through GitHub Discussions. You will need to create a free GitHub account if you don't have one already and post your questions to the METplus Components Discussion Forum:

https://github.com/dtcenter/METplus/discussions/new

Thanks!

------

John Halley Gotway

So your job is:

Go to the discussions page: https://github.com/dtcenter/METplus/discussions

Click on the "Unanswered" filter button and look for any discussions that have 0 responses.

Since there are none, you don't have any new discussions to handle. If there were a new one that came in on the day prior, you would:

Check to see if it should be reassigned from it's current category to some other category.

Review the labels and pick at least one of the blue one to further categorize it.

If you can answer it yourself, do so. Or if you can answer it with help from someone, post to this Slack channel asking for advice.

If it'd be better to have someone else answer, coordinate that on this Slack channel, or comment on the Discussion with something like:
"@George McCabe would be the best person to address your question. He should respond within a couple of days."
Or if it's obvious that we also need test data, ask the user to send that data.
For the remaining Unanswered discussions, review the latest on Discussion history to see if any additional action is required.
NEW if there's any recent activity on an ANSWERED question that indicates the questioner is "satisfied" with our response, click on the button to LOCK that Discussion to prevent future activity.
