### ISSUE TITLE
Enhance SeriesAnalysis wrapper to allow different field info values for each file in a list

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1166]
Currently the wrapper will call series_analysis once per field defined. This works fine if all of the files in the file list use the same field information. However, in the case with CPC's NMME file, if a single input file contains multiple fields that should be processed, the wrapper cannot be configured to specify a different level value (for each time).

## Describe the Enhancement ##
The preferred method of handling this would allow a user to list one file for a given field, and use a counter (or something that changes with each run) for the changing field index to access each field in the file. Specifically for NMME data, this would be pulling out the multiple time indices that are  contained in the observation files.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2700041
### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe, you and I discussed what changes might be needed for the SeriesAnalysis Wrapper via Slack. And this issue is the result of that discussion. Prior to actually making changes to the wrapper, I'd recommend manually configuring/running Series-Analysis to test/confirm that the proposed wrapper changes will actually have the desired effect. If you have questions or want to work through those tests together, I'm happy to help.

**Comment by georgemccabe** [comment]
This issue came up in GitHub Discussion #1143

**Comment by georgemccabe** [comment]
From a Slack message from @JohnHalleyGotway :

> If you run series_analysis with n input files and 1 field in the config file, it reads that same field from all n input files. If you configure it with n files and n fields, it should read the n-th field from the n-th file.
> So you configure it to define separate fields for each of the n input files.

**Comment by georgemccabe** [comment]
Enhancements to the wrapper logic that are needed to resolve this issue:
- [X] Keep time information for files to process available in SeriesAnalysis wrapper so that appropriate time information can be substituted into the field info
- [X] If field info has 1 item and uses a template tag, sub values using the time info for each file in the list

**Comment by j-opatz** [comment]
During a successful direct call to the series-analysis tool, I used the following command at runtime:

/d1/projects/MET/MET_regression/develop/NB`date +\%Y\%m\%d`/MET-develop/met/bin/series_analysis -fcst /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198201_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198301_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198401_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198501_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198601_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198701_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198801_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_198901_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199001_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199101_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199201_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199301_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199401_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199501_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199601_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199701_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199801_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_199901_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200001_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200101_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200201_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200301_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200401_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200501_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200601_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200701_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200801_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_200901_ens.nc \
        /d1/projects/CPC_data/output/NMME_out/GenEnsProd-SA/gen_ens_prod_201001_ens.nc \
        -obs /d1/projects/CPC_data/input/NMME/new_data/ghcn_cams.1x1.1982-2020.mon.nc -out hereReadThisSA.nc -config SAConfig_testing_for_CFSv2  -v 4 -log testing_SArun_WED.log

Also attaching the MET config file that was used with this command.
[SAConfig_testing_for_CFSv2.txt](https://github.com/dtcenter/METplus/files/7730894/SAConfig_testing_for_CFSv2.txt)
