### ISSUE TITLE
New Wrapper: GenEnsProd

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1180]
## Describe the New Feature ##
dtcenter/MET#1904 adds an initial version of the new Gen-Ens-Prod tool to the met-10.1.0-beta3 MET development release. This issue adds a wrapper for calling that Gen-Ens-Prod tool. Just like Gen-Ens-Prod is a subset of the Ensemble-Stat tool, it's wrapper can largely be a subset of the existing Ensemble-Stat wrapper.

From @georgemccabe:
The new wrapper will be able to borrow existing components from other wrappers to implement all of the functionality. The wrapper will support the following functionality:

- Obtain a list of input files, write a file list file, and pass to -ens argument
- Set environment variables to override values in MET config file (all dictionaries and variables in the new config file are supported in other wrappers)
- Pass wrapped config file as -config argument
- Build output file path from template/dir and pass to -out argument
- Set optional -ctrl path based on template/dir (GEN_ENS_PROD_CTRL_[TEMPLATE/DIR] or GEN_ENS_PROD_CONTROL_[TEMPLATE/DIR])

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2793541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe 
- [x] Select **scientist(s)** or **no scientist** required: @j-opatz 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- dtcenter/MET#1904 creates the Gen-Ens-Prod tool.
- No other downstream issues needed. Although training materials should be developed eventually.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
