### ISSUE TITLE
Update name for extraTC use case

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1187]
## Describe the Task ##
One of the use cases currently in the repo, CyclonePlotter_fcstGFS_obsGFS_OPC, does not conform to the current standard for use case naming. It indicates a center by name, which does not follow standard protocol. 

In order to bring this use case into alignment with the rest, the name will be changed to CyclonePlotter_fcstGFS_obsGFS_extraTC, and the description of the use case will be updated to "extra-TC tracker and plotting capabilities". This will require documentation, script, data, and automation name changes.

### Time Estimate ###
1-2 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
An existing use case in the TC and Extra TC category was found to have a similar name as the one proposed, so naming has changed to CyclonePlotter_fcstGFS_obsGFS_UserScript_ExtraTC
