### ISSUE TITLE
Reorganize the Cryosphere and Marine and Coastal use case categories into one group

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1200]
## Describe the Task ##
Before the latest beta release, the use case categories were reexamined and found that the cryosphere and marine and coastal use case categories have a significant amount of overlap. Additionally, with the ongoing effort to ingest and replicate EMC's marine and cryo verification package, the overlap of the two categories will become even more significant.

In an effort to not eclipse one category in favor of the other, or to cause user confusion by putting a use case that has aspects of both categories in one or the other, it's been decided that these two categories need to be merged into a new use case category, Marine and Cryosphere. 

### Time Estimate ###
2-3 days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Create new use case category, Marine and Cryosphere
- [x] Move existing Cryosphere case to new use case category
- [x] Move existing marine and coastal use cases to new use case category
- [x] Adjust documentation
- [x] Remove outdated use case directories

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
