### ISSUE TITLE
Update Contributor's Guide for new removing/adding data protocols

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1227]
## Describe the Task ##
Two of the most recent issues I've worked on (#1200 and #1187) have revealed a need to revisit the Contributor's Guide and update the sections pertaining to adding data on Mohawk. When the guide was written, it was a largely solo endeavor and focused on the scenario of adding a use case. However, there needs to be information on the scenarios for when use cases change names,and when data is removed/updated for an existing use case. 

This will require a "choose your own adventure" style writing, with care taken so it's A) understandable and B) users don't accidentally remove necessary data from the server.

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
This issue is still ongoing, but it can't be tackled like a typical issue (state the problem, work until a solution is found, confirm solution works for user, etc.). Instead, this will need to be resolved while it's being encountered: while reviewing the documentation for this issue, everything seems to be stated clearly. But the issue of removing data is so far from when this issue is being reviewed (~6 mos) that an effective strategy can't be made.
So this issue will be closed for now, hopefully to be completed when it actually comes up.
