### ISSUE TITLE
Implement various enhancements to climatology settings

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1247]
Various enhancements are needed to improve the logic for setting climatology variables in the climo_mean and climo_stdev dictionaries.

## Describe the Enhancements ##

- [x] Add support for setting a list of field levels in climo variables

Setting the following:

`GRID_STAT_CLIMO_MEAN_FIELD = {name="UGRD"; level=["P850","P500","P250"];}`

Results in an improperly formatted value:

METPLUS_CLIMO_MEAN_DICT=climo_mean = {file_name = ["/scratch1/NCEPDEV/global/glopara/fix/fix_verif/climo_fi
les/cmean_1d.19591203"];field = [{name="UGRD"; level=["P850",**P500,P250**];}];}

Add a test for setting climo field info and enhance the logic to properly format a list of levels. Make sure the behavior works for all apps that use climatology variables.

- [x] Add support for using forecast or observation field info for climatology

It is often the case that the climatology field info is the same as the forecast field info. If \<APP\>\_CLIMO_[MEAN/STDEV]_FIELD_NAME is not set, then the wrapper should check if \<APP\>\_CLIMO\_[MEAN/STDEV]\_USE\_[FCST/OBS] is set to True. Error out if both are True. If one is True, then use the field info from the appropriate input as the field info for the climo variable

- [x] Add support for setting file_type for climo_[mean/stdev]

Add optional \<APP\>\_CLIMO_[MEAN/STDEV]_FILE_TYPE to set file_type in the appropriate climo dictionary -- this was implemented in PR #1353

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
