### ISSUE TITLE
New Use Case: TCGen Verify Deterministic Genesis Forecasts and Probabilities from ATCF e-deck files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1274]
Use Case Documentation: https://metplus.readthedocs.io/en/develop/generated/model_applications/tc_and_extra_tc/TCGen_fcstGFS_obsBDECK_2021season.html

Create a new use case example that demonstrates new functionality added in dtcenter/MET#1809

## Describe the New Use Case ##
*Provide a description of the new feature request here.*

### Use Case Name and Category ###
*Provide use case name, following Contributor's Guide naming template, and list which category the use case will reside in.*
*If a new category is needed for this use case, provide its name and brief justification*

### Input Data ###
*List input data types and sources.*
*Provide a total input file size, keeping necessary data to a minimum.* 

### Acceptance Testing ###
*Describe tests required for new functionality.*
*As use case develops, provide a run time here*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**
- [x] Select **privacy**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Here is the data for this new use case, as provided by @halperin-erau:

Attached are tc_gen input files in the GFDL tracker format and edeck format.  They contain tracker output from the GFS, NAVGEM, and CMC models in the AL and EP basins during 2021.

Also attached are the 2021 b-deck files.  The 2021 a-decks should be used as well, but they were too large to email (~190 MB).

[bdecks_2021.tar.gz](https://github.com/dtcenter/METplus/files/7548926/bdecks_2021.tar.gz)
[tc_gen_test_prob.tar.gz](https://github.com/dtcenter/METplus/files/7548929/tc_gen_test_prob.tar.gz)
[tc_gen_test_deterministic.tar.gz](https://github.com/dtcenter/METplus/files/7548930/tc_gen_test_deterministic.tar.gz)
2021 ADECK files can be retrieved from: https://ftp.nhc.noaa.gov/atcf/aid_public/

**Comment by JohnHalleyGotway** [comment]
Recommend reading about adding a use case here and direct questions to @georgemccabe:
https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html
