### ISSUE TITLE
Add support for explicitly setting file list file paths in wrappers that support multiple input files

### ISSUE THREAD

**Issue by hertneky** [dtcenter/METplus#1289]
## Describe the Enhancement ##
Support the use of file_lists in the METplus wrappers for MET tools that already have that functionality. MET tools that currently accept a file_list as input look to be: ensemble_stat, grid_diag, gsidens2orank, MTD, rmw_analysis, series_analysis, tc_rmw.

Depending on the tool, users should be able to specify either a single file_list and/or a fcst_/obs_file_list to be used within the METplus configuration file . For example the MET MTD tool has either option:

Usage: mtd
          -fcst    file_1 ... file_n | file_list
          -obs     file_1 ... file_n | file_list
          -single  file_1 ... file_n | file_list

This functionality will allow users to run over a specified set of cases that may not be at continuous time intervals. When a file list is provided, the time controls in the configuration would presumably be ignored.

**Highest Priority:**
series_analysis - file_list overrides timing control
mtd - file_list overrides timing controls
tc_rmw and rmw_analysis - file_list just passes in data - need to check if it overrides timing controls
ensemble_stat - file_list is used to define members of ensemble - will still need timing controls

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
4.1.0-beta5

### Funding Source ###
2700042

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TaraJensen** [comment]
series_analysis
       -fcst  file_1 ... file_n | fcst_file_list
       -obs   file_1 ... file_n | obs_file_list
       [-both file_1 ... file_n | both_file_list]

tc_rmw
       -data file_1 ... file_n | data_file_list

**Comment by hertneky** [comment]
@georgemccabe I tested this enhanced functionality with the series-analysis tool and it worked and provided identical results to using the timing info from the conf.
