### ISSUE TITLE
Include xESMF capabilities in METplus

### ISSUE THREAD

**Issue by AliciaBentley-NOAA** [dtcenter/METplus#1314]
## Describe the New Feature ##
Tri-polar grids (used in NCEP Ocean models like RTOFS) need to be regridded in order to be read by METplus. This regridding is currently done on Hera using a Python package called xESMF. Unfortunately, NCO will not install xESMF on WCOSS2 (xESMF is no longer supported). Is there a way to regrid tri-polar grids and read them into METplus using supported Python packages? Alternatively, could xESMF be built into METplus itself to avoid the xESMF installation issue on WCOSS2?

### Acceptance Testing ###
Data: RTOFS data (tri-polar grid) 
Outcome: Need to be able to read RTOFS data into METplus

### Time Estimate ###
I hope this would only require a few days of work for the METplus team. 

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] Regrid RTOFS data (currently tri-polar grid)
- [ ] Ingest regridded RTOFS data into METplus

### Relevant Deadlines ###
No hard deadline, but EMC needs this ASAP to begin EVS development of RTOFS in 2022.

### Funding Source ###
Split 2793541, 2702691, 2788881, 2799991

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
These are the lines in the Python Embedding script that uses the xesmf package:

https://github.com/dtcenter/METplus/blob/97dee6dc0fcb6d43c3d595fbaa86d44ecc476111/parm/use_cases/model_applications/marine_and_coastal/PlotDataPlane_obsHYCOM_coordTripolar/read_tripolar_grid.py#L124-L143

If there is equivalent functionality in another Python package (ESMpy?) that is available on WCOSS2, then we could replace these lines to remove the dependency of the xesmf package.

**Comment by hankenstein2** [comment]
Find relevant code in the xESMF github repository and try it out

**Comment by hankenstein2** [comment]
The xESMF repository is using an MIT license which Minna pointed out can be used by us. I looked at the small piece of code we need and will see how easy it is to incorporate into METplus

**Comment by AliciaBentley-NOAA** [comment]
https://github.com/pangeo-data/xESMF

xESMF has been picked up by Pangeo and seems to be maintained more than the old Harvard version, if this is helpful information for you to have! Again, EMC needs the xESMF functionality in MET/METplus in order to regrid tri-polar grids (so that they can be read into METplus). Thanks!

**Comment by georgemccabe** [comment]
Thank you for sending that link, @AliciaBentley-NOAA.

Here are the relevant functions/classes that are used in the METplus use case:

grid_2d:
https://github.com/pangeo-data/xESMF/blob/e64b307d55470b5c086b18676dd2ecb1a4cbe05b/xesmf/util.py#L33

Regridder:
https://github.com/pangeo-data/xESMF/blob/e64b307d55470b5c086b18676dd2ecb1a4cbe05b/xesmf/frontend.py#L648

**Comment by TaraJensen** [comment]
According to Rocky Dunlap - xesmf is basically a package that wraps ESMpy.  It might be worth looking at ESMpy https://earthsystemmodeling.org/esmpy/

Also - while testing the capability - it would be good to also test reading the LFric metadata/grid.  See this issue: dtcenter/METplus#1561 and scroll down half way for a file called canned_metadata_lfric_r30711.zip

**Comment by hankenstein2** [comment]
There are some fairly big issues to overcome to get this working.

1. We would need to lift the entirety of xESMF into METdatadb - not hard but we would need to include a license with that specific code. The lines of code being called in the code snippets above are simple but everything depends on everything.
2. This would require python3.7+ and the packages cf_xarray (version 0.7) and shapely, we know how difficult it is to get new packages added
3. xESMF is indeed a wrapper or python interface to ESMF which at its core is fortran code which would need to be compiled by...us?

**Comment by hankenstein2** [comment]
We unfortunately need to close this ticket. NCO has made it clear that neither ESMF nor xESMF will be allowed to be installed on WCOSS machines and embedding the code into METplus is prohibitively complicated. We will explore a different avenue to solve this issue when MET tackles unstructured grids.
