### ISSUE TITLE
Add recording of Python packages to Adding Use Cases documentation

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#1374]
## Describe the Task ##
This issue arose from a request from EMC to compile a complete list of all Python packages that are used for the METplus wrappers use cases, METcalcpy, and METplotpy.  To run the METplus wrappers, the only Python package that is required besides the standard packages is dateutil (python-dateutil). However, some METplus use cases have additional Python package dependencies to run.  Use cases that utilize Python Embedding in the MET tools need to have xarray, numpy, pandas, and netCDF4, as well as any other Python packages that are used in the script that is used. The full list of package dependencies for the use cases depends on which cases need to be supported on WCOSS2, and it was determined that EMC users would like to have all of the use cases available for running on WCOSS2.  

The required packages for METcalcpy and METplotpy are listed in the pages below, respectively:
https://metcalcpy.readthedocs.io/en/develop/Users_Guide/installation.html
https://metplotpy.readthedocs.io/en/develop/Users_Guide/installation.html
 
It would be helpful for contributors to METplus wrappers, METcalcpy, and METplotpy, to continuously update the spreadsheet for less effort in the future and also for reference by others.
https://docs.google.com/spreadsheets/d/1Lf-yxZBXTTnBaqCOWUk-jdP9RpaLfil_s-KKH29CkKU/edit#gid=0

### Time Estimate ###
1 day of work.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
ASAP

### Funding Source ###
Due to low time commitment, I'll plan to split.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
This work has been completed.
