### ISSUE TITLE
Add support for new climo_cdf.direct_prob flag

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1392]
## Describe the Enhancement ##
MET PR dtcenter/MET#2034 for issue dtcenter/MET#2003 adds a new option to the climo_cdf dictionary. This task is to make this option configurable via METplus.

Also support climo_cdf in the Series-Analysis config file. It appears in the following MET config files (Series-Analysis is the only new one):
```
EnsembleStatConfig_default:climo_cdf = {
GridStatConfig_default:climo_cdf = {
PointStatConfig_default:climo_cdf = {
SeriesAnalysisConfig_default:climo_cdf = {
```

Please see [feature_2003_briercl](https://met.readthedocs.io/en/feature_2003_briercl/Users_Guide/config_options.html?highlight=direct_prob#climo-cdf ) documentation for details or [develop](https://met.readthedocs.io/en/develop/Users_Guide/config_options.html?highlight=direct_prob#climo-cdf), after the PR has been merged.

Also assigning to @j-opatz since he's applying this new functionality to NOAA/CPC data and is best suited to advise on the utility of this option.

### Time Estimate ###
2 hours (?)

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
Include in METplus 4.1 coordinated release.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe 
- [x] Select **scientist(s)** or **no scientist** required: @j-opatz 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
