### ISSUE TITLE
Create comprehensive Python package documentation

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#1403]
This task came about from a request from EMC to provide a complete list of Python packages needed for METcalcpy, METplotpy, and METplus wrappers.  Initially created in a Google Spreadsheet, we realize it would be better to provide this information in our existing Sphinx environment.

## Describe the Task ##
Lisa: In the [METplus User's Guide Overview](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html), between section "METplus Wrappers Components" (currently 1.4) and  "METplus Release Notes" (currently 1.5), create a new section called "METplus  Components Python Requirements" (which will become section 1.5).  Copy the information into the spreadsheet in the same format as the [METplus Database of Statistics](https://metplus.readthedocs.io/en/develop/Users_Guide/statistics_list.html).
DONE

Lisa or Julie: Update section "8.4.4.2. Add Sphinx Documentation File" of the [documentation](https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#document-new-use-case) to change the link to the spreadsheet in the text below:

> Update the list of External Dependencies (if applicable) to include any required Python packages. Update the [METplus Components Python Requirements](https://docs.google.com/spreadsheets/d/1Lf-yxZBXTTnBaqCOWUk-jdP9RpaLfil_s-KKH29CkKU/edit#gid=0) spreadsheet. If the package is already listed in the spreadsheet, add a link to the documentation page for this new use case, following the format in the spreadsheet. If the package is not already listed, update the spreadsheet to include the name of the required package, the version, the METplus component (e.g. METplus wrappers, METcalcpy, METplotpy), the source, a brief description, and a link to this new use case that uses this new Python package.

to point to the new section in the documentation.
DONE

Julie: Update the issue templates and the pull request templates to indicate that if there are new Python packages being added for that pull request, check to ensure they are listed in the table referenced above.
DONE

### Time Estimate ###
1 to 3 days of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
??

### Funding Source ###
Spread time evenly across 3 accounts:
2702691 
2792541 
2771021

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
The work is completed.  Closing issue.
