### ISSUE TITLE
Add support for the normalize option to the Gen-Ens-Prod wrapper.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1445]
## Describe the Enhancement ##
Sorry about this last minute addition. The PR's dtcenter/MET#2061 and dtcenter/MET#2075 for dtcenter/MET#1918 issue adds a new configuration option to the Gen-Ens-Prod tool.

Similar to the convert and censor_thresh/censor_val options, it can be set separately for each ens.field array entry. It is a flag that can be set to one of 5 options. They can be seen by searching for "normalize" in this section of the [feature branch documentation](https://met.readthedocs.io/en/feature_1918_std_climo/Users_Guide/gen-ens-prod.html#optional-arguments-for-gen-ens-prod) or in the [develop branch](https://met.readthedocs.io/en/develop/Users_Guide/gen-ens-prod.html#optional-arguments-for-gen-ens-prod) after the PR has been merged.

Note that these are literals in the gen_ens_prod configuration file (like TRUE and FALSE). They are NOT strings. Also note that while normalize is currently only supported in gen_ens_prod, we will likely add support for it to any of the other MET tools that use climatology data via dtcenter/MET#2062.

### Time Estimate ###
1/2 day?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe 
- [x] Select **scientist(s)** or **no scientist** required: none needed but @j-opatz can answer questions about intended usage

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No additional impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
