### ISSUE TITLE
Add support for probabilistic verification to the Ensemble-Stat wrapper.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1464]
## Describe the Enhancement ##
The PR dtcenter/MET#2067 issue dtcenter/MET#1259 enhances the Ensemble-Stat tool to support the computation of probabilistic statistics. This impacts the Ensemble-Stat configuration file in 3 ways:

1. Adds a new configuration option to specify the size of the Nx2 probabilistic contingency tables used.
```
prob_pct_thresh = [ ==0.25 ];
``` 

2. Adds support for an existing option to specify the number of Economic Cost-Loss Value points to be used (already supported in other wrappers).
```
eclv_points = 0.05;
```

3. Adds 5 new entries to the existing output_flag option to specify which probabilistic outputs should be written.
```
output_flag = {
...
   pct   = NONE;
   pstd  = NONE;
   pjc   = NONE;
   prc   = NONE;
   eclv  = NONE;
};
```

The task is to make the Ensemble-Stat options configurable via the METplus wrapper.

### Time Estimate ###
1/2 day (?)

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe 
- [x] Select **scientist(s)** or **no scientist** required: @j-opatz to advise on application to use cases

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
