### ISSUE TITLE
New Use Case: CFSv2 temporal standardized anomalies and BSS, BS output

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1531]
## Describe the New Use Case ##
After numerous improvements to the METplus suite, a CFSv2 use case is ready to be added to the METplus repository. This use case will demonstrate several important aspects specifically related to the S2S verification timescale:

Raw CFSv2 ensemble data will be read in via SeriesAnalysis and a temporal mean and standard deviation for each ensemble member will be constructed.
These files will then be passed to Gen-Ens-Prod and used to normalize the individual ensemble members. Also in this step the Gen-Ens-Prod tool will calculate a rough Ensemble frequency of three given thresholds, representing the tercile structure prevalent in climatology verification work.
Finally, the use case will call SeriesAnalysis and GridStat to calculate BS/BSS values.

The steps in this use case will be nearly identical to another use case that will be created, except that use case will produce HSS values (using the CTS/MCTS line types vs PSTD line type for BS/BSS).

### Use Case Name and Category ###
SeriesAnalysis_fcstCFSv2_obsGHCNCAMS_climoStandardized_MultiStatisticTool

This use case will reside in the S2S category.

### Input Data ###
Fcst: CFSv2 Ensemble (29 files, 1 year per file, 60MB each)
Obs: GHCN-Cams (234MB)
Climo: GHCN-Cams (6MB)
Stddev: GHCN-Cams (6MB)

All datasets were provided by CPC

### Acceptance Testing ###
Use case should run successfully in METplus and replicate existing verification results produced by CPC

14 min, 50ish seconds run time

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
CPC via JTTI FY20

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
Currently, this use case is held up due to an issue discovered with FCST_IS_PROB. This issue was detailed in a new Github issue #1586 and will need to be resolved before this use case can be fully added to the repo. In the meantime, the PR will be put together
