### ISSUE TITLE
Update Python requirement to 3.8.6

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1566]
## Describe the Task ##
Python 3.6 is no longer supported for security updates, so we need to update the requirement for the wrappers to 3.8. Python 3.8.6 is used by other METplus components.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
- [x] Update documentation to reflect new version
- [x] Update Conda environments on RAL workstations to use 3.8.6
- [x] Rebuild all Conda environments used for automated tests (scripts/docker/docker_env)
- [x] Review other areas that may need to be updated

### Relevant Deadlines ###
5.0.0 release

### Funding Source ###
2792541

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
**Consider creating an issue for MET to update the version used for Python embedding (in Docker, documentation, environment files for local installs, etc.)**
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
dtcenter/MET#2196 must be completed as part of this work.

**Comment by georgemccabe** [comment]
Cartopy 0.20.x supports an environment variable CARTOPY_DATA_DIR to set the location of shapefiles. We should update the instructions to instruct users to use this variable instead of CARTOPY_DIR as added for #933. The solution implemented for that issue only affects CyclonePlotter wrapper, so use cases that require cartopy will still attempt to download these shapefiles. Using CARTOPY_DATA_DIR will fix the issue for all uses of cartopy.

**Comment by georgemccabe** [comment]
There are other changes required to move to require 3.8.6 that were discovered:

- [x] Update metplus/PYTHON_VERSION
- [x] Update enviroment.yml
- [x] Update .readthedocs.yaml
- [x] Look for other updates that may be needed

Updating the PYTHON_VERSION file will cause run_metplus.py to error and exit if a version lower than 3.8.6 is used. We should consider the impacts of this change.

**Comment by georgemccabe** [comment]
We discussed this task in a METplus Engineering meeting and decided that we do not want to prevent the METplus wrappers from running if the user is not using Python 3.8.6 or higher. To handle this, we can add metplus/PYTHON_VERSION_MIN which will contain the minimum version needed to run the wrappers (3.6.3 for f-string support). This will be used to report the existing error. We will also add logic to print a warning message if the version of Python used is less than the recommended version set in PYTHON_VERSION.
