### ISSUE TITLE
Create component icons for use in METplus flowcharts.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1576]
## Describe the Task ##

The tasks for this issue include.

- Create a set of small png images to be used in flowcharts that demonstrate METplus workflows. However, exactly what those images should be requires more definition. @TaraJensen recommends using color-shaded ovals from the [MET Flowchart](https://github.com/dtcenter/MET/tree/main_v10.1/met/docs/Flowchart). Also consider using some of the other icons that Cindy's made in the last couple of years. The icons should include file I/O, individual MET tools, and the other METplus components (METplotpy, METcalcpy, METdatadb, METviewer, and METexpress).
- Store the resulting images somewhere in the [METplus docs](https://github.com/dtcenter/METplus/tree/main_v4.1/docs) directory. Perhaps add a Flowchart sub-directory, similar to what exists in the MET repo.
- Ideally, we'd also add flowcharts to each of the existing METplus use cases. Consider storing the flowchart as both an image to be included in the use case documentation and as a powerpoint that can easily be downloaded, copied, and modified for other use cases. But this may be too large of a task.
- Update the METplus issue template for [New Use Cases](https://github.com/dtcenter/METplus/blob/main_v4.1/.github/ISSUE_TEMPLATE/new_use_case.md) to make some reference to creating a flowchart.
- Consider adding a new section to the documentation with more clear direction about creating flowcharts.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
