### ISSUE TITLE
Enhancement: Resolve findings from SonarQube for 6.0.0

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/METplus#1610]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##

*Provide a description of the enhancement request here.*

http://mandan:9000/dashboard?id=org.sonarqube%3AMETplus_python_NB

9 blocker and 18 majors

-- 9 blockers --

"%" to "%%":
- [internal_tests/produtil/testme.py#L860](https://github.com/dtcenter/METplus/blob/develop/internal_tests/produtil/testme.py#L860)
- [internal_tests/produtil/testme.py#L2547](https://github.com/dtcenter/METplus/blob/develop/internal_tests/produtil/testme.py#L2547)
- [produtil/testing/parse.py#L1350](https://github.com/dtcenter/METplus/blob/develop/produtil/testing/parse.py#L1350)
- [produtil/testing/parsetree.py#L749](https://github.com/dtcenter/METplus/blob/develop/produtil/testing/parsetree.py#L749)

```
testme.py#L860:
    raise ValueError("Key \"%s\" contains a \"%\""%(key,))

testme.py#L2547:
    raise ValueError('%s: cannot have "%" in a parameter name.'%(
                varname,))

parse.py#L1350:
 raise ValueError('%s: cannot have "%" in a parameter name.'%(

produtil/testing/parsetree.py#L749:
            raise ValueError("Key \"%s\" contains a \"%\""%(key,))
```
Unused or missing argument
- [internal_tests/produtil/testme.py#743](https://github.com/dtcenter/METplus/blob/develop/internal_tests/produtil/testme.py#L743) & [internal_tests/produtil/testme.py#L963](https://github.com/dtcenter/METplus/blob/develop/internal_tests/produtil/testme.py#L963)

- [produtil/testing/parsetree.py#532(https://github.com/dtcenter/METplus/blob/develop/produtil/testing/parsetree.py#532) & [produtil/testing/parsetree.py#947](https://github.com/dtcenter/METplus/blob/develop/produtil/testing/parsetree.py#947)

```
testme.py#L743:
    def as_parameters(self,con):

testme.py#L963: missing argument
    return s.as_parameters()

produtil/testing/parsetree.py#532
    def as_parameters(self,con):
produtil/testing/parsetree.py#947:
    return s.as_parameters()
```

Infinitive recursive calls at [produtil/testing/parsetree.py#L375-L376](https://github.com/dtcenter/METplus/blob/develop/produtil/testing/parsetree.py#L375-L376)
```
    def check_define(self,key,value):
        return self.check_define(key,value)

```

Not used argument, tm:  [produtil/mpiprog.py#L272-L276](https://github.com/dtcenter/METplus/blob/develop/produtil/mpiprog.py#L272-L276)
```
    def delturbomode(self,tm):
        """!Removes the request for turbo mode to be on or off."""
        self._turbomode=None
    turbomode=property(getturbomode,setturbomode,delturbomode,
                       "Turbo mode setting for this group of MPI ranks.")
```

ArithPTParserError is not defined at  [produtil/testing/setarith.py#L47](https://github.com/dtcenter/METplus/blob/develop/produtil/testing/setarith.py#L47)
```
__all__=[ 'ArithPTParserError', 'arithparse', 'ArithKeyError' ]
```

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
PR #2200 contains the first round of fixes to appease SonarQube.
Before changes: 21 bugs, 421 code smells
After changes: 2 bugs (not really bugs), 109 code smells
