### ISSUE TITLE
Update Hovmoeller Use case to use updated Hovmoeller plotting

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#1650]
*Replace italics below with details for this issue.*

## Describe the Task ##
The original METplotpy hovmoeller plot was not configurable for users who are running from the command line (and do not have permission to modify the code or to indicate where to save the output plot).  Additionally, this code did not follow the paradigm that other METplotpy plots employed: default config file and custom config file.  Instead, it was a mix of a "default" config file that couldn't be modified by some users (ie those that don't have permission to modify the source code that is installed in a common area) with command line arguments. 

### Time Estimate ###
*Estimate the amount of work required here.*
~2 days 

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Update the hovmoeller.yaml config file to match the updated config file structure*
- [ ] *Update/simplify the hovmoeller.py code, the METplotpy/metplotpy/plots/hovmoeller.py code has support for a custom configuration file to override the settings in the default.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Minna Win, Hank Fisher
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority** Assigned High priority because changes to hovmoeller code in METplotpy will be in the beta1 release
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
