### ISSUE TITLE
New Use Case: PANDA-C use cases

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#1686]
## Describe the New Use Case ##
This is a collection of use cases to replace outdated Air Force verification with new METplus methodology. The same core code will be utilized via Python Embedding, and sources for the forecast and observation datasets will vary.

Configurations will typically call GridStat 3 times, with varying setups (probability, neighborhood, etc)

### Use Case Name and Category ###
Use case names will be added when each configuration file is completed. To see a list of all expected/planned use cases, see the sub-issues section.

### Input Data ###
Forecast: MPAS, GFS
Observation: ERA5, SATCORPS, MERA
Input sizes may differ, depending on required variables for the given use case

### Acceptance Testing ###
*Describe tests required for new functionality.*
*As use case develops, provide a run time here*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
This is the proposed order that the use cases will be created in
- [x] MPAS to SATCORPS: low and total cloud fraction 
- [x] MPAS to SATCORPS: cloud top height, cloud base height
- [x] GFS to SATCORPS: low and total cloud fraction
- [x] GFS to SATCORPS: cloud top pres, cloud top temp
- [x] MPAS to MERRA2: low and total cloud fraction
- [x] GFS to MERRA2: low and total cloud fraction
- [x] MPAS to ERA5: low and total cloud fraction
- [x] MPAS to ERA5: cloud base height
- [x] GFS to ERA5: low and total cloud fraction

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2771021

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
