### ISSUE TITLE
Internal: Rename internal_tests directory to internal

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1748]
We would like to be consistent across METplus components, so we should rename this directory to match what MET uses.

## Describe the Task ##
* Rename the internal_tests directory to internal
* Rename the internal_tests/scanning directory to internal/scripts
* Update any scripts that reference these files
* Coordinate with @hsoh-u to ensure that any necessary changes to the automated sonarqube runs are made

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
by 5.0.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
**Corresponding issues for METdataio, METplotpy, and METcalcy (and others?) should be created**

- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@georgemccabe Should scripts/docker also move to internal?  That would be consistent with the MET repo.

**Comment by georgemccabe** [comment]
> @georgemccabe Should scripts/docker also move to internal? That would be consistent with the MET repo.

@jprestop, I suppose it would be nice to be consistent across repos. We will need to update the build rules on DockerHub dtcenter/metplus while preserving the old location for any bugfix releases to 4.1. This could be accomplished by creating a new build rule that matches v4.1* pointing to the old location of the docker directory and update the existing build rules to point to the new location.
