### ISSUE TITLE
Update the EnsembleStat wrapper and use case examples to remove ensemble post processing logic

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1816]
## Describe the Enhancement ##
PR dtcenter/MET#2265 for issue dtcenter/MET#1908 removes ensemble post-processing logic from the Ensemble-Stat tool. It has completely moved over the the Gen-Ens-Prod tool instead.

This issue is to update METplus accordingly. Those updates should include:
- Update the config options supported by the EnsembleStat wrapper.
   - No longer set `ens`, `nbrhd_prob`, `nmep_smooth`, and `ensemble_flag` dictionaries.
   - Move `ens_thresh` and `vld_thresh` from the `ens` to `fcst` dictionary.
   - Add support for the new `nc_orank_flag` dictionary (which is similar to old `ensemble_flag`).
- Review the existing METplus Use Cases and apply the following logic:
   - If the use case had been calling EnsembleStat WITHOUT the `-grid_obs` or `-point_obs` command line options, we can assume it was only doing ensemble post-processing. That call to EnsembleStat should be replaced with a call to GenEnsProd instead. The corresponding file names will change from "ensemble_stat" to "gen_ens_prod" as well.
   - If the use case called EnsembleStat with observations, but no other MET tool (e.g. PointStat, GridStat, MODE) was called afterwards, we DO NOT need to add a call to the GenEnsProd wrapper.
   - If the use case called Ensemble with observations and then called another MET tool, we DO need to add in a call to the GenEnsProd wrapper to generate the ensemble products to be verified by that other MET tool.
 
- Once all the changes have been made to the use cases and all differences have been rectified, consider updating the use case names from EnsembleStat to GenEnsProd to name them accurately following the use case conventions.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe 
- [x] Select **scientist(s)** or **no scientist** required: @j-opatz 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This issue should not be closed after merging PR #1820. Additional steps needed are:

* Rename use cases that are named starting with EnsembleStat that no longer run EnsembleStat (GenEnsProd only)
* Rename output filenames that include ensemble_stat that were created by GenEnsProd (this was done to make diffing output easier, but the names should reflect the tool used)

Also, documentation should be added to assist users with updating their config files that use EnsembleStat, but that is covered in a new issue #1819

**Comment by georgemccabe** [comment]
Closed by #1820 and #1823
