### ISSUE TITLE
New Use Case: Read in precip gauge data for use in METplus with python embedding

### ISSUE THREAD

**Issue by PerryShafran-NOAA** [dtcenter/METplus#1828]
*Replace italics below with details for this issue.*

## Describe the New Use Case ##
*Provide a description of the new feature request here.*

Modify METplus to read in the COCORAHS precip gauge data, a CSV file, and use python embedding to allow ASCII2NC to create a file for use in PointStat

### Use Case Name and Category ###
*Provide use case name, following Contributor's Guide naming template, and list which category the use case will reside in.*

PointStat_fcstURMA_obsCOCORAHS_ASCIIprecip
In the model_applications/precipitation category

*If a new category is needed for this use case, provide its name and brief justification*

### Input Data ###
*List input data types and sources.*
*Provide a total input file size, keeping necessary data to a minimum.* 

### Acceptance Testing ###
*Describe tests required for new functionality.*

Use ASCII2NC and python embedding to create the precip gauge observation file.  If this creates a netCDF file that PointStat can read for verification, then the functionality will be successfully created.  

*As use case develops, provide a run time here*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

1-2 week time is sufficient.  

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

EVS verification code that includes this verification is due to be complete on December 1, 2022.  

### Funding Source ###
2773542

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [X] [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by LoganDawson-NOAA** [comment]
Attaching sample file that needs to be read by MET.

[CoCoRaHS.20220914.DailyPrecip.csv](https://github.com/dtcenter/METplus/files/9656021/CoCoRaHS.20220914.DailyPrecip.csv)

**Comment by j-opatz** [comment]
The Python embedding script is complete, and the use case should come together quickly now.

@PerryShafran-NOAA and @LoganDawson-NOAA , what type of forecast will the CoCoRaHS data be validating? The use case name only says "ANALYSES", so I wasn't sure. If I can get a copy of the model file you'd like to use to compare to the 2022-09-14 point data you've provided, I can get the use case with ASCII2NC -> PointStat set up. 

If you'd like to use a different date, just be sure to send along the observation and model datasets!
