### ISSUE TITLE
StatAnalysis - Support setting multiples jobs

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1842]
Currently only 1 job can be specified via StatAnalysis wrapper using the STAT_ANALYSIS_JOB_NAME and STAT_ANALYSIS_JOB_ARGS config variables. Only 1 job is allowed to be specified via the command line arguments to stat_analysis, but multiple jobs can be specified in the STATAnalysisConfig file.

## Describe the Enhancement ##
Enhance the StatAnalysis wrapper to support setting multiple jobs.
Instead of setting STAT_ANALYSIS_JOB_NAME and STAT_ANALYSIS_JOB_ARGS, users can set STAT_ANALYSIS_JOB1, STAT_ANALYSIS_JOB2, etc. The -job argument and job type that was previously specified via STAT_ANALYSIS_JOB_NAME will be included in the value of STAT_ANALYSIS_JOB\<n\>.

While the following will still be supported:

```
STAT_ANALYSIS_JOB_NAME = filter
STAT_ANALYSIS_JOB_ARGS = -dump_row [dump_row_file]
```

the same job command can be specified using:

```
STAT_ANALYSIS_JOB1 = -job filter -dump_row [dump_row_file]
```

and additional jobs can be specified with JOB2, JOB3, etc.

@CPKalb also discovered that filename template tags are not supported in the job arguments. The [dump_row_file] and [out_stat_file] syntax are substituted with the values from MODEL\<n\>_STAT_ANALYSIS_DUMP_ROW_TEMPLATE and MODEL<n\>_STAT_ANALYSIS_OUT_STAT_TEMPLATE respectively. The logic should also be enhanced to substitute filename template tags anywhere in the job value so that multiple jobs can more easily be customized.

### Time Estimate ###
~2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
5.0.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required - @CPKalb as needed for testing

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
