### ISSUE TITLE
Internal: Fix GitHub Actions warnings - update the version of actions and replace set-output

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1863]
This is related to dtcenter/MET#2297

## Describe the Task ##
Warnings have appeared in GHA runs that need to be resolved. This involves:

**1. Modifying all GitHub Actions workflow files (found in .github/workflows) to:**
* Update version of actions/checkout to v3
* Update version of actions/setup-python to v4
* Update version of actions/upload-artifact to v3
* Update version of actions/download-artifact to v3
* Update version of actions/github-script to v6

Example:
Previous:
`      - uses: actions/checkout@v2`
New:
`      - uses: actions/checkout@v3`

**2. Modify all scripting logic in GitHub Actions workflows (this may be in workflow YAML files or in scripts that are called by a workflow) to:**
* Change use of ::set-output to use >> $GITHUB_OUTPUT

Example:
Previous:
`echo ::set-output name=run_compile::$run_compile`
New:
`echo "run_compile=${run_compile}" >> $GITHUB_OUTPUT`

### Time Estimate ###
A few hours including confirming full test suite run does not include any more warnings

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
ASAP

### Funding Source ###
NONE

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components. -- Issues will be needed for each other METplus component that uses GHA
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
