### ISSUE TITLE
StatAnalysis - Allow processing of time ranges other than daily

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#1871]
Currently StatAnalysis wrapper truncates the INIT/VALID_BEG/END times to only use YYYYMMDD. The hours are subset using the lists in the config file, i.e. FCST_VALID_HOUR, OBS_VALID_HOUR, FCST_INIT_HOUR, OBS_INIT_HOUR. Users may want to run the tool on a more specific time range.

## Describe the Enhancement ##
Enhance the wrapper to use the full time specified with INIT/VALID_BEG/END. To preserve previous behavior, if only YYYYMMDD is specified, then set the time range to include the full day of the end date, e.g. if VALID_END = 20221018, then set `valid_end = "20221018_235959"`

### Time Estimate ###
~1-2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
5.0.0

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [X] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [X] Complete the development and test your changes.
- [X] Add/update log messages for easier debugging.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [X] Push local changes to GitHub.
- [X] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [X] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
