### ISSUE TITLE
Add documentation for creating GitHub Projects to the Contributor's Guide

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#1885]
## Describe the Task ##
In the [GitHub Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) section of the Contributor's Guide:

1. Move section [6.2 Sequence of Events - Contributing Code](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html#sequence-of-events-contributing-code) to be section 6.3
2. Add a new section 6.2 Using GitHub Projects for Stages of the METplus Release Cycle.  In that section, write at least a few sentences to describe our use of GitHub Projects for the various [Stages of the METplus Release Cycle](https://metplus.readthedocs.io/en/latest/Release_Guide/index.html#stages-of-the-metplus-release-cycle).  Include the following directions for creating (copying) or updating a GitHub Project:
- copy/update the title and description
- add new columns to the default view
- define all the other views
- change from default private to public
- copy over the workflow automation settings
- add the METplus team with write permission plus any other admins
- go to each repo and "add" the new project to it

3.  While working on this page, fix the broken link for the text "best practices for collaboration on GitHub" in section 6.1.  The broken link is: https://metplus.readthedocs.io/en/latest/Contributors_Guide/docs.google.com/document/d/1DxsViogPdA0uObHgNx4YFKd4ClC-m9UFcX0rO-ZJTY0/edit?pli=1#heading=h.g4dgc8a6erna, whereas the link should be: https://docs.google.com/document/d/1DxsViogPdA0uObHgNx4YFKd4ClC-m9UFcX0rO-ZJTY0/edit?pli=1#heading=h.g4dgc8a6erna, and add a period at the end of the sentence.  Also change "WRF-Hydro team" to "formerly WRF-Hydro team" as James left RAL in January 2022 and is currently working in CPAESS but for USGS.

### Time Estimate ###
1 to 3 days of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
TBD

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Adding Discussion from Slack to this issue to keep track of this information which may be relevant:

> While setting up a development project for the next release after MET 11.0.0, I ran across a project template that supports [development cycles (i.e. "iterations")](https://docs.github.com/en/issues/planning-and-tracking-with-projects/understanding-fields/about-iteration-fields). Please see [MET-11.1.0 Development](https://github.com/orgs/dtcenter/projects/64). When you assign something to the project, you can assign it to an iteration (which I renamed "cycle"). See the pic below. I named the cycles beta1, 2, ... 5 to follow our existing conventions. I'm hoping this will allow us to use a single project for each release, rather 6 or 7 of them.
I plan to try it out for MET to see how it goes.

> I found something else I like... the "status -> group by value" option is nice. Makes it really easy to see the status across multiple issues.
