### ISSUE TITLE
Enhance the GridStat and PointStat wrappers to handle the addition of SEEPS.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#1953]
## Describe the Enhancement ##

PR dtcenter/MET#2344 for issue dtcenter/MET#1943 adds support to the MET Grid-Stat tool for computing SEEPS, and tweaks it for Point-Stat. This required 3 changes to the Grid-Stat configuration file and 1 change to the Point-Stat configuration file. This issue is to update the METplus GridStat and PointStat wrappers accordingly.

The specific diffs can be seen [here for Grid-Stat](https://github.com/dtcenter/MET/pull/2344/files#diff-f430b07c8625fd8a33861f202a2fd8c8f860ba8bb1bac65afe90cda7ddbfb6a3) and [here for Point-Stat](https://github.com/dtcenter/MET/pull/2344/files#diff-89f9b3b49d954d8c025b1d74c6549b5ce186410cb02d85b9fe6692c4107339af), but are described below:

1. Add Grid-Stat entry for `output_flag.seeps` which can be set to NONE, STAT, or BOTH with default = NONE.
2. Add Grid-Stat entry for `nc_pairs_flag.seeps` which can be set to TRUE or FALSE with default = FALSE.
3. Add Grid-Stat top-level `seeps_p1_thresh` option to define a threshold with default = NA (where NA is a threshold type always evaluating to true).
4. Add Point-Stat top-level `seeps_p1_thresh` option as described above.

### Time Estimate ###
4 hours

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe 
- [x] Select **scientist(s)** or **no scientist** required: none needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Re-opening this issue since testing by @robdarvell and @RachelNorth found an issue related to the handling of SEEPS in METplus. While the [GRID_STAT_OUTPUT_FLAG_SEEPS](https://metplus.readthedocs.io/en/develop/Users_Guide/glossary.html#term-GRID_STAT_OUTPUT_FLAG_SEEPS) configuration option exists, we are missing similar config options for Point-Stat. Please add support for POINT_STAT_OUTPUT_FLAG_SEEPS and POINT_STAT_OUTPUT_FLAG_SEEPS_MPR to control the settings for `output_flag.seeps` and `output_flag.seeps_mpr` in the MET Point-Stat config file.
