### ISSUE TITLE
Documentation: Update Coding Standards section in Contributor's Guide

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#1974]
## Describe the Task ##
Review the [Coding Standard's Section of the METplus Contributor's Guide](https://metplus.readthedocs.io/en/develop/Contributors_Guide/coding_standards.html) (also linked to in the METplotpy Contributor's Guide) to ensure it is accurate and up-to-date.  In reviewing the METplotpy Contributor's Guide, it came to our attention that Vulture is a dead code linter.  Review this page with the METplus component's team and decide how to proceed with updating.

Consider using tools (if not already being used) to enforce coding standards.

### Time Estimate ###
< 1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
TBD

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@georgemccabe Thank you for bringing it to my attention that there is no assignee on this issue.  I have assigned this issue to you.  Since you are the lead engineer for the METplus wrappers, I think you would be the best person to review the Coding Standards section of the Contributor's Guide and ensure it is accurate and up-to-date.  While the issue arose because the METplotpy Contributor's Guide Coding Standards section links to the METplus Contributor's Guide Coding Standards section, it is not a requirement that METplus and METplotpy have the same coding standards.  This section should contain whatever rules, techniques, and guidelines contributors should follow to create clean, readable, and efficient code with minimal bugs and errors, for the METplus wrappers code.  If METplus wrappers and METplotpy share the same coding standards, it would be great to have consistency, but if they differ that is fine, since METplotpy has its own Contributor's Guide and can document its own standards.
