### ISSUE TITLE
New Use Case: Read in Argo profile data netCDF files for use in METplus with python embedding

### ISSUE THREAD

**Issue by GwenChen-NOAA** [dtcenter/METplus#1977]
*Replace italics below with details for this issue.*

## Describe the New Use Case ##
*Provide a description of the new feature request here.*

To create a new use case and python code to read Argo profile data into PointStat using python embedding.

### Use Case Name and Category ###
*Provide use case name, following Contributor's Guide naming template, and list which category the use case will reside in.*
*If a new category is needed for this use case, provide its name and brief justification*

PointStat_fcstRTOFS_obsArgo_netCDF_temp_sali
In the Model Applications/Marine and Cryosphere category

### Input Data ###
*List input data types and sources.*
*Provide a total input file size, keeping necessary data to a minimum.* 

The netCDF files are available on WCOSS2 at /lfs/h1/ops/dev/dcom/$YYYYMMDD/validation_data/marine/argo.

### Acceptance Testing ###
*Describe tests required for new functionality.*

Use python embedding and PointStat to read in Argo profile data for RTOFS ocean temperature and salinity verifications, then the functionality will be successfully created. Utilize available python packages on WCOSS2 and test run on WCOSS2.

*As use case develops, provide a run time here*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

1-2 week time is sufficient.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

EVS Alpha Test was due on December 1, 2022 and Beta Test deadline is to be determined.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

2773542

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
        @JohnHalleyGotway 
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Met on 12/15/2022 to discuss the development of this new use case.

See:
http://www.argodatamgt.org/content/download/12096/80327/file/argo-dm-user-manual.pdf

Would like to develop this use case using METplus version 5.0.0 prior to June 1, 2023.

ARGO file format is NetCDF:
[https://data-argo.ifremer.fr/geo/${basin}/${YYYY}/${MM](https://data-argo.ifremer.fr/geo/$%7Bbasin%7D/$%7BYYYY%7D/$%7BMM))
   e.g. https://data-argo.ifremer.fr/geo/atlantic_ocean/2022/12/

On WCOSS2:
/lfs/h1/ops/dev/dcom/YYYYMMDD/validation_data/marine/argo/argo_${YYYYMMDD}_${basin}_prof.nc
   Basin = atlantic_ocean, indian_ocean, and pacific_ocean

What variables should be extracted?
- TEMP (temperature) with TEMP_QC, PSAL (ocean salinity) with PSAL_QC, PRES (vertical coordinate) in "decibars" with PRES_QC.
- Question of "ADJUSTED" variables? Make it easy to switch between regular and adjusted... use the ADJUSTED values by default.

What valid times should be reported?
- Read Julian day values from the JULD variable as an offset from the reference time from the REFERENCE_DATE_TIME variable and report that separately for each profile (i.e. N_PROF).
- Note that JUL_QC provides a QC flag for the timestamp and we could only use date whose timestamps have a good QC value.
```
>>> import datetime
>>> REFERENCE_DATE_TIME = datetime.datetime(1950, 1, 1)
>>> juld_val = 26645.6170138889
>>> juld_delta = datetime.timedelta(days=juld_val)
>>> juld_delta
datetime.timedelta(days=26645, seconds=53310, microseconds=1)
>>> REFERENCE_DATE_TIME + juld_delta
datetime.datetime(2022, 12, 14, 14, 48, 30, 1)
```
- Set station id = PLATFORM_NUMBER
- Set message type = ARGO as a constant
- No concern about the DIRECTION variable. It is specified separately for each profile and can be ascending or descending. Since the PRES variable is 2-d (`float PRES(N_PROF, N_LEVELS) ;`), presumably the order of the level values for each profile are consistent with the order of the TEMP and SAL variables.

See these details:
In particular, if you are doing scientific work sensitive to small pressure biases (e.g. calculations of global ocean heat content or mixed layer depth) Argo recommends the following guidelines:

    Use the quality flags in the Argo data files and data labeled with QC = 1
    Only use delayed-mode data (D files)
    Only use ADJUSTED data variables
    PRES_ADJUSTED_ERROR should be checked and where values are greater than 20db, these data should be rejected from https://argo.ucsd.edu/data/data-faq/

The model outputs data in vertical levels of meters below surface. Based on [this reference](https://www.translatorscafe.com/unit-converter/en-US/pressure/53-58/decibar-meter%20sea%20water/), 1 decibar = 1 meter of sea water (msw). So we should store those "pressure" values in the "height" column for the observation.

The model runs daily and is verified at 00Z.

Update this documentation to indicate that interpolation by height is done linearly both above/below the surface:
https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html#interpolation-matching-methods

Update the ascii2nc usage statement to replace `(msl or agl)` with `(e.g. msl, agl)` since the height coordinate for this data is in "msw" (meters of sea water).

Recommend that we define the units of the observations in the resulting `met_point_data` object.

See https://github.com/dtcenter/MET/issues/2302.

- The METplus team will write a python embedding script that populates the point_data object and calls this new utility function to convert that to met_point_data for use in Point-Stat.
- Gwen with test that that actually work on WCOSS2 by running point_point_obs first, using the example we send. Recommend that we add this example to the [python embedding website](https://dtcenter.org/community-code/model-evaluation-tools-met/sample-analysis-scripts), or perhaps this content should move to a user's guide?
- Gwen will develop a new METplus use case following instructions in [Section 8](https://metplus.readthedocs.io/en/latest/Contributors_Guide/add_use_case.html#adding-use-cases) of the Contributor's Guide.

**Comment by DanielAdriaansen** [comment]
ARGO user manual with tables of QC flags, etc.:
http://www.argodatamgt.org/content/download/12096/80327/file/argo-dm-user-manual.pdf

When we update the ascii2nc usage statement to reflect the change to `(e.g. msl, agl)` as @JohnHalleyGotway notes above, we should also update the documentation here as well:
https://met.readthedocs.io/en/latest/Users_Guide/reformat_point.html#id8

**Comment by georgemccabe** [comment]
I was able to get a Python Embedding script written to read the ARGO observations into MET. I tested it with ascii2nc and plot_point_obs. I checked in the [read_argo_metplus.py](https://github.com/dtcenter/METplus/blob/feature_1977_argo/parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstRTOFS_obsArgo_netCDF_temp_sali/read_argo_metplus.py) script to GitHub in a feature branch. There are comments to describe the logic used to perform quality control checks on the data to skip certain observations.

To get the script to work, I had to add the share/met/python directory of the MET install location to the PYTHONPATH environment variable. We have discussed improvements to the MET logic to prevent the need for this step. This can be handled through the use case conf settings for now. Here are some sample commands I used to run locally:

```
export PYTHONPATH=/usr/local/met/share/met/python
/usr/local/met/bin/ascii2nc -format python "/home/mccabe/METplus/parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstRTOFS_obsArgo_netCDF_temp_sali/read_argo_metplus.py /d1/projects/METplus/METplus_Data/development/argo/atlantic_ocean/2022/12/20221214_prof.nc" /home/mccabe/out.nc
/usr/local/met/bin/plot_point_obs "PYTHON_NUMPY=/home/mccabe/METplus/parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstRTOFS_obsArgo_netCDF_temp_sali/read_argo_metplus.py /d1/projects/METplus/METplus_Data/development/argo/atlantic_ocean/2022/12/20221214_prof.nc" /home/mccabe/out.ps
```

**Question:** Where can I find a sample RTOFS file to use for forecast input to PointStat?

**Comment by GwenChen-NOAA** [comment]
George,

If you have access to Cactus, you can get RTOFS files from my ptmp
directory
at /lfs/h2/emc/ptmp/Lichuan.Chen/evs/v1.0/prep/rtofs/rtofs.$YYYYMMDD.
These are the original RTOFS forecast files in tri-polar grid.  Use the *_
prog.nc files, which contain sst and sss.  If you want RTOFS files in
lat-lon grid, you can use the rtofs_glo_2ds_*_prog.buoys.nc files under
the buoys subdirectory.  If you'd like me to upload sample data files to
the METplus ftp site, please let me know.

Many thanks,
Gwen

**Comment by georgemccabe** [comment]
Gwen, I don't have access to Cactus, but it looks like we already have a sample RTOFS files that contain sss and sst from [another METplus use case](https://metplus.readthedocs.io/en/latest/generated/model_applications/marine_and_cryosphere/GridStat_fcstRTOFS_obsSMAP_climWOA_sss.html). The file I have is a 24 hour lead initialized on 20210501. It looks like the 20210502 ARGO data is still available on the website. You can use a different run time for the use case if you'd prefer. I just wanted to see what would be involved to read the data into MET.

**Comment by georgemccabe** [comment]
@GwenChen-NOAA, since there are existing use cases that reads the sss and sst fields from the RTOFS data into MET, I am confident that this will be achievable in a PointStat use case using the ARGO data.

I think the next step is to run the Python script on Cactus to ensure that it works as expected. I added a debug option to the script, so if you include the word _debug_ as the 2nd argument to the script, you will get screen output that shows which QC checks did not pass and the values read from the data.

I also created a [METplus config file](https://github.com/dtcenter/METplus/blob/feature_1977_argo/parm/use_cases/model_applications/marine_and_cryosphere/ASCII2NC_obsArgo_netCDF_temp_sali.conf) that calls ASCII2NC and PlotPointObs on the ARGO data. Once you are satisfied with the Python script, then you should be able to develop a new use case to call PointStat referring to the existing use cases. Please reach out if you have any issues or questions with this part.

**Comment by GwenChen-NOAA** [comment]
George,

Thank you so much for the quick turnaround.  I will test run it and let you
know how it goes.  Happy holidays!

Gwen

**Comment by GwenChen-NOAA** [comment]
George,

I loaded the MET 10.1.2/METplus 4.1.4 modules on Cactus and did the
following:

> export
PYTHONPATH=/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/python
> ascii2nc -format python
"/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/EVS/ush/rtofs/read_argo_metplus.py
20221116_prof.nc" 20221116_prof.metplus.nc

But I got the error message below:

DEBUG 1: Config File:
/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/config/Ascii2NcConfig_default
Traceback (most recent call last):
  File
"/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/wrappers/set_python_env.py",
line 9, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
ERROR  :
ERROR  : Python3_Script::Python3_Script(const char *) -> unable to open
script "set_python_env"

We do have numpy on Cactus.  I have been using it for other python codes.
Is there other environment variables I need to set than PYTHONPATH?

Thanks,
Gwen

**Comment by georgemccabe** [comment]
Hi @GwenChen-NOAA, if MET 10.1.2 was installed with Python Embedding support, then it should be able to find numpy.

If the module loads have set PYTHONPATH, then setting it the way you have will overwrite those values. That may explain why numpy can't be found. You can check this by running the module commands then run `echo $PYTHONPATH`. You can add to the existing PYTHONPATH by running this instead:

` export PYTHONPATH=/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/python:$PYTHONPATH`

Let me know if that fixes the issue.

**Comment by GwenChen-NOAA** [comment]
Thanks, George!  You're right.  I loaded python 3.8.6 separately and it got
overwritten without :$PYTHONPATH.  So I did:

> export
PYTHONPATH=/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/python:$PYTHONPATH
> echo $export
PYTHONPATH=/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/python:$PYTHONPATH

/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/python:/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages

> ascii2nc -format python
"/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/EVS/ush/rtofs/read_argo_metplus.py
20221116_prof.nc" 20221116_prof.metplus.nc

Now I got:

DEBUG 1: Config File:
/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/config/Ascii2NcConfig_default
Traceback (most recent call last):
  File
"/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen/EVS/ush/rtofs/read_argo_metplus.py",
line 11, in <module>
    from met_point_obs import convert_point_data
ImportError: cannot import name 'convert_point_data' from 'met_point_obs'
(/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/python/met_point_obs.py)
WARNING:
WARNING: PythonHandler::do_straight() -> an error occurred importing module
"read_argo_metplus"
WARNING:
ERROR  :
ERROR  : ascii2nc-> encountered an error while reading input files!

Any idea what might be wrong?

Thanks,
Gwen

**Comment by GwenChen-NOAA** [comment]
Sorry, the line with echo $PYTHONPATH got messed up.  It should be:

> echo $PYTHONPATH

/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2/share/met/python:/apps/prod/python-modules/3.8.6/intel/19.1.3.304/lib/python3.8/site-packages

Gwen

**Comment by GwenChen-NOAA** [comment]
I don't see 'convert_point_data' in met_point_obs.py.  Do I need MET
11.0.0/METplus 5.0.0 for it?

Thanks,
Gwen

**Comment by DanielAdriaansen** [comment]
> Do I need MET 11.0.0/METplus 5.0.0 for it?

Yes, that's right! Do you have access to those?

**Comment by GwenChen-NOAA** [comment]
It’s on Hera. I will try it tomorrow. 

Gwen

**Comment by GwenChen-NOAA** [comment]
George and Dan,

Thank you both!  The read_argo_metplus.py script works on Hera with MET
11.0.0.  It outputted a netCDF file that can be read by plot_point_obs to
create a location map.  I will work on a config file using point_stat to
generate stats.

*Question:* can point_stat use read_argo_metplus.py to read in multiple
Argo profile data files?  Argo data breaks down by ocean basins.  I need to
read in all 3 basins at once to calculate stats for the global domain.

Thanks again,
Gwen

**Comment by georgemccabe** [comment]
Hi @GwenChen-NOAA,

Currently the script only supports a single input file, but I could easily modify it to read more than 1 file.

**Comment by GwenChen-NOAA** [comment]
That would be very helpful.  Thank you!

**Comment by georgemccabe** [comment]
@GwenChen-NOAA, I just updated the script in the feature branch to support multiple input files as command line arguments.

**Comment by georgemccabe** [comment]
Closed with PR #2148
