### ISSUE TITLE
Calculate Terrestrial Coupling Index (TCI) from CESM output and compare them to FLUXNET2015: 

### ISSUE THREAD

**Issue by mrinalbiswas** [dtcenter/METplus#2011]
*Replace italics below with details for this issue.*

## Describe the New Use Case ##
This use case will calculate Terrestrial Coupling Index (TCI) from CESM CAM and CLM dataset and compare them to Paul Dirmeyer's FLUXNET2015 NETCDF data. The TCI is computed using [Ahmed Method ](https://www.coupling-metrics.com/terrestrial-coupling-index/)and utilizes SOILWATER_10CM and LHFLX data. 
Ref: 
Dirmeyer, P. A. (2011), The terrestrial segment of soil moisture–climate coupling, Geophys. Res. Lett.,  38, L16702, doi:[10.1029/2011GL048268](http://onlinelibrary.wiley.com/doi/10.1029/2011GL048268/abstract)

Dirmeyer, P. A., Z. Wang, M. J. Mbuh, and H. E. Norton (2014), Intensified land surface control on boundary layer growth in a changing climate, Geophys. Res. Lett., 41, 1290–1294, doi:[10.1002/2013GL058826](http://onlinelibrary.wiley.com/doi/10.1002/2013GL058826/full)

### Use Case Name and Category ###
feature_2011_TCI_from_CESM_FLUXNET2015_NETCDF

### Input Data ###
Model: CESM CLM and CAM datasets
Observations: FLUXNET2015

### Acceptance Testing ###
Run the use case and match numbers from CLASP team members
*As use case develops, provide a run time here*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
CLASP

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by mrinalbiswas** [comment]
Changed the name of the feature branch
