### ISSUE TITLE
Documentation: Update the METplus Components Python Requirements

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#2016]
## Describe the Task ##
Update the [METplus Components Python Requirements Documentation](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) for the METplus Analysis tools for recent changes based on testing for official installation on WCOSS2 the **upcoming bugfix release** and in the **develop branch** to ensure that they are current.  This documentation be used by NCO.

### Time Estimate ###
<1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
METplus Analysis Tools Bugfix Release (01/25/2023), although it won't be published until the METplus Bugfix Release.

### Funding Source ###
Split between 2792542 and 2773542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions** (Need to select two Milestones, but can only select one so I listed the Bugfix release)

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This may be a duplicate of #1978

**Comment by jprestop** [comment]
Thanks @georgemccabe.  It's not a duplicate.  There were some changes made to versions of packages for the METplus Analysis tools but this page has not yet been updated.  I neglected to put "for the METplus Analysis tools" in the description so I just added it.

**Comment by jprestop** [comment]
Hi @bikegeek.  I see that this was moved from "Backlog" to "Done" for METplus Version 5.0 Support, but it doesn't look like it has been fully reviewed and updated as I still see the following:

> pandas | >=1.0.5, <=1.2.3 (METdataio)

I didn't check any others, that one just jumped out at me.  @georgemccabe was interested in knowing when this would be complete as he is hoping to cut the METplus bugfix release sometime soon, so I wanted to follow up.

**Comment by bikegeek** [comment]
I will update it, I was waiting to get the versions from upgrading to
Python 3.10 solidified.  I can do it this afternoon.


---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by georgemccabe** [comment]
@bikegeek , @jprestop, It looks like this issue was moved to "Done" for the METplus-5.1.0 Development project, but I don't see a PR for these changes into the develop branch. It looks like the changes were not applied to develop. Re-opening this issue.

**Comment by jprestop** [comment]
> @bikegeek , @jprestop, It looks like this issue was moved to "Done" for the METplus-5.1.0 Development project, but I don't see a PR for these changes into the develop branch. It looks like the changes were not applied to develop. Re-opening this issue.

Thanks @georgemccabe.  I updated the milestone to be METplus-5.1.0 from METplus-5.0.1.

I see that @bikegeek mentioned earlier:
> I will update it, I was waiting to get the versions from upgrading to Python 3.10 solidified.

@bikegeek Do you feel that they are solidified now? Will you be able to do this before the beta2 release on Wednesday or should we reassign to the rc1 release instead?

**Comment by georgemccabe** [comment]
@bikegeek, since I haven't heard back I am going to move this to rc1. Let me know if this has already been completed and I'll move it back.

**Comment by bikegeek** [comment]
sorry, I was out of the office for a few hours.  I finished updating the
tables in the documentation but didn't submit a PR because it was a
sub-task.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
This issue can be closed with the work done in #1978 and with the PR #1978
