### ISSUE TITLE
Documentation: Enhance the Release Notes by adding dropdown menus

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/METplus#2076]
Please use [Sphinx Design for Dropdown menus](https://sphinx-design.readthedocs.io/en/latest/dropdowns.html) . This will allow for searches of material hidden within dropdown menus.

Changes will need to be made to the below files:
1.  config.py 
    add 'sphinx_design' to the "extensions =" section.  (note the underscore.) 
2.  requirements.txt file. 
    add 'sphinx-design==0.3.0' with a dash 
3. METplus/.github/workflows/documentation.yml 
    add a line after this example [line 28](https://github.com/dtcenter/METviewer/blob/505660418afbc1debb301c5f0b4bcd28823b3896/.github/workflows/documentation.yml#L28) . Make sure it is correctly indented.
   python -m pip install -r docs/requirements.txt

It should look like this:
          python -m pip install --upgrade sphinx sphinx-gallery sphinx_rtd_theme
          python -m pip install python-dateutil requests Pillow
          python -m pip install -r docs/requirements.txt

Panel drop downs would be added for the subcategories and sub-subcategories. For example,
-Repository and build
---Installation
---Static Code Analysis
---Testing
---Continuous Integration
-Documentation
-Library code
---Bugfixes
---Python embedding enhancements
---Miscellaneous
---NetCDF Library
---Statistics computations
etc.

## Describe the Task ##
*Provide a description of the task here.*

### Time Estimate ###
*less than a day*

### Sub-Issues ###
None

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
*Split between accounts 2702691 and 2792542.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
