### ISSUE TITLE
Add support for new multivariate MODE settings

### ISSUE THREAD

**Issue by davidalbo** [dtcenter/METplus#2197]
## Describe the Enhancement ##
New parameters have been added to mode (multivariate) that need the option to be set from METplus and documented.  Environment variables in METplus might be these:

METPLUS_MULTIVAR_INTENSITY          This is at the top level, similar to METPLUS_MULTIVAR_LOGIC.   
METPLUS_FCST_MULTIVAR_NAME        This shows up once inside the fcst = {}
METPLUS_FCST_MULTIVAR_UNITS        same 
METPLUS_OBS_MULTIVAR_NAME          This shows up once inside the obs = {}
METPLUS_OBS_MULTIVAR_UNITS          same

In all cases the default is the empty string.  If set, here are some example settings (in the same order as above):
multivar_intensity = [FALSE, TRUE, TRUE];
multivar_name = "Snow";
multivar_units = "LO";
multivar_name = "Precip";
multivar_units = "Z10";

The METPLUS_FCST_MULTIVAR_NAME and METPLUS_OBS_MULTIVAR_NAME have the same multivar_name="value"; format, they are put in different places.  We might want to also allow METPLUS_MULTIVAR_NAME and METPLUS_MULTIVAR_UNITS  which are at a more outer level? (same name/units for fcst and obs).

If a description of these and what they mean is needed in METplus, that documentation would need to be added, or maybe METplus refers to MET, where the documentation is found.

@davidalbo would be interested in learning how to add this functionality.

### Time Estimate ###
1-2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
June 8, 2023

### Funding Source ###
2700042

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
https://github.com/dtcenter/MET/issues/1283

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
