### ISSUE TITLE
New Use Case: PointStat AMDAR PBLH with python embedding

### ISSUE THREAD

**Issue by jason-english** [dtcenter/METplus#2198]
*Replace italics below with details for this issue.*

## Describe the New Use Case ##
Using python embedding, compute PBLH from AMDAR aircraft data using the "Theta-increase" method (Nielsen-Gammon et al., 2008, J. App. Met. Clim.), which creates an altitude ascending array for each flight, computes a potential temperature base value, and finds the first altitude that exceeds a specified increase in potential temperature. The geographic region(s)/airport(s) of interest is specified, and the lat/lon domain to determined by processing a static mask (which is created for each region/airport via gen_vx_mask). The airport(s), pt_delta (theta-increase), and sounding can all be specified in the configuration script.

### Use Case Name and Category ###
PointStat_fcstHRRR_obsAMDAR_PBLH
Category: model_applications/pbl

### Input Data ###
AMDAR hourly netcdf file: 221822000q.cdf (7.1 MB)
HRRR grib2 file: hrrr_pblh_2218208000012 (5.1 MB)

### Acceptance Testing ###
Use gen_vx_mask to create a circular static mask around the airport(s) of interest, and then point-stat with python embedding to generate .stat files of PBL Height. 

### Time Estimate ###
Approximately 3 months (including PBLH algorithm development)

### Sub-Issues ###
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
To be implemented as part of the June 2023 MET/METplus release.

### Funding Source ###
GSL Task II funds

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**
- [x] Select **privacy**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
