### ISSUE TITLE
Internal: Remove base environment from Docker Conda images

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#2249]
Scripts in internal/scripts/docker_env are used to create Docker images that contain Conda environments used for use case tests that require additional python packages. Many of the conda environments are created by copying (cloning) an existing environment (like metplus_base or py_embed_base) and adding packages. The original base environment still exists in the Docker image. Some of these conda environments, like metplotpy, take up a lot of space and cause the Docker image to be very large even though the base image is not used.

## Describe the Task ##
Add logic to the Dockerfiles in internal/scripts/docker_env to remove the conda environment used to create a new environment after the new one is created. Consider creating a GitHub Action workflow that can be triggered through the web UI to build and push these images so they can be run by other developers.

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
The logic to remove the unused Conda environments was added in c986e69f. I rebuilt a few images to test and discovered that the size of the images did not decrease as I expected, but actually increased very slightly (likely due to the update/upgrade commands for the OS and conda that have grown since the last time they were built). This is looking at compressed image size on DockerHub, so it is possible that these changes will be useful to reduce the size of the final Docker container that is used to run the use case tests and may still alleviate disk space issues.

I am still rebuilding the Docker images and pushing them to DockerHub. This issue can be closed when that is completed.
