### ISSUE TITLE
Improve METplus test coverage

### ISSUE THREAD

**Issue by John-Sharples** [dtcenter/METplus#2253]
## Describe the Enhancement ##
Improve the test coverage of `utils/` and `metplus/` by expanding existing tests and adding new tests. 

### Time Estimate ###
TBD

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] Improve coverage in `metplus/wrappers/'
- [ ] Improve coverage in `metplus/utils/'

### Relevant Deadlines ###
None

### Funding Source ###
In kind contribution from the Bureau of Meteorology.

### Assignee ###
- [ ] @John-Sharples

### Labels ###
TBD

### Projects and Milestone ###
- [ ] **alert: NEED CYCLE ASSIGNMENT** 

## Define Related Issue(s) ##
Enhancement should have no impact on other components. Scope is limited to testing that utilises pytest. May have an impact on GitHub CI as tests will change, and dependancies required by CI may be impacted.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by John-Sharples** [comment]
@georgemccabe 
As mentioned this morning I started looking at `diff_utils` already (but won't do more now that I know it's actively being developed). My changes don't include your recent additions and bugfixes, but thought I'd share them anyway.

https://github.com/John-Sharples/METplus/blob/feature_2253_diff_util_test_bom/internal/tests/pytests/util/diff_util/test_diff_util_bom.py

As we seem to have taken different approaches, this might be a good opportunity for some quick feedback and to set any expectations around style and test design. Please let me know if you have any comments.

A couple of things to note:
- I note the preference to write temp files to `METPLUS_TEST_OUTPUT_BASE` rather than use  `/tmp`. Makes sense for tracking files and happy to adopt this approach.
- I have a preference to test each function individually, as well as the core funtionality of the module. Let me know if you think this is overkill.

Thanks
John

**Comment by georgemccabe** [comment]
@John-Sharples, these tests look good to me! It looks like the tests you have written and the tests I have written do not overlap too much so we can use both sets.  I haven't written tests for the NetCDF diff logic yet, so I'm glad you started with that. I was also planning on adding tests for the individual functions you have already covered.

We don't have strict style/design rules for these tests. I think the tests you have written are clear and easy to understand, which is one of the few requirements in my mind. I also typically focus on testing individual functions/components. The tests I have started for diff_util are based on specific examples from MET output files that weren't being handled properly.

Knowing what you are already implemented, I will try to wrap up my changes today or tomorrow so you can merge my changes into your branch.

> I note the preference to write temp files to METPLUS_TEST_OUTPUT_BASE rather than use /tmp. Makes sense for tracking files and happy to adopt this approach.

Some METplus power users run on systems that discourage writing to /tmp, so we have moved away from making this the default. You can still configure METplus to write temporarily files to /tmp is that is desired.

Note that my changes have removed the logic that reads a shell script that contains environment variables to set before running the tests. Instead the user should set METPLUS_TEST_OUTPUT_BASE to a path where they have write access. That is the only environment variable that is still required to run the tests.

**Comment by georgemccabe** [comment]
I forgot to mention that we are preparing for the METplus 5.1.0 official release, which is currently scheduled for July 31. Only bugfixes should go into the develop branch at this time. The changes I am working on are fixing a bug in the diff logic, so I will merge them into develop before the release. As long as your changes include new tests and do not have any changes to the actual code base, I think they could be merged into develop before the release if they are ready. Otherwise we should hold off on merging any new changes into develop until after the release is created.

**Comment by John-Sharples** [comment]
Thanks George - I'll watch #2254 and merge into my branch once it's accepted. Then I'll get a PR up for you.

Noted that you're in the middle of preparing for a release. There's no rush on any of my changes, more than happy for them to wait until you've cleared the decks.

**Comment by georgemccabe** [comment]
@John-Sharples, I just merged my changes into the develop branch, so you can update your branch with those changes. I also updated the Contributor's Guide - Testing chapter with more info about the pytests.

**Comment by John-Sharples** [comment]
Thanks @georgemccabe 

I've updated my tests on top of your changes and raised a PR. 
https://github.com/dtcenter/METplus/pull/2256

Please let me know if there's anything further I need to add. Wasn't sure about Milestones and Projects etc.

Let me know if there is further work you'd like me to do on this. Otherwise in the coming weeks like start looking at the wrapper tests. Likely starting with `series_analysis` or `plot_data_plane`

**Comment by georgemccabe** [comment]
PR #2398 added logic to the GitHub Actions testing workflow to create an error annotation for a workflow run if the code coverage goes below 90%. This will not cause the workflow run to fail, but it will alert developers that this has fallen below the requirements. As of that PR the code coverage was up to 91%.
