### ISSUE TITLE
Bugfix: Prevent failure in LSR use case

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#2294]
In the NOAA telecon on 2023/08/07, we discovered that the Python Embedding script used in the short_range/Point2Grid_obsLSR_ObsOnly_PracticallyPerfect use case can fail if it encounters a row that has missing information.

> Time,F_Scale,Location,County,State,Lat,Lon,Comments
> ...
> **2011,UNK,2 WNW Port Cli 2023-07-28 1,:48:02,,0,0,**
> 2011,UNK,2 WNW Port Clinton,Ottawa,OH,41.52,-82.98,Trees and limbs downed. Pictures submitted via social media and time estimated from radar. (CLE)
> ...
> **0155,70,13,,,0,0,**
> 0155,70,13 N Edson,Sherman,KS,39.51,-101.57,Corrects previous tstm wnd gst report from 13 N Edson. Trained spotter reports estimated 70 mph wind gust with blowing dust reducing visibility down to near 0 at times. (GLD)

## Describe the Enhancement ##
Enhance the script to filter out rows that do not have data in required columns.

### Time Estimate ###
<1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
EVS v2

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
