### ISSUE TITLE
Documentation: Specify available tags on DockerHub

### ISSUE THREAD

**Issue by jfrost-mo** [dtcenter/METplus#2329]
## Describe the Enhancement ##
The docker build of METplus does not use the latest tag. (https://github.com/dtcenter/METplus/discussions/2305#discussioncomment-6703333). This means that the default docker pull that one does to try out the container doesn't work, and instead a specific version needs to be pulled, like `5.1-latest`. This is all well and good, but it doesn't appear to be documented anywhere, such as on the [Docker Hub README](https://hub.docker.com/r/dtcenter/metplus), or in the [installation documentation](https://metplus.readthedocs.io/en/latest/Users_Guide/installation.html).

### Time Estimate ###
Approximately 0.5 days of work.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] Add note to docker hub readme
- [ ] Add note to installation documentation

### Relevant Deadlines ###
NONE.

### Funding Source ###
NONE.

### Assignee ###
- [ ] Select **engineer(s)** required
- [x] **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] This issue also applies to the MET docker container.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
@JohnHalleyGotway, do you have an opinion of where this information should be added to properly document the naming conventions?

**Comment by JohnHalleyGotway** [comment]
@georgemccabe my initial thought was to look at the [METplus 5.1 Existing Builds](https://dtcenter.org/community-code/metplus/metplus-5-1-existing-builds) page, but checking there, I see that we just link directly to the location on DockerHub.
<img width="383" alt="Screen Shot 2023-08-30 at 2 13 22 PM" src="https://github.com/dtcenter/METplus/assets/21087144/9b77a326-4d67-4218-a828-69392e00b447">

I'd recommend that we update the content in:
1. The [METplus in Docker](https://metplus.readthedocs.io/en/latest/Users_Guide/getting_started.html#metplus-in-docker) documentation section which is currently not accurate (`docker pull dtcenter/metplus:latest`).
2. Update the [METplus 5.1 Existing Builds](https://dtcenter.org/community-code/metplus/metplus-5-1-existing-builds) page to include version-specific commands, like `docker pull dtcenter/metplus:5.1-latest`.

Can you think of other places to update?

**Comment by georgemccabe** [comment]
@JohnHalleyGotway,

@jfrost-mo mentioned the DockerHub README in the issue body. I agree that it would be good to note this on the [dtcenter/metplus DockerHub page](https://hub.docker.com/r/dtcenter/metplus) because it is currently unclear. It looks like the README that is shown on DockerHub is synced with the README.md file at the top of the METplus repository. Do you think this information is appropriate for that README file? An alternative is to update the description of the DockerHub repo. The description is currently set to:

> Python scripting infrastructure for MET tools.

but we could change it to something like this:

> Python scripting infrastructure for MET tools. Use tags named vX.Y.Z (e.g. v5.1.0) for a specific version or vX.Y-latest (e.g. v5.1-latest) for the latest version of the X.Y release that includes any bugfixes.

**Comment by jfrost-mo** [comment]
My view is that the README should contain (or link to) everything needed to get METplus running. So that should probably include a link to the [Installation docs](https://metplus.readthedocs.io/en/latest/Users_Guide/installation.html), as users viewing the GitHub are (I think) likely to do their own install rather than just using a site installation.

Related, the docker stuff should probably be moved from the getting started to the installation section of the documentation, as it is very much installing.

**Comment by georgemccabe** [comment]
* I updated the description on the [METplus DockerHub page](https://hub.docker.com/r/dtcenter/metplus) to say:
  > Python scripting infrastructure for MET tools. Use tags named X.Y-latest or X.Y.Z. 

  The full text I suggested is not allowed because it is too long. I think the list of tags provide examples of valid tags, so that seems sufficient.

* I updated the 5.1 Existing Builds page and METplus in Docker section of the User's Guide as suggested above.


@jfrost-mo, the METplus README does link to the METplus User's Guide which contains the Installation chapter. I think that is sufficient to direct users to the right area.
Regarding the location of the METplus in Docker section, that section includes more information that just obtaining the container, such as obtaining sample data and running examples. I suggest that we include a link to that section from the Installation chapter so it is clear from that chapter that Docker can be used. What do you think?

**Comment by jfrost-mo** [comment]
That sounds sensible to me.
