### ISSUE TITLE
Add METplus configuration options to support MET options that can be set separately for each `obs.field` entry

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2357]
## Describe the Enhancement ##
This issue arose via the dtcenter/METplus#2356 discussion. @heu3becteh would like to define `topo_mask.flag = TRUE`, but only when the interpolation `method = GEOG_MATCH`. This cannot be supported directly, however one reasonable workaround is verifying the same field twice, the first with `topo_mask.flag = FALSE` and the second with `topo_mask.flag = TRUE`. No METplus configuration option exists to directly set `topo_mask.flag` separately for each variable. Instead, it needs to be set using [POINT_STAT_OBS_VAR<n>_OPTIONS](https://metplus.readthedocs.io/en/latest/Users_Guide/glossary.html#term-OBS_POINT_STAT_VAR-n-_OPTIONS).

This issue is to step back and survey the MET configuration options that `can be set separately for each "obs.field" entry`. The [topo_mask.flag](https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#topo-mask) entry is one specific example. Based on that survey, add new configuration options to set those directly rather than relying on the [POINT_STAT_OBS_VAR<n>_OPTIONS](https://metplus.readthedocs.io/en/latest/Users_Guide/glossary.html#term-OBS_POINT_STAT_VAR-n-_OPTIONS) to do so, which can be error prone and difficult to get correct. And while I list Point-Stat above, please include all MET tools in the survey of config options.

Note that the `alert: NEED MORE DEFINITION` label should remain on this issue until the very specific config options needed have been clearly defined.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required - DO NEED A SCIENTIST TO ADVISE ON CONFIG OPTIONS!

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Based on discussion dtcenter/METplus#2747, recommend that we also support setting `cnt_thresh` separately for each variable being evaluated.

Specifically, recommend adding:
- `FCST_VAR<n>_CAT_THRESH` and `OBS_VAR<n>_CAT_THRESH` ... to set `field.cat_thresh`
- `FCST_VAR<n>_CNT_THRESH` and `OBS_VAR<n>_CNT_THRESH` ... to set `field.cnt_thresh`

For backward compatibility, continue to support `FCST/OBS_VAR<n>_THRESH` entries and use their values to set the newly added `FCST/OBS_VAR<n>_CAT_THRESH` settings.

**Comment by JohnHalleyGotway** [comment]
As discussed by @JohnHalleyGotway and @georgemccabe for METplus Discussion #2849, some changes are needed in the EnsembleStat wrapper configuration options.

Specifically, `FCST/OBS_ENSEMBLE_STAT_VAR<n>_THRESH` set the `fcst.cat_thresh` and `obs.cat_thresh`, but ensemble_stat does NOT actually parse them. Recommend deprecating these options. If fully removing support of this from the code is unreasonable, just update the documentation to clarify.

Instead, `ENSEMBLE_STAT_PROB_CAT_THRESH` is parsed and used by ensemble_stat. Recommend adding support for `FCST/OBS_ENSEMBLE_STAT_PROB_CAT_THRESH` options.

**Comment by georgemccabe** [comment]
[This comment](https://github.com/dtcenter/METplus/discussions/2974#discussioncomment-13094481) in discussion #2974 notes the desire to add support for settings `nc_pairs_var_name` per obs field.
