### ISSUE TITLE
New use case: TCDiag Single Init Use Case

### ISSUE THREAD

**Issue by jvigh** [dtcenter/METplus#2359]
## Describe the New Feature ##

The goal of this use case is to provide a use case to NHC that illustrates an end-to-end workflow that runs the TCDiag suite for a single initialization and accomplishes the following steps:
- [x] Call the TC-Diag tool to generate diagnostics output for one initialization
- [ ] Load the resulting data into TC-Pairs to generate TCMPR output
- [x] Call the TCMPR plotter on the TCMPR output 
  - [x] Call METdataio reformatter to reformat output from TCDiag tool
  - [x] Time series of diagnostic values for forecasts (a real-time type of plot for forecasters)
         (Similar to what CIRA is producing. Representing what is in the current diagnostic file.) 
  - [ ] Additional brainstorming: Another option could be short-term retrospectives (e.g., last 5 runs, or the storm history).
    - [ ] Recommend that when using this use case, decide whether this enhancement should be done as part of this use case or a new use case. (NOTE: Probably would not be an end-to-end use case, but rather use existing data). 
- [x] Call the Skew-T diagram using the CIRA ASCII data        

NOTE: This is not the basic use case (e.g., TCDiag-only use case that is tool-specific). Rather, this is the elaborated use case that will go under the model applications under the TC and Extra TC section. 

NOTE: Jon Martinez is working on setting up a verification workflow with METplus that mimics the NHC verification workflow. 
So in the future, there may be a workflow to pattern after. This may require some separate meetings with Jon Martinez, Kathryn Newman, Kate, etc. 

### Use Case Name and Category ###
This use case will live in the TCDiag-Realtime repository. 

### Input Data ###
*List input data types and sources.*
*Provide a total input file size, keeping necessary data to a minimum.* 

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Goal: December (subject to v12.0.0 release schedule).

### Funding Source ###
TCDiag Project (2770043)

### Assignee ###
- [x] Engineer: **George McCabe** and **Minna Win-Gildenmeister**
- [x] Scientist: **Jonathan Vigh**

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose)
- [x] [MET](https://github.com/dtcenter/MET/issues/new/choose)
- [x] [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose)
      - [ ] https://github.com/dtcenter/METdataio/issues/240
- [x] [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose)
- [x] [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose)
- [x] [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose)
- [x] [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
     - [x] https://github.com/dtcenter/METplotpy/issues/342
     - [x] https://github.com/dtcenter/METplotpy/issues/383 

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Will not be completed in time for RC1 release, awaiting sample data to complete the use case.

**Comment by JohnHalleyGotway** [comment]
@jvigh can you please take a look at this issue and update status. Can it be completed prior to the METplus-6.1.0-beta2 development release scheduled for March 26, 2025?

**Comment by jvigh** [comment]
Hi @JohnHalleyGotway - March 26 won't be possible, as I'm working to close out the current SWPC-IDIQ project. That is soaking up my extra/weekend time. Would it work to get this in for the beta3 cycle? What would the deadline be for that?

**Comment by michelleharrold** [comment]
@jvigh -- is this work something that will proceed, or should this issue be closed or reassigned?

**Comment by jvigh** [comment]
@michelleharrold - I still plan to do this, but probably won't have time to work on it until July.

**Comment by michelleharrold** [comment]
@jvigh - I wanted to double check on this given the METplus release timelines. Is this still work you plan on finishing? Thanks!

**Comment by jvigh** [comment]
Hi Michelle - thanks for checking in. I am still planning on finishing this use case, but the disruption this year due to my house repairs were a major factor this summer. Those have largely wrapped up and we will soon start benefiting from the benefit of being able to stay in one spot and not having to move every few weeks or months. But I'm catching up on all of my projects simultaneously and that's going to keep me busy through December. 

I anticipate having time to work on this use case in January. It'll hopefully just be 10 hours of work.

**Comment by georgemccabe** [comment]
@jvigh , could you provide an update?

**Comment by jvigh** [comment]
@georgemccabe, I've been swamped trying to catch my current projects up to speed (and still trying to get my insurance claim to a point where it can be finally closed). The most pressing task is getting some real-time aircraft recon capabilities up and running for NHC for the coming hurricane season. I also have a chunk of work I need to do for my NASA project so that the Climate & Environmental Hazards Explorer can be released. 

This is still on my radar, however.
