### ISSUE TITLE
New Use Case: TCDiag Seasonal Analysis Use Case 

### ISSUE THREAD

**Issue by jvigh** [dtcenter/METplus#2360]
## Describe the New Use Case ##

The goal of this use case is to provide a use case for EMC that illustrates an end-to-end workflow that analyzes pre-existing real-time diagnostic runs for an an entire season accomplishes the following steps:
- [ ] Run TCPairs to generated matched pair output for a season's worth of diagnostics output
- [ ] Stratify the diagnostic values by intensity
- [ ] Stratify the intensity performance conditioned by errors (e.g., track) or by a thresholded diagnostic value (e.g., low vertical shear)
- [ ] Generate summary plots for a retrospective evaluation of model performance:
  - [ ] spatial plot of the stratified errors
  - [ ] display the distributions of diagnostics by storm, by season, by model
  - [ ] performance diagram (stratifying by diagnostic value of shear low/med/high or for different models)
  - [ ] scatter diagram (?) 

NOTE: This is an elaborated use case that will be housed in the [TCDiag-Realtime repo](https://github.com/NCAR/TCDiag-Realtime).

### Use Case Name and Category ###
This use case will live in the TCDiag-Realtime repository. 

### Input Data ###
*List input data types and sources.*
*Provide a total input file size, keeping necessary data to a minimum.* 

### Acceptance Testing ###
*Describe tests required for new functionality.*
*As use case develops, provide a run time here*

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Goal: Early December (subject to v12.0.0 release schedule).

### Funding Source ###
TCDiag project (2770043)

### Assignee ###
- [x] Engineer: **George McCabe** and **Minna Win-Gildenmeister**
- [x] Scientist: **Jonathan Vigh**

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose)
- [x] [MET](https://github.com/dtcenter/MET/issues/new/choose)
- [x] [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose)
- [ ] [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose)
- [ ] [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose)
- [ ] [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose)
- [x] [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
  - [ ] dtcenter/METplotpy#383
  - [ ] dtcenter/METplotpy#342 

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
