### ISSUE TITLE
New Use Cases: RRFS reformatting, aggregating, and plotting use case

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplus#2406]
## Describe the New Use Case ##
Create the UseCase under TBD to demonstrate how to reformat RRFS ECNT linetype data via METdataio, perform aggregation via METcalcpy, and generate a line plot via METplotpy.

### Use Case Name and Category ###
TBD

### Input Data ###
*List input data types and sources.*  RRFS data
*Provide a total input file size, keeping necessary data to a minimum.* 

### Acceptance Testing ###
*Describe tests required for new functionality.*
*As use case develops, provide a run time here*

### Time Estimate ###
1-3 days for METdataio Reformatting section of UserScript and config files
1-3 days for METcalcpy Aggregation
1 day for METplotpy section of UserScript
1-2 days for documentation

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] METdataio Reformatting section of UserScript and config files
- [ ] METcalcpy Aggregation
- [ ] METplotpy section of UserScript
- [ ] Use case documentation

### Relevant Deadlines ###
Before beta3 release

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)**  Minna Win
- [ ] Select **scientist(s)** Vanderlei Vargas
### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [x] Delete your fork or branch.
- [x] Close this issue.
