### ISSUE TITLE
Enhancement: MvMode config format changes

### ISSUE THREAD

**Issue by davidalbo** [dtcenter/METplus#2429]
## Describe the Enhancement ##
Based on this issue,  https://github.com/dtcenter/MET/issues/2706, for Multivariate Mode, took out the `intensity_flag` parameter and added two new integer array parameters in it's place:  
```
multivar_intensity_compare_fcst = [ ];
multivar_intensity_compare_obs = [ ];
```

so METplus environment variables will need some tweaking.  Everything else is the same.

Example with 3 input forecasts and obs.
Previous:
`intensity_flag=[FALSE, FALSE, FALSE]`

New:
```
multivar_intensity_compare_fcst = [ ];
multivar_intensity_compare_obs = [ ];
```

Previous:
`intensity_flag=[FALSE, TRUE, TRUE]`

New:
```
multivar_intensity_compare_fcst = [2, 3 ];
multivar_intensity_compare_obs = [2, 3];
```

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Hi @davidalbo, thank you for creating this issue. This is more of an enhancement than a new use case, so I modified the template to use the enhancement issue sections and checklist. The sections you had questions about are not found in the enhancement template, so you don't need to worry about them.

**Comment by hertneky** [comment]
@davidalbo Just noting that with these changes, the [use-case](https://metplus.readthedocs.io/en/latest/generated/model_applications/short_range/MODEMultivar_fcstHRRR_obsMRMS_HRRRanl.html#sphx-glr-generated-model-applications-short-range-modemultivar-fcsthrrr-obsmrms-hrrranl-py) would also need to be updated, which would be a minor change.
