### ISSUE TITLE
Document the recommend used of ISMN data in the Verification Datasets Guide

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2448]
## Describe the Task ##
Pull request https://github.com/dtcenter/MET/pull/2758 for issue https://github.com/dtcenter/MET/issues/2701 adds support to ascii2nc for handling the -format ismn option for reading soil moisture data (and other variable types too) for the [ISMN Network](https://ismn.bafg.de/en/). In addition, issue dtcenter/METplus#2447 updates the ASCII2NC wrapper to handle this new format.

This issue is to update the METplus Verification Datasets Guide (in `docs/Verification_Datasets/datasets`) to add a description of the how [ISMN](https://ismn.bafg.de/en/) soil moisture data can be used in verification. Note that this does not need to be very long, and does not need to repeat what's already listed on the ISMN site. Instead, we just want to briefly describe the data source and why/how its useful for verification.

### Time Estimate ###
4 hours?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
7750034 (UAlbany-NCAR METplus JTTI)

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required - not needed
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
@JohnHalleyGotway do you feel this required for the 12.0.0 release because there's an ISMN support in ASCII2NC?

**Comment by DanielAdriaansen** [comment]
@anewman89 will look at this template:
https://github.com/dtcenter/METplus/blob/develop/docs/Verification_Datasets/datasets/template.rst

And use existing docs here:
https://metplus.readthedocs.io/en/develop/Verification_Datasets/index.html

To provide text to @DanielAdriaansen who will commit it and issue a PR and test the documentation building, and get this merged in.

**Comment by DanielAdriaansen** [comment]
Complete this at the same time as #2533

**Comment by DanielAdriaansen** [comment]
The work for this was added to `feature_2533_ISMN_use_case` in 3c47f3d, 12caf88, and c2f5e4a, and will be part of the pull request for #2533

**Comment by DanielAdriaansen** [comment]
The content I added came from this Google Doc: https://docs.google.com/document/d/1u9dDn-7Q0Nqm1LKkVRRFKvjex6opoM3A/edit, written by @anewman89

**Comment by DanielAdriaansen** [comment]
Closed by #3051
