### ISSUE TITLE
New Use Case: International Soil Moisture Network (ISMN)

### ISSUE THREAD

**Issue by anewman89** [dtcenter/METplus#2533]
## Describe the Enhancement ##
The capability to read in International Soil Moisture Network [(ISMN)](https://ismn.bafg.de/en/) formatted ASCII files was recently implemented into the [MET ASCII2NC tool](https://github.com/dtcenter/MET/issues/2701).

We need to develop a use case that can demonstrate the use of the ISMN data ingest in ASCII2NC through an example model forecast verification.

We could develop a use case that reads soil temperature and moisture from ISMN data and verifies NOAA UFS output from sample GFS data, specifically the HR3 data available on NCAR HPC which is a prototype configuration for GFSv17, using the MET pointstat tool. It could be good to include quick-look plotting capabilities of the pointstat matched pair output as well, either spatially or as a scatter plot of model versus obs, or model error versus model value.

### Use Case Name and Category ###
Model soil moisture and temperature verification using ISMN data
This should be in the Land-surface category

### Input Data ###
UFS GFS prototype model data focusing on soil moisture and temperature output
ISMN data focused on CONUS

### Acceptance Testing ###
Verify conversion of ISMN data using ASCII2NC
Verify output of pointstat for example cases for soil moisture and temperature verification

### Time Estimate ###
2-3 days

### Sub-Issues ###
- [ ] Collect observations and model example data
- [ ] Develop use case scripts
- [ ] Develop description of use case
- [ ] See associated issues and ISMN data documentation need (below)

### Relevant Deadlines ###
05/31/2024

### Funding Source ###
7750034 UAlbany

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Along with this use case, there is a related documentation issue for ISMN data, METplus #2448 

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by anewman89** [comment]
@DanielAdriaansen I started this issue for the ISMN use case per our discussion on 04/01/2024. I believe we will be adding someone, likely Bri, to take the lead here, but I think it'd be good to have you in a support role for help.

**Comment by DanielAdriaansen** [comment]
Choose 0hr forecast and plot fcst/analysis vs. obs scatter plot.

**Comment by JohnHalleyGotway** [comment]
@DanielAdriaansen when working with this data, ascii2nc can read multiple input files on the command line. However, with ISMN data there will be tens, hundreds, or thousands of input files. ascii2nc currently does NOT accept an input ascii file list. Please consider whether or not it should be enhanced to do so for this data. If so, please let me know and we can write up that issue.

**Comment by anewman89** [comment]
@DanielAdriaansen Lets use one of the summer 2020 GFS prototype initializations, say 2020 07 28.  We'll focus on CONUS,  top level soil moisture and temperature, which we can make a couple scatter plots from.

**Comment by DanielAdriaansen** [comment]
Related to #2447

**Comment by DanielAdriaansen** [comment]
@anewman89 I downloaded ISMN data for 20200805 in the "Header+Values" format and processed 3536 observations. All of them appear to have the valid time of `20200805_000000` coming from `ASCII2NC`. Is this expected? Or should we expect that there is some variation in the actual timestamp of the observations for a single day? I am not familiar enough with the network characteristics yet to know for sure. I spot checked ARM, iRON, CW3E, and USCRN and all the files ending with `.stm` had a time of exactly `00:00`, so I am leaning toward this is expected but curious what you thought.

**Comment by anewman89** [comment]
@DanielAdriaansen Thanks for the update.  I would have expected some variation in the time stamp.  I think what is happening is if you selected 20200805 as your start and end date on the ISMN data download, it will only give you 00 UTC data for 5 August 2020.  If you select 06 August 2020 as your end date, you'll get hourly data if a particular site has hourly or finer resolution.  

So this is fine as its just an example of capabilities.

**Comment by DanielAdriaansen** [comment]
@anewman89 much better! Processed 87,107 observations now and found 11,363 matched pairs using +/- 12h around 12 UTC (24h window), which seems much better to me. Thanks for the help here! Next step is what we want to plot or show with the output. Looking at the meeting notes I see:
"MAE/BIAS maybe
F-O, plot of differences"

But let's discuss more specifics about what the viz should look like- maybe choose something in the METplotpy plot types? https://metplus.readthedocs.io/projects/metplotpy/en/latest/Users_Guide/index.html. I'm probably not the best here for determining what someone would want to look at for Vx in this case.

**Comment by anewman89** [comment]
@DanielAdriaansen Could METplotpy make a spatial plot of bias at the station points?  I don't see that in the user's guide.  Or some other MET plotting capability?  For METplotpy, could we make a box plot of the matched pair F-O values? We could also possibly make a 2D histogram of F-O versus O (or F).

**Comment by DanielAdriaansen** [comment]
> Could METplotpy make a spatial plot of bias at the station points?

I don't think it can. When you say spatial plot of bias at the station points, do you envision a colored dot (red-blu colorscale) indicating the magnitude (+/-) of the bias at each station? I can include this fairly easily to round out the use case, and I'll start on that now but please confirm. Thanks.

**Comment by DanielAdriaansen** [comment]
@anewman89 question about different networks and station names in the ISMN data. Right now, for testing, I am doing this for the use case:
`val="SNOTEL,iRON,USCRN";}`

What this does is takes all SNOTEL, iRON, and USCRN sites and treats them as a single type of observation called `ISMN` for PointStat.

I am not sure how `ASCII2NC` is determined the observation "station ID" (OBS_SID), but they look like this:
```
Beaver_Dams
Batesville_8_WNW
Bristlecone_Trail
```

Is there any possibility that names like this could be found in two types of networks in ISMN? In other words, Beaver_Dams might be in `SNOTEL` and also `USCRN`?

**Comment by anewman89** [comment]
@DanielAdriaansen confirming your plot design. 

Regarding station names. Good question, I would expect it to be unlikely, but I don't actually know how many or if any network sites are co-located and use the exact same station name, or if a station is pulled into two networks...

**Comment by DanielAdriaansen** [comment]
@DanielAdriaansen be sure to include documentation updates to remove two optional STAT_ANALYSIS conf setttings from the "required" section of the documentation, and consider where to add instructions in the contributor's guide for adding a new use case concerning setting `run:false` in the JSON file before merging a PR or after merging, or somewhere to remind the user.

**Comment by DanielAdriaansen** [comment]
@anewman89 here's a sample graphic for `SOILW` 0-0.1m bias (range of +/- 1%). This is using `SNOTEL`, `USCRN`, and `iRON` only at this time.

![Image](https://github.com/user-attachments/assets/65ea840e-85a5-455a-9c37-e572ab1317a3)

**Comment by anewman89** [comment]
@DanielAdriaansen Plot looks good! However, I'm not sure of the units range of 1%. Is that the full color bar range? To me it looks like -100 to 100 as the ratio of -1 to 1. We could probably cut that down to +/- 20 and just let the few outliers saturate so we can see variability across more of CONUS.

**Comment by DanielAdriaansen** [comment]
Here's the histogram of `ME` values from MET.

Note here this is a _single_ forecast valid time. I would imagine bias could be much larger than +/- 1% on average if a user had many, many forecasts over many seasons, but I do think the range of data in this case is very much largely between +/- 1%.

![Image](https://github.com/user-attachments/assets/77377f9d-a0a4-4807-8afb-28b6ca985be5)

**Comment by anewman89** [comment]
Thanks for the histogram @DanielAdriaansen  Do you have the ability to plot a histogram of the F and O values to double check those?

**Comment by DanielAdriaansen** [comment]
Ah yes. I read units as `%` (from `wgrib2` output of the FCST file), and falsely assumed 0-100. In fact, units are not `%` and the units in the `MPR` files say `fraction`. Here is a histogram of F and O **multiplied by 100**

![Image](https://github.com/user-attachments/assets/13d76777-2143-48d8-a26d-e1258eb1089e)

How would you like the bias to appear? As a percent? Or as a fractional value between +/- 1.0?

**Comment by anewman89** [comment]
Thanks @DanielAdriaansen Soil moisture comes out from the UFS and these obs as a volumetric amount, cubic meters per cubic meter, so it can be percent or a fraction. To me the fraction makes more sense, so we could keep the plot in the -1/1 range, but can we limit it to about +/- 0.1?  Thanks!

**Comment by DanielAdriaansen** [comment]
`SOILW`:
![Image](https://github.com/user-attachments/assets/0244b805-46dc-417f-8e53-7c531b74cfbd)

`TSOIL`:
![Image](https://github.com/user-attachments/assets/5bdfd189-2b95-4b6f-be1d-fa0db59e0b33)

Only for sites in `SNOTEL`, `ARM`, `USCRN`, `SCAN`.

Do you have any other recommendations for the graphics, additional networks to demonstrate (we can't do all currently do to the large number of different files), or additional levels (I am only doing `TSOIL` and `SOILW` for `0-0.1` level currently)?

**Comment by anewman89** [comment]
@DanielAdriaansen Great, thanks for this!  I like your suggestion of a 2D histogram of F-O versus F as one other plot.  Could you add a label to these spatial plots of F-O somewhere?

**Comment by DanielAdriaansen** [comment]
> I like your suggestion of a 2D histogram of F-O versus F as one other plot

I don't remember suggesting this, but it's doable. This would be "ME" on one axis and the "FCST" value on another? Any preferences on:
1. Which is on which axis?
2. Colors of dots (shade by ME value? shade by...FCST value? Other?)

And yes- on the maps I'll add begin/end valid times, network names, variable name, F-O, and level as well.

**Comment by anewman89** [comment]
Whoops, it was a comment I made. :)  Glad it's doable.  Let's do: 1) ME (Y-axis) versus F (X-axis) and then 2) shade by frequency of occurrence so its a 2D density heatmap.

**Comment by DanielAdriaansen** [comment]
Some more thoughts for you to consider.

Right now, my "WINDOW" around the forecast valid time for including ISMN obs is +/- 12h (so a 24h window around a single valid time). Is this what we want? I set it pretty wide to capture obs to get going, but wondering if this should be a little tigher.

What "time" do you want the 2D histogram to represent? All available times plotted on a single plot? So if a user had 30 days of forecasts valid every 6h (30 x 4) plus 12 lead times (30 x 4 x 12) this would be 1440 possible "forecasts" plotted on top of each other at the end of the METplus run. I can add some additional complexity to call the plotting script once per valid time, lead time, etc. if there is a preference to stratify this for each 2D histogram.

The map plots are already aggregating across all times so there is no option to stratify the overall bias in those plots currently. But maybe there should be? I'll need some additional help to configure `stat-analysis` properly to do this, maybe from @JohnHalleyGotway or someone else, depending on what you wish. Or, we could also remove the call from `stat-analysis` completely, and just read the MPR data and do the stratification you desire in Python for the plotting of the map.

This all can get complex real quick, and it's prone to not capturing all possible scenarios a user would have with their forecast data (leads, inits, etc.) especially since I am only using one model file as the bare minimum example for the use case. Let me know if you want to get together and scope this out a bit more clearly.

**Comment by anewman89** [comment]
Lots of good thoughts here. We could probably tighten the window down a bit, say +/- 3-6 hours for the demonstration if there are still sufficient obs available.

For the 2D plot, let's do the same as the spatial plots, so aggregated ME for each station as a 2D histogram for now.  I could see aggregated by lead time, time of year, etc being worthwhile, but perhaps just a comment in the code to note where this would need to happen is fine for now.

**Comment by DanielAdriaansen** [comment]
> Lots of good thoughts here. We could probably tighten the window down a bit, say +/- 3-6 hours for the demonstration if there are still sufficient obs available.

Got it, thanks!

> For the 2D plot, let's do the same as the spatial plots, so aggregated ME for each station as a 2D histogram for now. I could see aggregated by lead time, time of year, etc being worthwhile, but perhaps just a comment in the code to note where this would need to happen is fine for now.

Can you clarify what you mean by "aggregated ME for each station" for the 2D plot? If you want "F-O" on one axis (ME/bias), there's no way to get the corresponding "F" part of that in the stat-analysis output file (i.e. stat-analysis only puts out ME, not the summation components of ME). So the only way I can create this is by computing F-O for each matched pair using the point stat MPR files, and then I can access the F part of it as well. This is just literally a scattershot though of all pairs on top of each other, and no aggregation _per se_ is occurring other than plotting on top of each other. Does this jive with what you were thinking?

**Comment by anewman89** [comment]
Thanks for the clarification with the stat-analysis output Dan. I'm open for a quick call right now.  I can send a message to you.

**Comment by DanielAdriaansen** [comment]
OK here are the rough draft for:
`TSOIL`:
<img width="1797" height="1226" alt="Image" src="https://github.com/user-attachments/assets/70425b32-d847-4334-ba7a-c62ae084c0e5" />

`SOILW`:
<img width="1797" height="1219" alt="Image" src="https://github.com/user-attachments/assets/0038a397-bf36-4159-89e6-1fa64a60fc49" />

I will update annotations, font sizes, and add a colorbar. But you'll probably have suggestions on:
1. The range of shading for the cells in the density plot. Right now these are un-normalized, so they are raw counts in each F/F-O bin. We could normalize them to be 0-1, but maybe you have other ideas or preferences on the range of colors based on the ranges on F/F-O.
2. The ranges for the y-axis and x-axis for these plots. I just used the same as for the bias (ME) map plots, but we may want to tinker for these 2D histograms to get them looking a certain way.

Let me know what you think.

**Comment by anewman89** [comment]
Thanks for these @DanielAdriaansen !  Good suggestion to normalize, could we run the color bar 0-max frequency?  For the ranges, it makes sense to keep the y-axis the same as the spatial plots.  For x ranges, we probably should just use 0-1 for soil moisture.  Could we use some range of temp like [min-2, max+2]?  That way the SOILT plot is framed nicely.

**Comment by DanielAdriaansen** [comment]
Next versions
`TSOIL`:
<img width="1745" height="1282" alt="Image" src="https://github.com/user-attachments/assets/d8a8b5fc-190a-4cc8-99fc-56246b9b5531" />

`SOILW`:
<img width="1761" height="1291" alt="Image" src="https://github.com/user-attachments/assets/8fb83c5a-b6f1-4244-92dc-77838425ef80" />

**Comment by anewman89** [comment]
I like this color bar and the axes ranges, thanks!

**Comment by DanielAdriaansen** [comment]
Closed by #3051
