### ISSUE TITLE
New Use Case: Vegetation-Atmosphere Coupling (VAC) index as a land-atmosphere coupling diagnostic

### ISSUE THREAD

**Issue by anewman89** [dtcenter/METplus#2535]
## Describe the New Use Case ##
The Vegetation-Atmosphere Coupling (VAC) index as described in [Zscheischler et al. (2015)](https://agupubs.onlinelibrary.wiley.com/doi/10.1002/2015GL066563) and summarized by Paul Dirmeyer [here](https://github.com/pdirmeyer/l-a-cheat-sheets/blob/main/Coupling_metrics_V30_VAC.pdf).

The original VAC index is computed using anomalies of fraction of absorbed photosynthetically active radiation (FPAR) or evapotranspiration (ET), and 2 m temperature with the long-term mean seasonal cycle removed.  FPAR and ET were from satellite (FPAR) or model/model-obs fusion products (ET).  For this use case, we will focus on ET as FPAR is often prescribed in current and likely next generation land models for forecast applications.

The long-term mean data should be required to be user provided, but for the use case, we'll have to compute those ourselves.  For observations, we can use ERA5 for 2 m temperature, and possibly [FLUXCOM](http://www.fluxcom.org/) or [GLEAM](https://www.gleam.eu/) for 'observed' ET.

For the models, we will likely not have access to long-term datasets except for long-term climate simulation datasets.  For operational forecasts, there are often only short test periods to draw from.  The user will likely need to be tasked to provide what they consider an appropriate model long-term seasonal mean value to compute anomalies from.

Further, the original VAC index estimates percentile anomalies empirically from the long-term anomaly time series.  The user may need to provide the observed and model percentile values (or fitted Gaussian distribution parameters?).  An alternative would be to use just the anomalies in anomaly units, not percentiles, but that often has more noise than percentile based anomalies.

Finally, the visualization of this metric is often done in a 2-d scatter plot, with varying levels of color coding depending on user preference.  We will likely need to coordinate with forthcoming MetPlotPy enhancements across TBD issues.

### Use Case Name and Category ###
Vegetation-Atmosphere Coupling (VAC) index as a land-atmosphere coupling diagnostic

### Input Data ###
Observed ET and 2 m temperature for evaluation period
Modeled ET and 2 m temperature for evaluation period
User provided long-term seasonal means for both obs and model
User provided long-term percentiles for both obs and model

### Acceptance Testing ###
*Describe tests required for new functionality.*
*As use case develops, provide a run time here*

### Time Estimate ###
3-4 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Approximately 6/30/2024

### Funding Source ###
2785031 (Dyn Veg Drought)

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
There will be coordination with MetPlotPy and possibly MetCalcPy for VAC plotting and computation respectively.

## New Use Case Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept your changes. Merge branch into **develop**.
- [ ] Create a second pull request to merge **develop** into **develop-ref**, following the same steps for the first pull request.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Note that we may want to also add logic to METcalcpy to handle longterm climatology-based statistics.
Would need a separate METcalcpy issue to do so. This was discussed with @anewman89 on April 5, 2024 at a Land Project meeting.
