### ISSUE TITLE
Enhancement: Enhance GHA documentation workflow with a custom action

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#2543]
## Describe the Enhancement ##
Enhance the GitHub Actions documentation workflow with a single custom action to reduce duplication and ensure consistency.

Items to include:
- [ ] In .readthedocs.yaml under `sphinx`, add `fail_on_warning: true` 
- [ ] `python-version: '3.10'` should be listed (documentation.yml) across all repos, but is currently `3.8` in [METdataio](https://github.com/dtcenter/METdataio/blob/develop/.github/workflows/documentation.yml) and [METviewer](https://github.com/dtcenter/METviewer/blob/develop/.github/workflows/documentation.yml).
- [ ] Make the `workflow_dispatch` [trigger](https://github.com/dtcenter/MET/blob/8ee59fce756c1878b6825952a15461ad084cc1c5/.github/workflows/documentation.yml#L14) available across all repos in the main and develop branches.  This will allow manual runs of the documentation workflow for a desired branch or tag.
- [ ] Use one definition of requirements for documentation.  For example, currently,  documentation.yml specifies any additional packages needed to build the documentation in GitHub Actions, but the docs/requirements.txt file specifics any additional packages needed to build the documentation in Read The Docs.  We could bring those two together with a script called in documentation.yml using what is specified in docs/requirements.txt.
- [ ] Accomplish the work listed in these issues for `make clean html`
       - [ ] [METplus #2034](https://github.com/dtcenter/METplus/issues/2034)
       - [ ] [MET #2436](https://github.com/dtcenter/MET/issues/2436)
       - [ ] [METcalcpy #273](https://github.com/dtcenter/METcalcpy/issues/273)
       - [ ] [METdataio #179](https://github.com/dtcenter/METdataio/issues/179)
       - [ ] [METplotpy #316](https://github.com/dtcenter/METplotpy/issues/316)
       - [ ] [METviewer #454](https://github.com/dtcenter/METviewer/issues/454)
       - [ ] [METexpress #111](https://github.com/dtcenter/METexpress/issues/111)
       - [ ] [METplus-Training #57](https://github.com/dtcenter/METplus-Training/issues/57) 

See the [metplus-action-release-checksum](https://github.com/dtcenter/metplus-action-release-checksum) and the [call to it](https://github.com/dtcenter/METplus/blob/26deaa90fd5b5a63eb696d9403c5c631fc7fa7b9/.github/workflows/release-checksum.yml#L12) as an example.
 
It looks like a [metplus-action-build-documentation](https://github.com/dtcenter/metplus-action-build-documentation) already exists but we don’t believe any of the METplus repos are actually using it.  Check in with @georgemccabe about it, however, it looks like only @JohnHalleyGotway has made any [commits](https://github.com/dtcenter/metplus-action-build-documentation/commits/main/).

### Time Estimate ###
1-3 days of work

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] See description for related issues.

### Relevant Deadlines ###
None

### Funding Source ###
TBD

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
