### ISSUE TITLE
Update Truth: For dtcenter/MET#2921

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2620]
## Describe Expected Changes ##

PR dtcenter/MET#2921 for issue dtcenter/MET#2841 modifies the definition of the range/azimuth grids used by the TC-RMW and TC-Diag tools. It makes the following changes:
- Re-defines azimuths from being defined counterclockwise from due north to being define clockwise from due east.
- Corrects the logic for deriving radial and tangential winds.

This will cause all TC-RMW and TC-Diag outputs based on the range/azimuth grid definitions to be modified. Specifically, we should see a phase shift in the data (i.e. shifting left by 25% due to the north to east change) as well as a reversal of values along the X-axis due to changing from counterclockwise to clockwise.

- [x] Link to relevant issue(s): dtcenter/MET#2921
- [x] Link to relevant pull request(s): dtcenter/MET#2841

### Title ###
- [x] Define the **Title** of this issue as **Update Truth: For dtcenter/{REPO}#{PR_NUMBER}** to indicate the repository and pull request that warranted this issue.

### Assignee ###

*Assign this issue to the author of the pull request that warranted this issue. Optionally assign anyone else who should review the differences in the output.*

- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version if updating truth data for the `develop` branch **OR** select next **METplus-Wrappers-X.Y.Z bugfix** version if updating truth data for a `main_vX.Y` branch.
- [x] If updating truth data for the `develop` branch, select the **METplus-Wrappers-X.Y.Z Development** project **OR** if updating truth for a `main_vX.Y` branch, select the **Coordinated METplus-X.Y Support** project

## Update Truth Checklist ###
- [x] Review the GitHub Actions workflow that was triggered by the PR merge
  - If no differences were found, note this in a comment.
  - If all of the differences are expected, note this in a comment.
    Include any details of how the review was performed.
  - If unexpected differences are found, the following instructions can
    help uncover potential explanations. If none of these apply and the
    source of the differences cannot be determined, contact the
    METplus wrappers lead engineer (@georgemccabe) for assistance.
    - Search for other open issues that have the label `type: update truth`
      applied by clicking on the label on this issue. Coordinate with the
      author of these issues to ensure all diffs are properly reviewed.
    - Check if any additional GitHub Actions testing workflows have been
      triggered since the workflow that corresponds to this issue was run.
      Review the latest run to ensure that there are no diffs that are
      unrelated to this issue.
    - If the incorrect differences are caused by the changes from the
      issue that warranted this issue, consider reverting the PR and
      re-opening the issue.
  - Iterate until one of the above conditions apply.
- [ ] Approve the update of the truth data
  - Contact the METplus wrappers lead engineer (@georgemccabe) or
    backup lead (@jprestop) to let them know that the truth data can
    be updated.
- [ ] Update the truth data.
      This should be handled by a METplus wrappers engineer.
      See the [instructions to update the truth data](https://metplus.readthedocs.io/en/develop/Contributors_Guide/continuous_integration.html#update-truth-data-update-truth-yml) for more info.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
This review is based on this [GHA testing workflow run](https://github.com/dtcenter/METplus/actions/runs/9655034405) that was triggered when PR dtcenter/MET#2921 was merged into develop.

I note the following:
- 3 of the 56 use case groups failed.
- Across those 3 use case groups, differences were flagged in a total of 4 NetCDF output files only:
```
Archive:  diff-use_cases_met_tool_wrapper_0-29_59-64.zip
  inflating: met_tool_wrapper/TCDiag/tc_diag/2023/sal032023_gfso_doper_2023062012_cyl_grid_parent_output.nc  
  inflating: met_tool_wrapper/TCDiag/tc_diag/2023/sal032023_gfso_doper_2023062012_cyl_grid_parent_truth.nc  
  inflating: met_tool_wrapper/TCDiag/tc_diag/2023/sal032023_gfso_doper_2023062012_diag_output.nc  
  inflating: met_tool_wrapper/TCDiag/tc_diag/2023/sal032023_gfso_doper_2023062012_diag_truth.nc  
Archive:  diff-use_cases_met_tool_wrapper_30-58.zip
  inflating: met_tool_wrapper/TCRMW/met_tool_wrapper/TCRMW/tc_rmw_aal142016_output.nc  
  inflating: met_tool_wrapper/TCRMW/met_tool_wrapper/TCRMW/tc_rmw_aal142016_truth.nc  
Archive:  diff-use_cases_tc_and_extra_tc_0-2.zip
  inflating: tc_and_extra_tc/TCRMW_fcstGFS_fcstOnly_gonzalo/model_applications/tc_and_extra_tc/TCRMW_gonzalo/tc_rmw_gonzal09l.2014101312_output.nc  
  inflating: tc_and_extra_tc/TCRMW_fcstGFS_fcstOnly_gonzalo/model_applications/tc_and_extra_tc/TCRMW_gonzalo/tc_rmw_gonzal09l.2014101312_truth.nc 
```
I used `ncview` to spot check the 4th file and see the differences are exactly as expected with the range/azimuth data shift to the right by 90 degrees (north to east) and then reversed (counterclockwise to clockwise):
![Screen Shot 2024-06-25 at 12 11 40 PM](https://github.com/dtcenter/METplus/assets/21087144/12c35bdb-b08e-4164-861a-bb90e1b8c1a0)

I also see the same pattern in the first diff file.

I'll also note that no differences were flagged in the TC-Diag `.dat` output file: `met_tool_wrapper/TCDiag/tc_diag/2023/sal032023_gfso_doper_2023062012_diag.dat`. This makes sense because the diagnostics are computed for each RANGE value and the modified azimuths should still produce the same average value for each range. However, the `850TANG`, `850VORT`, and `200DVRG` diagnostics are reported as bad data in the output... and those are based on the derivation radial and tangential wind derivations. We should eventually have a TC-Diag use case that actually computes those diagnostic values from the radial/tangential winds (@jvigh and @KathrynNewman).
```
850TANG (10M/S)   9999  9999  9999
850VORT (/S)      9999  9999  9999
200DVRG (/S)      9999  9999  9999
```
