### ISSUE TITLE
Enhancement: Support separate climatology datasets for both the forecast and observation inputs

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#2622]
dtcenter/MET#2924 describes changes that will be made to MET to support forecast climo_mean and climo_stdev.

## Describe the Enhancement ##
Enhance the METplus wrappers to accompany the MET changes. From Slack, @JohnHalleyGotway noted:

> For METplus, I imagine we’d just want to…
> * Add support for FCST_CLIMO_MEAN and OBS_CLIMO_MEAN… and use them to set “climo_mean” inside the MET “fcst” dictionary.
> * Add support for FCST_CLIMO_STDEV and OBS_CLIMO_STDEV… and use them to set “climo_stdev” inside the MET “obs” dictionary.
> * If the FCST/OBS_CLIMO_MEAN/STDEV entries are not set, but CLIMO_MEAN/STDEV are, just set:
>   * FCST_CLIMO_MEAN = OBS_CLIMO_MEAN = CLIMO_MEAN
>   * FCST_CLIMO_STDEV = OBS_CLIMO_STDEV = CLIMO_STDEV

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
6.0.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Note that dtcenter/MET#2924 is fixed through 2 pull requests (dtcenter/MET#2939 and dtcenter/MET#2942). So this work can be done. Note that when defining `climo_mean` and `climo_stdev` dictionaries in the `fcst` and `obs` dictionaries, be sure to define both the `field` and `file_name` arrays inside each.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe please see details in this MET [issue comment](https://github.com/dtcenter/MET/issues/2924#issuecomment-2313138332).
