### ISSUE TITLE
Enhancement: Update Python from 3.10.x to 3.12.0

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#2697]
## Describe the Task ##

In the [METplus User's Telecon on 20241209](https://docs.google.com/document/d/1HnUfQ1FQ2GtKwpxbpau7v80ED4XcH0qn_LAR2VtSiXQ/edit?tab=t.0), it was recommended by EMC that our team tries out a switch to 3.12 for METplus-6.1.0 and see how it goes and reports back.  Note that it is important to use specifically Python 3.12.0 (and not later versions) as 3.12.0 is all that is available on WCOSS2.  If we find there are problems, we can report back to NCO to see if they are willing to update their version.

Python needs to be updated from Python 3.10 to Python 3.12.x, consistent with the version on the NCEP/NCO WCOSS2 hosts.

Review the package versions in our requirements.txt files when making this update. Ensure that there are no problems with Python Embedding with MET.

A link to the Python versions and dates : https://devguide.python.org/versions/

### Time Estimate ###
Spend 2 hours for preliminary investigation for:

- METplus
- METplus Analysis Tools

### Sub-Issues ###
For the METplus Analysis Tools:
- [ ] Upgrade other modules (i.e. pandas, numpy, matplotlib, plotly, etc.) to Python 3.12-compatible versions and make necessary changes
- [x] test/verify for METcalcpy
- [x] test/verify for METplotpy 
- [x] test/verify for METdataio
- [x] update any relevant documentation for METplus Analysis Tools
- [x] update the requirements in the NCO and repository requirements.txt  (verify toml files indicate >=3.10.4 )
- [x] test/verify for affected METplus use cases

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
R2O account key

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
**This change needs to be made across all repositories**
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
@John-Sharples suggested to review the package versions in our requirements.txt files when making this update.

**Comment by bikegeek** [comment]
Testing for backwards compatibility in METdataio (Python 3.10) is not possible due to lack of backwards compatibility in pandas with pd.options.future.no_silent_downcasting:

Sept 24, 2024 Github Issue created in pandas:
https://github.com/pandas-dev/pandas/issues/59845

**Comment by bikegeek** [comment]
METdataio, METcalcpy, METplotpy have been updated to Python 3.12
