### ISSUE TITLE
Bugfix: Improve SeriesAnalysis field info generation with regards to time

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#2705]
This was discovered from discussion #2687.

SeriesAnalysis wrapper contains logic to determine which time values to substitute in field info. Previously, the use case that utilized this logic processed one dataset that contained a single file with multiple times and another dataset that contained multiple files each with 1 time. The logic was written to parse the timing information from the multiple files and use that to set the timing information in the field info to read the single file.

## Describe the Enhancement ##
The use case described in discussion #2687 processes 2 datasets that contain multiple times, so parsing the timing information from the other dataset filenames is not sufficient. Currently the field information for the 12 hour and 24 hour forecast leads are identical, which is incorrect. This is arguably a bug and not an enhancement because it doesn't work properly, but we had not encountered a use case that needed this capability in the past. Development is typically driven by existing/desired use cases.

Update the logic to use the time_info dictionary content from the `self.c_dict['ALL_FILES']` list that is used to gather the list of input files to process. The relevant function is [get_formatted_fields](https://github.com/dtcenter/METplus/blob/develop/metplus/wrappers/series_analysis_wrapper.py#L1038) and the helper function it calls.

### Time Estimate ###
1-2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
