### ISSUE TITLE
Update Truth: dtcenter/MET#2988

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2719]
## Describe Expected Changes ##

ORSS values changed from `1.0` or `-1.0` to `NA` when the Odds Ratio is `NA`. MET was failing to properly check for bad data.

- [x] Link to relevant issue(s): dtcenter/MET#2887
- [x] Link to relevant pull request(s): dtcenter/MET#2988

### Title ###
- [x] Define the **Title** of this issue as **Update Truth: For dtcenter/{REPO}#{PR_NUMBER}** to indicate the repository and pull request that warranted this issue.

### Assignee ###

*Assign this issue to the author of the pull request that warranted this issue. Optionally assign anyone else who should review the differences in the output.*

- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version if updating truth data for the `develop` branch **OR** select next **METplus-Wrappers-X.Y.Z bugfix** version if updating truth data for a `main_vX.Y` branch.
- [x] If updating truth data for the `develop` branch, select the **METplus-Wrappers-X.Y.Z Development** project **OR** if updating truth for a `main_vX.Y` branch, select the **Coordinated METplus-X.Y Support** project

## Update Truth Checklist ###
- [x] Review the GitHub Actions workflow that was triggered by the PR merge
  - If no differences were found, note this in a comment.
  - If all of the differences are expected, note this in a comment.
    Include any details of how the review was performed.
  - If unexpected differences are found, the following instructions can
    help uncover potential explanations. If none of these apply and the
    source of the differences cannot be determined, contact the
    METplus wrappers lead engineer (@georgemccabe) for assistance.
    - Search for other open issues that have the label `type: update truth`
      applied by clicking on the label on this issue. Coordinate with the
      author of these issues to ensure all diffs are properly reviewed.
    - Check if any additional GitHub Actions testing workflows have been
      triggered since the workflow that corresponds to this issue was run.
      Review the latest run to ensure that there are no diffs that are
      unrelated to this issue.
    - If the incorrect differences are caused by the changes from the
      issue that warranted this issue, consider reverting the PR and
      re-opening the issue.
  - Iterate until one of the above conditions apply.
- [x] Approve the update of the truth data
  - Contact the METplus wrappers lead engineer (@georgemccabe) or
    backup lead (@jprestop) to let them know that the truth data can
    be updated.
- [ ] Update the truth data.
      This should be handled by a METplus wrappers engineer.
      See the [instructions to update the truth data](https://metplus.readthedocs.io/en/develop/Contributors_Guide/continuous_integration.html#update-truth-data-update-truth-yml)
      for more info.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Reviewed the diffs flagged in this [GitHub actions testing workflow](https://github.com/dtcenter/METplus/actions/runs/11301082912) run. Differences are flagged in 16 output files across 8 different use case groups (listed below).

I manually inspected these diffs to confirm that they're limited to properly writing bad data in the `ORSS` column.

```
.//short_range/MODEMultivar_fcstHRRR_obsMRMS_HRRRanl/mode/2021020100/f21/mode_Fcst_WIND_Z10_Obs_WIND_Z10_HRRR_vs_ANALYSIS_210000L_20210201_210000V_000000A_cts_truth.txt
.//short_range 2/GridStat_fcstHRRR_obsPracPerfect_SurrogateSevere/model_applications/short_range/surrogate_severe_prac_perfect/grid_stat/grid_stat_360000L_20200206_120000V_truth.stat
.//short_range 2/GridStat_fcstHRRR_obsPracPerfect_SurrogateSevere/model_applications/short_range/surrogate_severe_prac_perfect/grid_stat/grid_stat_360000L_20200206_120000V_cts_truth.txt
.//marine_and_cryosphere 2/PointStat_fcstRTOFS_obsARGO_climoWOA23_temp/stats/rtofs.20230318/point_stat_RTOFS_ARGO_temp_Z50_240000L_20230318_000000V_truth.stat
.//s2s/TCGen_fcstGFSO_obsBDECKS_GDF_TDF/model_applications/s2s/TCGen_fcstGFSO_obsBDECKS_GDF_TDF/TCGen/tc_gen_2016_cts_truth.txt
.//s2s/TCGen_fcstGFSO_obsBDECKS_GDF_TDF/model_applications/s2s/TCGen_fcstGFSO_obsBDECKS_GDF_TDF/TCGen/tc_gen_2016_truth.stat
.//precipitation/PointStat_fcstMULTI_obsMETAR_PtypeComparisons/model_applications/precipitation/point_stat_gfs_360000L_20210217_000000V_truth.stat
.//precipitation/PointStat_fcstMULTI_obsMETAR_PtypeComparisons/model_applications/precipitation/point_stat_gfsx_480000L_20210217_120000V_truth.stat
.//precipitation/PointStat_fcstMULTI_obsMETAR_PtypeComparisons/model_applications/precipitation/point_stat_gfsx_840000L_20210219_000000V_truth.stat
.//precipitation/PointStat_fcstMULTI_obsMETAR_PtypeComparisons/model_applications/precipitation/point_stat_gfs_480000L_20210217_120000V_truth.stat
.//marine_and_cryosphere/GridStat_MODE_fcstIMS_obsNCEP_sea_ice/model_applications/marine_and_cryosphere/sea_ice/MODE/20190201/mode/mode_IMS_ICEC_vs_NCEP_ICEC_000000L_20190201_220000V_000000A_cts_truth.txt
.//met_tool_wrapper/TCGen/met_tool_wrapper/TCGen/tc_gen_2016_cts_truth.txt
.//met_tool_wrapper/TCGen/met_tool_wrapper/TCGen/tc_gen_2016_truth.stat
.//tc_and_extra_tc/GridStat_fcstHAFS_obsTDR_NetCDF/model_applications/tc_and_extra_tc/tdr/2019082818/grid_stat_HAFS_vs_TDR_180000L_20190829_120000V_truth.stat
.//tc_and_extra_tc/TCGen_fcstGFS_obsBDECK_2021season/model_application/tc_and_extra_tc/TCGen/tc_gen_cts_truth.txt
.//tc_and_extra_tc/TCGen_fcstGFS_obsBDECK_2021season/model_application/tc_and_extra_tc/TCGen/tc_gen_truth.stat
```

**Comment by JohnHalleyGotway** [comment]
@jprestop or @georgemccabe, the METplus truth data for develop can be updated since all diffs flagged are expected due to the better error checking of the `ORSS` column in the CTS line type.

**Comment by georgemccabe** [comment]
Thanks, @JohnHalleyGotway. I will update the truth data.
