### ISSUE TITLE
Documentation: Update existing use cases to use the template

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#2741]
## Describe the Enhancement ##
In the METplus-6.0.0-beta6 release cycle the following issue was created and completed:
[Documentation: Develop an RST template for use cases #918](https://github.com/dtcenter/METplus/issues/918)
The templates have been developed and now we need to update all existing use cases to utilize the templates. 

@CPKalb has already started on using the new templates for some of the existing templates.  

See Tina's [comment on this issue](https://github.com/dtcenter/METplus/issues/2741#issuecomment-2430103669) regarding what she is working on.

@lisagoodrich I talked with Dan about how to get started on this task.  First we'll start with a spreadsheet identifying what cases we have and which fields need to be changed.  We'll talk about all of this before you get started.

### Time Estimate ###
??

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
The current funding for this work ends on **12/31/2024**.

### Funding Source ###
7730022

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by CPKalb** [comment]
@lisagoodrich, @jprestop 

The ones I have been working on are part of [issue 2628](https://github.com/dtcenter/METplus/issues/2628).  While I'm updating the scientific objective, I am also moving them to the new template.  The use cases include:

s2s_mid_lat:
UserScript_fcstGFS_obsERA_Blocking
UserScript_obsERA_obsOnly_Blocking
UserScript_fcstGFS_obsERA_WeatherRegime
UserScript_obsERA_obsOnly_WeatherRegime

s2s_mjo:
UserScript_fcstGFS_obsERA_OMI
UserScript_obsERA_obsOnly_OMI
UserScript_obsERA_obsOnly_RMM
UserScript_obsERA_obsOnly_PhaseDiagram

s2s_stratosphere:
UserScript_fcstGFS_obsERA_StratosphereBias
UserScript_fcstGFS_obsERA_StratospherePolar
UserScript_fcstGFS_obsERA_StratosphereQBO


This is basically all the use cases in s2s_mid_lat and s2s_stratosphere, but there are others in the s2s_mjo area that are not part of that issue.  Let me know if you you want me to just do all the s2s_mjo use cases...

The s2s_mid_lat and s2s_mjo use cases are done and I still need to finish up the stratosphere ones.  I'll do that under issue 2628 since I've already been working there.

**Comment by jprestop** [comment]
@CPKalb Thank you so much for this helpful information!  I really appreciate you taking the time so quickly to list these cases here.

**Comment by CPKalb** [comment]
@jprestop, it looks like the updated documentation has a section for "Version Added."  If we are unsure which version of METplus a use case was added, is there a way to get this information?

**Comment by jprestop** [comment]
> @jprestop, it looks like the updated documentation has a section for "Version Added." If we are unsure which version of METplus a use case was added, is there a way to get this information?

@CPKalb That is a great question.  I tried to look this up via google, but my search strings were not producing the results I was looking for. 

In looking for the version where UserScript_fcstGFS_obsERA_Blocking was added, I believe I was able to find this information.  Here are the steps I took (see [video](https://drive.google.com/file/d/1Z0qBRlK5YWtIK8MJJafefXjqjKaFNPoh/view?usp=sharing) of me walking through it):

- Navigate to the use case in the repository (in this case develop/docs/use_cases/model_applications/s2s_mid_lat/UserScript_fcstGFS_obsERA_Blocking.py)
- Click on "Blame"
- Scroll down to the bottom and look at the left hand column to find the earliest feature number associated with this file
- Look up that closed issue in the respository
- Ensure that it does have to do with the creation of this use case
- Look at the milestone assigned to it

I'm wondering if @JohnHalleyGotway knows of a more straightforward way to get this information.  The method I have found here is time consuming and if the milestone wasn't selected, it could prove to be more difficult to figure out.

**Comment by georgemccabe** [comment]
@jprestop, I did something similar to get this information.

You can also click on the use case doc file, then click on "History" and scroll to the earliest commit to see when it was added. In this case, the file was renamed, but there is a link to see the history before the rename (click "Browse History"). From there, I see the earliest commit was from PR #856, so I clicked on the link to navigate to that PR. From there I can see that it was added for Milestone 4.0.0. 

https://github.com/user-attachments/assets/96a912b2-8b72-499c-8a71-6a363b82ab2f

**Comment by jprestop** [comment]
Status update:
Please see [2024 Existing Use Cases](https://docs.google.com/spreadsheets/d/1Nw_H9Y5U8XBfQEAifCVyFcT-kmDc3R79rwCqIQHptKQ/edit?gid=0#gid=0) for detailed information.
No work was completed on the met_tool_wrappers use cases, but only on the model_applications use cases.
In that spreadsheet, rows 1-15 had all columns worked on and need feedback and potential updates from the case creator in order to be considered completed.
After row 15, we switched to working on columns.  See the PRs associated with this issue for more detailed information, however, the following columns were worked on for all model_application use cases in the spreadsheet:

- Version Added
- Running METplus
- Datasets 
- METplus Workflow

Additionally, dropdown menus were added.

Further work will need funding.

**Comment by mkavulich** [comment]
I noticed in the latest users guide that all the links to use cases under https://metplus.readthedocs.io/en/develop/Verification_Datasets/datasets.html are broken. Is this related to this work?

**Comment by jprestop** [comment]
Hi @mkavulich.  Thanks for letting us know.  To confirm I understand what you are saying - are you talking about how on this [page](https://metplus.readthedocs.io/en/latest/Verification_Datasets/datasets/aeronet.html), for example, under "METplus Use Cases", the link in "Link to [METplus Use Cases](https://metplus.readthedocs.io/en/develop/search.html?q=VxData%26%26UseCase&check_keywords=yes&area=default) for this dataset." is broken? If so, I checked a few others and see that they are all also broken.  I also check a few other versions of the documentation and can't seem to find a version of the documentation where they worked.  This problem is not related to this issue, however, it's definitely something we want to fix.  I'm not sure I know exactly how it should be functioning, but I'll talk with the team, figure out what needs to be done, and will create an issue to fix it.  Thanks for bringing it to our attention, and please let me know if I misunderstood the problem.

**Comment by mkavulich** [comment]
@jprestop, yes that's the problem I was referring to. I wanted to bring it to the team's attention but I didn't want to open a new issue if one already existed. Thanks!

**Comment by jprestop** [comment]
@mkavulich Thank you! I just created issue #2912 for this work.

**Comment by DanielAdriaansen** [comment]
@jprestop is the issue @mkavulich describing a result of the work here? Or is it unrelated?

**Comment by DanielAdriaansen** [comment]
> [@jprestop](https://github.com/jprestop) is the issue [@mkavulich](https://github.com/mkavulich) describing a result of the work here? Or is it unrelated?

Nevermind I finally read this above: 

> This problem is not related to this issue, however, it's definitely something we want to fix.

**Comment by jprestop** [comment]
Closing issue with the creation of this new issue for the remainder of the work: #2917
