### ISSUE TITLE
Internal: Determine/document a process to test use cases that can't run in automated test environment

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#2779]
Currently there are a few use case that are not run in GitHub Actions for various reasons, like they exceed the memory limit or disk space limit. Some of these are noted in the [Contributor's Guide](https://metplus.readthedocs.io/en/develop/Contributors_Guide/add_use_case.html#use-cases-that-cannot-be-run-in-github-actions). As part of the release process, we should make sure to run these use cases outside of the GitHub Actions automated testing environment to ensure that they run as expected.

The Contributor's Guide describes the [process to add use cases that can't be run](https://metplus.readthedocs.io/en/main_v5.1/Contributors_Guide/add_use_case.html#use-cases-that-exceed-memory-allocations-of-github-actions) by not assigning a number to the use case in the internal/tests/use_cases/all_use_cases.txt file and excluding them from the .github/parm/use_case_groups.json file that determines the groups of use cases to run in the automated tests. We have since added support for a "disabled" key in the use_case_groups.json file to always skip those use cases.

There are a few use cases that are not run in the automated tests, but the reason is unclear because they are not listed in the Contributor's Guide section. This could happen for various external reasons (unrelated to GitHub Actions limitations) and we may be planning on eventually getting these cases working again.

## Describe the Task ##
* Update the documentation and process for adding use cases that can't be run in GHA to:
  * Assign a number
  * Mark them as disabled in the JSON use case groups file
  * Add a reason why it is disabled for internal reference so we know if it will never be able to run in GHA or not
* Develop a process to run the use cases that can be run outside of GHA and run them to test that they work (on seneca?)
* Document process to run the cases and see if this step can be scripted to make this testing easier for future releases

### Time Estimate ###
This depends on how much of this work we want to complete for this release and which should move to another issue for future work. We should at very least test the use cases that need to be tested!

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
For now, I will start with testing the use cases that are not run in GHA on seneca. Some of the use cases have input data that is provided with the rest of the data for the model_applications categories. Some of them have data in an additional tar file on the web.

- [X] marine_and_cryosphere:11 GridStat_fcstRTOFS_obsGHRSST_climWOA_sst
  - Ran without errors
  - Ran on seneca using command:
    ```
    run_metplus.py \
    ~/METplus/parm/use_cases/model_applications/marine_and_cryosphere/GridStat_fcstRTOFS_obsGHRSST_climWOA_sst.conf \
    ~/mccabe.seneca.conf \
    user_env_vars.MET_PYTHON_EXE=/home/met_test/miniforge3/envs/icecover.v6.0/bin/python3
    ```

- [X] s2s_stratosphere:1 UserScript_fcstGFS_obsERA_StratospherePolar
  - Data found in https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/v6.0/additional_data_UserScript_fcstGFS_obsERA_StratospherePolar.tgz
  - Added data to seneca:/d1/projects/METplus/METplus_Data/not_in_gha
  - Ran without errors (after bugfix to METcalcpy)
  - Ran on seneca using command:
     ```
    mamba activate weatherregime.v6.0
    run_metplus.py \
    ~/METplus/parm/use_cases/model_applications/s2s_stratosphere/UserScript_fcstGFS_obsERA_StratospherePolar.conf \
    ~/mccabe.seneca.conf \
    config.INPUT_BASE=/d1/projects/METplus/METplus_Data/not_in_gha \
    config.OUTPUT_BASE=/d1/personal/mccabe/out_s2s_strat \
    user_env_vars.PYTHONPATH=/home/mccabe/METcalcpy:/home/mccabe/METdataio:/home/mccabe/METplotpy
    ```

- [X] s2s_stratosphere:2 UserScript_fcstGFS_obsERA_StratosphereQBO
  - Data found in https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/v6.0/additional_data_UserScript_fcstGFS_obsERA_StratosphereQBO.tgz
  - Added data to seneca:/d1/projects/METplus/METplus_Data/not_in_gha
  - Ran without errors
  - Ran on seneca using command:
     ```
    mamba activate weatherregime.v6.0
    run_metplus.py \
    ~/METplus/parm/use_cases/model_applications/s2s_stratosphere/UserScript_fcstGFS_obsERA_StratosphereQBO.conf \
    ~/mccabe.seneca.conf \
    config.INPUT_BASE=/d1/projects/METplus/METplus_Data/not_in_gha \
    config.OUTPUT_BASE=/d1/personal/mccabe/out_s2s_strat2 \
    user_env_vars.PYTHONPATH=/home/mccabe/METcalcpy:/home/mccabe/METdataio:/home/mccabe/METplotpy
    ```

- [X] short_range:14 UserScript_fcstRRFS_fcstOnly_Reformat_Aggregate_Plot
  - Disabled reason: "need new RRFS data with new line types"
  - Not expected to successfully run because we need new input data
  - Ran without errors (after a few minor changes to use case scripts)
  - Ran on seneca using command:
    ```
    mamba activate rrfs_usecase_env
    run_metplus.py \
    ~/METplus/parm/use_cases/model_applications/short_range/UserScript_fcstRRFS_fcstOnly_Reformat_Aggregate_Plot.conf \
    ~/mccabe.seneca.conf \
    config.OUTPUT_BASE=/d1/personal/mccabe/out_short_range14 \
    user_env_vars.PYTHONPATH=/home/mccabe/METcalcpy:/home/mccabe/METdataio:/home/mccabe/METplotpy
    ```
  - Note: will need to create a conda environment in internal/scripts/docker_env for this use case!

- [X] short_range:15 MODEMultivar_fcstRRFS_obsGOES_MRMS_BrightnessTemp_Lightning
  - Ran without errors
  - Ran on seneca using command:
    ```
    run_metplus.py \
    ~/METplus/parm/use_cases/model_applications/short_range/MODEMultivar_fcstRRFS_obsGOES_MRMS_BrightnessTemp_Lightning.conf \
    ~/mccabe.seneca.conf
    ```


I ran each of these using today's MET nightly build directory on seneca. I automate this by setting an environment variable in my .bashrc:
`export TODAY_YMD=$(date +%Y%m%d)`
then set the following in mccabe.seneca.conf:
`MET_INSTALL_DIR=/d1/projects/MET/MET_regression/develop/NB{ENV[TODAY_YMD]}/MET-develop`

**Comment by georgemccabe** [comment]
We discussed the details of this issue on 2/13/2025. We decided to start with scripts that will run nightly as the met_test user on a RAL machine (seneca) to test the use cases that can't run in GHA.

The script should:
* Determine which use cases to run (using jq to parse out use cases marked as not run in GHA in .github/parm/use_case_groups.json)
* Build commands to run use cases (refer to comment above on how to run, could use internal/tests/use_cases/metplus_use_case_suite.py)
* Run use cases using latest nightly build of MET tools -- /d1/projects/MET/MET_regression/develop/NB$(date +%Y%m%d)
* Run use cases using METplus develop and METplus develop-ref?
* Compare results using METplus/metplus/util/diff_util.py
* Send email to alert of any failures or differences

We should also document instructions in the Contributor's Guide to describe how to add a new use case that doesn't run in GitHub Actions:
* Determine if use case cannot run in GHA
* Create conda environment if it doesn't already exist on machine (e.g. ice_cover.v6.0)
* Stage input data (in directory on machine, e.g. /d1/projects/METplus/METplus_Data/not_in_gha and tar file on web server so it is available to users)
* Mark use case in .github/parm/use_case_groups.json so it is picked up by nightly script

We should also include some notes on how to set this up on a new machine (creating conda environments, staging data, etc)

**Comment by JohnHalleyGotway** [comment]
Recommend that we reconsider our approach based on recent developments with GitHub.

On Feb 21, 2025, the dtcenter organization applied for the [GitHub for Nonprofits](https://github.com/solutions/industry/nonprofits) program. The application was approved the same day, and changes should appear in the dtcenter organization with 2 weeks. This program gives the dtcenter free access to the **GitHub Team** account (normally $4/person/month). In addition, it grants us access to GitHub Actions [Larger Runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners), for a fee (see [pricing](https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates)).

Our options now are to pay for GitHub-hosted larger runners or to pursue self-hosted runners using our own local hardware.

Here's a proposed strategy:
1. Brainstorm logic for how to include the running of these large use cases into our existing workflow.
   - Could define a new `testing_large_runner.yml` workflow to isolate these use cases.
   - If using GitHub-hosted larger runners, we could include them in the existing `testing.yml` workflow and add logic to determine whether or not these "large use case" jobs should actually be run.
   - If using self-hosted runners, might be wise to isolate them into a separate workflow.
2. If using GitHub-hosted larger runners, deteremine the least expensive "larger runner" necessary for each use case that doesn't run on the standard hardware (as opposed to  a local nightly build solution).
3. With either, be sure to provide a manual "workflow dispatch" option. If included in `testing.yml`, make the running of "large use cases" optional with checkbox (default = false). Or we could provide much finer control over what use cases are run via workflow dispatch.
4. To start, recommend ONLY running "large use cases" when workflow dispatch requests them or when a **new tag** is created in the METplus repository. Although, if using self-hosted runners, consider running the `testing_large_runner.yml` workflow at the same cadence as the `testing.yml` workflow.
5. Consider refining this logic and frequency as needed based on cost and complexity.

**Comment by georgemccabe** [comment]
I ran the above use cases on seneca using the coordinated v6.1 main branches. I used the v6.1 instead of v.6.0 conda environments. All of the use cases ran without issue except for s2s_stratosphere/UserScript_fcstGFS_obsERA_StratosphereQBO.conf, which required a bugfix to remove a deprecated, unused import in METplotpy: see https://github.com/dtcenter/METplotpy/pull/516

Because the testing has been completed to prepare for the v6.1.0 release and there is currently no funding to implement an automated approach to running the use cases that require more resources than what GitHub Actions provides on its free tier, I am moving this issue to the 6.2 project board.

**Comment by georgemccabe** [comment]
New commands run on seneca to test for v6.2.0:

Setup steps:
* Set `MET_INSTALL_DIR=/d1/projects/MET/MET_regression/main_v12.2/latest` in `~/mccabe.seneca.conf`
* Update ~/METplotpy, ~/METdataio, and ~/METcalcpy to get latest changes from `main_v3.2` branches
* Update ~/METplus to use `main_v6.2` branch

Use case commands:
- [X] marine_and_cryosphere:11 GridStat_fcstRTOFS_obsGHRSST_climWOA_sst
```
run_metplus.py \
~/METplus/parm/use_cases/model_applications/marine_and_cryosphere/GridStat_fcstRTOFS_obsGHRSST_climWOA_sst.conf \
~/mccabe.seneca.conf \
user_env_vars.MET_PYTHON_EXE=/home/met_test/miniforge3/envs/icecover.v6.1/bin/python3
```

- [X] s2s_stratosphere:1 UserScript_fcstGFS_obsERA_StratospherePolar
```
mamba activate weatherregime.v6.1
run_metplus.py \
~/METplus/parm/use_cases/model_applications/s2s_stratosphere/UserScript_fcstGFS_obsERA_StratospherePolar.conf \
~/mccabe.seneca.conf \
config.INPUT_BASE=/d1/projects/METplus/METplus_Data/not_in_gha \
config.OUTPUT_BASE=/d1/personal/mccabe/out_s2s_strat_v6.2 \
user_env_vars.PYTHONPATH=/home/mccabe/METcalcpy:/home/mccabe/METdataio:/home/mccabe/METplotpy
```

- [x] s2s_stratosphere:2 UserScript_fcstGFS_obsERA_StratosphereQBO
```
mamba activate weatherregime.v6.1
run_metplus.py \
~/METplus/parm/use_cases/model_applications/s2s_stratosphere/UserScript_fcstGFS_obsERA_StratosphereQBO.conf \
~/mccabe.seneca.conf \
config.INPUT_BASE=/d1/projects/METplus/METplus_Data/not_in_gha \
config.OUTPUT_BASE=/d1/personal/mccabe/out_s2s_strat2_v6.2 \
user_env_vars.PYTHONPATH=/home/mccabe/METcalcpy:/home/mccabe/METdataio:/home/mccabe/METplotpy
```

- [X] short_range:14 UserScript_fcstRRFS_fcstOnly_Reformat_Aggregate_Plot
```
mamba activate rrfs_usecase_env
run_metplus.py \
~/METplus/parm/use_cases/model_applications/short_range/UserScript_fcstRRFS_fcstOnly_Reformat_Aggregate_Plot.conf \
~/mccabe.seneca.conf \
config.OUTPUT_BASE=/d1/personal/mccabe/out_short_range14_v6.2 \
user_env_vars.PYTHONPATH=/home/mccabe/METcalcpy:/home/mccabe/METdataio:/home/mccabe/METplotpy \
user_env_vars.PRE_LOAD_CHROME=True
```

- [x] short_range:15 MODEMultivar_fcstRRFS_obsGOES_MRMS_BrightnessTemp_Lightning
```
run_metplus.py \
~/METplus/parm/use_cases/model_applications/short_range/MODEMultivar_fcstRRFS_obsGOES_MRMS_BrightnessTemp_Lightning.conf \
~/mccabe.seneca.conf
```

**Comment by georgemccabe** [comment]
Current funding does not allow us to complete the work to automate the running of the use cases that cannot run in GitHub Actions provided runners. This issue has become cluttered with the tracking of manual testing of these use cases for each release. I am moving this issue off of the project board and into the **Consider for Next Release** milestone. I created #3192 to track testing for the v7.0.0-beta1 release and will create new issues for each development cycle to ensure testing has been completed after each dev (betaN or rcN) release.
