### ISSUE TITLE
New Wrapper: PairStat

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2781]
## Describe the New Feature ##
Issue dtcenter/MET#3006 adds a new tool named Pair-Stat to read already paired forecast/observation data from input files, filter as requested, and compute/write ASCII output statistics. This logic is pretty similar to the existing Point-Stat tool, however we'll only have a single input data source rather than separate ones for forecasts and observations. The initial implementation will support two data source types:
- ASCII MPR data generated by Point-Stat or provided through Python-embedding
- IODA pairs

The specifics of the usage statement and configuration file contents are still under development, but will be noted here once they are finalized.

**Pair-Stat Usage**:
TDB

**Pair-Stat Configuration File**:
TBD

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
Approx 1 week?

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
None needed.

### Relevant Deadlines ###
Do not charge 7730022 past 12/30/2024.

### Funding Source ###
7730022 NRL METplus

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @georgemccabe will implement
- [x] Select **scientist(s)** or **no scientist** required: @DanielAdriaansen will advise.

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **METplus-Wrappers-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **METplus-Wrappers-X.Y.Z** version, select the **METplus-Wrappers-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- No impacts to METplus Analysis expected since Pair-Stat will create .stat files with existing line types.

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplus-Wrappers-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
At the same time this work is done for the new wrapper, we should develop a corresponding `met_tool_wrapper` use case to demonstrate it's functionality. Maybe that's a separate issue but @JohnHalleyGotway mentioned that @georgemccabe may have off-the-shelf scripts or code to set up a basic use case to demonstrate the tool, so it may be contained within this issue. @georgemccabe please advise if you feel strongly about a separate issue. Thanks!

**Comment by georgemccabe** [comment]
Part of the process of adding a new wrapper is to include a met_tool_wrapper basic use case to demonstrate its use.

**Comment by JohnHalleyGotway** [comment]
Current usage statement as of 12/16/24:
```
*** Model Evaluation Tools (METV12.1.0) ***

Usage: pair_stat
	-pairs file
	-format type
	-config config_file
	[-outdir path]
	[-log file]
	[-v level]

	where	"-pairs file" is one or more files containing forecast/observation pairs. May be used multiple times (required).
		"-format type" defines the input pairs file format and may be set to "mpr" or "ioda" (required).
		"-config config_file" is a PairStatConfig file containing the desired configuration settings (required).
		"-outdir path" overrides the default output directory (.) (optional).
		"-log file" outputs log messages to the specified file (optional).
		"-v level" overrides the default level of logging (2) (optional).
```
Recommend that we change to `-pairs file_list` to support file list input to handle a very long list of inputs.
