### ISSUE TITLE
Update Truth: For dtcenter/MET#3008

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2811]
## Describe Expected Changes ##

Adds a `units` attribute to the NetCDF output from Gen-Vx-Mask, and in many cases, `units = flag`. This has led to a change in the `OBS_UNITS` column for at least one of the METplus use cases. Rather than being set to `NA`, it now contains `flag`. This change does make sense. When MET reads NetCDF inputs, it does check for, store, and write to the output the value of the `units` variable attribute.

- [x] Link to relevant issue(s): dtcenter/MET#2966
- [x] Link to relevant pull request(s): dtcenter/MET#3008

### Title ###
- [x] Define the **Title** of this issue as **Update Truth: For dtcenter/{REPO}#{PR_NUMBER}** to indicate the repository and pull request that warranted this issue.

### Assignee ###

*Assign this issue to the author of the pull request that warranted this issue. Optionally assign anyone else who should review the differences in the output.*

- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version if updating truth data for the `develop` branch **OR** select next **METplus-Wrappers-X.Y.Z bugfix** version if updating truth data for a `main_vX.Y` branch.
- [x] If updating truth data for the `develop` branch, select the **METplus-Wrappers-X.Y.Z Development** project **OR** if updating truth for a `main_vX.Y` branch, select the **Coordinated METplus-X.Y Support** project

## Update Truth Checklist ###
- [x] Review the GitHub Actions workflow that was triggered by the PR merge
  - If no differences were found, note this in a comment.
  - If all of the differences are expected, note this in a comment.
    Include any details of how the review was performed.
  - If unexpected differences are found, the following instructions can
    help uncover potential explanations. If none of these apply and the
    source of the differences cannot be determined, contact the
    METplus wrappers lead engineer (@georgemccabe) for assistance.
    - Search for other open issues that have the label `type: update truth`
      applied by clicking on the label on this issue. Coordinate with the
      author of these issues to ensure all diffs are properly reviewed.
    - Check if any additional GitHub Actions testing workflows have been
      triggered since the workflow that corresponds to this issue was run.
      Review the latest run to ensure that there are no diffs that are
      unrelated to this issue.
    - If the incorrect differences are caused by the changes from the
      issue that warranted this issue, consider reverting the PR and
      re-opening the issue.
  - Iterate until one of the above conditions apply.
- [x] Approve the update of the truth data
  - Contact the METplus wrappers lead engineer (@georgemccabe) or
    backup lead (@jprestop) to let them know that the truth data can
    be updated.
- [ ] Update the truth data.
      This should be handled by a METplus wrappers engineer.
      See the [instructions to update the truth data](https://metplus.readthedocs.io/en/develop/Contributors_Guide/continuous_integration.html#update-truth-data-update-truth-yml)
      for more info.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
This METplus [GHA testing workflow run](https://github.com/dtcenter/METplus/actions/runs/11982948239) was triggered by this [MET commit](https://github.com/dtcenter/MET/commit/183bccc764b0a1d0afe73be1aff23e489e9b1af7). Differences were flagged Grid-Stat output from this [fire use case](https://github.com/dtcenter/METplus/actions/runs/11982948239/job/33411860523). The diffs are limited to the `OBS_UNITS` column changing from `NA` to `flag`.

This difference is consistent with the changes made to the Gen-Vx-Mask code.

The METplus truth data for the develop branch can be safely updated.
