### ISSUE TITLE
Internal: Refine testing GitHub Action workflow dispatch functionality

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#2816]
## Describe the Enhancement ##
This was intially discussed during the [METplus 5.0 Release Retrospective](https://docs.google.com/document/d/1z0YM0d_xI2WCXFY5FuhpUbgXD3NXab0susAPY4Ry16Q/edit?pli=1#). In GitHub actions for METplus the testing.yml workflow has a `workflow dispatch` feature. This enable you to manually trigger runs of that workflow for any feature branch you choose. This issue is to enhance that functionality in 2 ways:

1. Specify the reference branch. All manually triggered workflow runs are diffed against the `develop-ref` truth data. Enhance this to let the user pick the reference truth dataset (i.e. `develop-ref`, `main_v11.0-ref`, and so on). Alternatively, you could enhance the script logic to automatically pick the *right* reference dataset.

2. Improve the GHA run name. Currently, all manually triggered testing workflow runs are simply named `Testing`, like this:
<img width="386" alt="Screen Shot 2023-02-23 at 10 52 55 AM" src="https://user-images.githubusercontent.com/21087144/220989435-60bbedcd-7018-4603-9738-a378f23dde11.png">
Enhance this to include the name of the branch being run at a minimum. Consider also including the reference dataset name, if that's made to be configurable.

Remember to migrate this functionality to the other METplus repos.

### Time Estimate ###
1 day?

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
NRL METplus 7730022 

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Once happy with these changes, recommend migrating them to the other METplus repos as well.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Does this issue belong in the METplus repository?

**Comment by georgemccabe** [comment]
For (1): I believe [this code](https://github.com/dtcenter/METplus/blob/6ad1d5eb2ee51abac1d9796ea69d59c23d04620f/.github/jobs/setup_and_run_diff.py#L37-L41) gets the main_vX.Y truth data for branches that contain main_vX.Y in the name, otherwise it uses develop.

For (2): It looks like `run-name` can be used to set the workflow run title
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name
