### ISSUE TITLE
Create python embedding script to read in tripolar grids into a METplus use case

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/METplus#417]
## Describe the Task ##
Create a python embedding to read in tripolar grid data. This will allow METplus to handle ocean and ice model data, specifically from NOAA's Real-Time Ocean Forecast System (RTOFS) model. There is an existing METplus use case for calculating relevant metrics for sea ice evaluation. 

### Time Estimate ###
I (Lindsay) estimate that this task will take me about 3 full days of work, perhaps a little less with the assistance of George.

### Sub-Issues ###
- [x] take the processing script shared by Todd and Deanna Spindler from NOAA and isolate the relevant xarray/tripolar IO part of the code.
- [x] Create a python embedding script that reads in and properly stores the sea ice data from the model
- [x] Run plot_data_plane passing the resulting xarray object as "met_data" in order to confirm veracity.
- [x] Run the sea ice METplus use case with the python embedding script and produce statistics comparing the RTOFS model against an analysis. 

### Relevant Deadlines ###
This project ends on June 30, 2020.

### Funding Source ###
Account key 2760811

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: George McCabe
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [x] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
Issue #350 

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
The addition of this use case should complete this task: https://metplus.readthedocs.io/en/latest/generated/model_applications/marine_and_coastal/PlotDataPlane_obsHYCOM_coordTripolar.html#sphx-glr-generated-model-applications-marine-and-coastal-plotdataplane-obshycom-coordtripolar-py

Possible duplicate of #791
