### ISSUE TITLE
Reorganize sphinx documentation files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#418]
Users have been confused with the directories under parm/use_cases having two files with the same name -- one ending with .conf that is read by METplus and one ending with .py which is the documentation file. Users often think that the .py file is a python script that should be executed or read by METplus.

## Describe the Enhancement ##
* Create a docs/use_cases directory structure that mimics the organization of the directories under parm/use_cases.
* Move a few .py files into the new directory structure
* The README files in the parm/use_cases directories should be moved to the docs/use_cases directory
* The README files in the parm/use_cases directories should be replaced with instructions to point the user to the online documentation and either instructions to build the docs locally or point them to the docs/use_cases area so they can view the info if they are offline
* Update the docs/conf.py file to add the new area to the list of directories that are read by sphinx
* Test that the documentation can be rendered from the new area
* Apply this change to all use cases

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
The new structure should be replicated when we move the MET (and other) documentation over to using Sphinx.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name: `feature_418_sphinx_use_case_reorg`
- [X] Complete the development and test your changes.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Push local changes to GitHub.
- [X] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
