### ISSUE TITLE
Allow regrid_data_plane wrapper to input multiple fields

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METplus#421]
## Describe the New Feature ##
Currently, when two variables are listed in a .conf file for the regrid_data_plane wrapper, it the wrapper runs regrid_data_plane twice, like below:
regrid_data_plane, input_file, G211, output_file -method MAXGAUSS -width 1 -field 'name="ENS_FREQ_14.2"; level="(*,*)";' 
regrid_data_plane, input_file, G211, output_file -method MAXGAUSS -width 1 -field 'name="ENS_FREQ_19.0"; level="(*,*)";' 

It would be useful to have the ability to have the wrapper input multiple field as such:
regrid_data_plane, input_file, G211, output_file -method MAXGAUSS -width 1 -field 'name="ENS_FREQ_14.2"; level="(*,*)";' -field  'name="ENS_FREQ_19.0"; level="(*,*)";'

### Acceptance Testing ###
input files: any data file with multiple fields

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
None

### Relevant Deadlines ###
Helpful for surrogate severe calculation and hail, so ideally 04/20/2020

### Funding Source ###
2770041

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_421_rdp_multi_field`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
