### ISSUE TITLE
GenVxMask wrapper subtask - documentation and tests

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#423]
This is a sub-issue of #387 

## Describe the Sub-Issue ##
* Create documentation files for new use cases
* Add unit tests for GenVxMask wrapper
* Add unit tests for changes to other code needed for wrapper
* Add new use cases to test_use_cases.py and run

### Time Estimate ###
About 1 to 2 days of work.

### Relevant Deadlines ###
Needed for HWT

### Funding Source ###
2770471 - SWPC

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by georgemccabe** [comment]
### Documentation:
* Added 3 use cases with documentation files:
http://icculus.rap.ucar.edu/metplus-test/Users_Guide/met_tool_wrapper/index.html#genvxmask
* Added section to Python Wrappers and added all config variables to glossary
http://icculus.rap.ucar.edu/metplus-test/Users_Guide/wrappers.html#genvxmask
* Added up-to-date info to create a new wrapper in Contributor's Guide:
http://icculus.rap.ucar.edu/metplus-test/Contributors_Guide/create_wrapper.html

### Testing:
* Added pytests for GenVxMask and additional functionality needed to support new tool (i.e. allowing grid definitions in place of a file path) - all tests passed
* Added 3 new use cases configs to Use Case test script
