### ISSUE TITLE
Update Tutorial Chapter 4 for MET 9.0, METplus 3.0

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#428]
*Replace italics below with details for this issue.*

## Describe the Task ##
Update Chapter 4 pages to reflect changes to MET9, METplus3
Chapter 4 uses MODE, MTD MET tools; Mode, MTD METplus

### Time Estimate ###
12 pages to review, update
Check for moved or removed links, renamed tools
~1 week at 50%; goal next Tuesday

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *MET mode*
- [ ] *METplus Mode*
- [ ] *MET MTD*
- [ ] *METplus MTD*
- [ ] *Additional Exercises*

### Relevant Deadlines ###
*METplus3.1 beta*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Todd Arbetter, George McCabe
- [x] John Opatz

### Labels ###
- [x] MET/METplus documentation (online tutorial)
- [x] High priority
- [x] NCAR

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
Issue #443, METplus MTD, needs to be resolved

**Comment by j-opatz** [comment]
I have reviewed the tutorial chapter and have the following comments:

MET Tool: MODE splash page

—Links to MET users guide goes too ver. 8.0, not 9.0

MODE Tool: configure	

—Links to MET users guide goes to ver 8.1, not 9.0

MODE Tool: output

—The tutorial lists what royal blue is, but what does red mean? Or green?
—NCView is installed on the system, but it’s not set for my path and I’m guessing not for the average tutorial taker (on Dakota). How can they set this up?

Use case: MODE

—Link to MET user's guide goes to ver 8.1, not 9.0
—The METplus user’s guide link is broken
—The path to the logs ($METPLUS_TUTORIAL_DIR/output/mode/logs/) does not exist. Is it supposed to be $METPLUS_TUTORIAL_DIR/output/logs/?

MTD: configure

—Make sure to address the yellow box’s comment
—the first blue box should probably indicate the censor_thresh, censor_val, and conv_time_window to provide contextual clues for where the change should be made (almost thought that I should be setting these variables myself!)
—for the conv_radius, should the “/grid_res” remain there?

MTD: Run

—Running MTD with the command given produces an error: “yyerror() -> syntax error in file ‘/tmp/met_config_26409_0’ line 244 text =‘(nut)’”

METplus Use Case: MTD

—MET users guide links to ver 8.1, not 9.0
—METplus users guide link is broken
—The path to the logs ($METPLUS_TUTORIAL_DIR/output/mtd/logs/) does not exist. Is it supposed to be $METPLUS_TUTORIAL_DIR/output/logs/?

Additional exercises

—The OUTPUT_BASE variable doesn’t exist in the mid.skip.conf or mtd.unzip.conf files, it’s in the tutorial.conf file. This should be indicated in the tutorial so the user isn’t confused
—Can a link to the METplus User's guide glossary be added for the scrub_staging_dir and staging_dir

**Comment by TaraJensen** [comment]
I'm done with this chapter

**Comment by fentoad72** [comment]
Closed unless errors are found testing on supporting NCAR, NOAA platforms (#468)
