### ISSUE TITLE
Add the PR approval process steps to the contributor's guide. 

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#429]
## Describe the Task ##
Add the PR approval process steps to Chapter 6 of the contributor's guide.   Also work on the formatting of that chapter to get to render well on GitHub pages.
Merge into the master_v3.0 and develop branches.
Push the changes to the gh-pages branch, rendered here:
   https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None required.

### Relevant Deadlines ###
None.

### Funding Source ###
2702691

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required. John HG.
- [X] Select **scientist(s)** or **no scientist** required. Not required.

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components: No impacts.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Some notes I had lying around:

For internal development, the person submitting the PR selects appropriate reviewer(s).  Make sense?
For external contributors, recommend that the met-help point person is responsible for assigning un-assigned PR on their day.  Good idea?
Need to setup and ensure that TravisCI regression tests pass.
Talked to Lisa about breaking a big issue (> 3 days), MET docs from Lyx to Sphinx, down into sub-issues (< 3 days).
Generally, use 1 branch for the parent issue (not separate ones for each sub-issue).
Generally, do 1 PR for each sub-issue to merge from the parent branch into the source branch.
Is this a good approach?

**Comment by georgemccabe** [comment]
@JohnHalleyGotway, those all make sense to me. I recently made a PR for sub-tasks I was working on because I wanted to get the changes into the develop branch sooner than later so others can discover anything that may break things that aren't covered by the automated tests. The changes seemed to make sense on their own, meaning they didn't rely on other sub-tasks to be complete. If a sub-task doesn't make sense in the code base without other sub-tasks being completed, then I would say we should wait to create a PR. 

An example of the former is #510, which is a sub-task of #569. The changes in #510 allowed the pytests to be called by simply running 'pytest' in the top level directory instead of relying on a script to call each test. This allows us to utilize the code coverage tools with pytest and makes it easier to add new tests. While the sub-task is required to complete #569, it is useful on its own for other improvements.
 
An example of the latter could be adding documentation to go with code changes. While modifying the docs is a sub-task, it doesn't really make sense to push the code changes without the docs.

**Comment by jprestop** [comment]
The formatting of that chapter 6 to have it render well on GitHub pages was handled in [Issue 688](https://github.com/dtcenter/METplus/issues/688) and is now complete.

Also, I wanted to note a change from John's comment on "Aug 21, 2020", which said "Need to setup and ensure that TravisCI regression tests pass." to note that we are switching from using TravisCI to using GitHub Actions.
