### ISSUE TITLE
Create new Skymet use case for state variables

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#435]
## Describe the New Feature ##
Create a new use case for the Skymet project that runs ascii2nc and point_stat on state variables.
- Loop over the initialization time
- Loop over the model lead times (00 to 240, every 1 hour)
- For each valid time:
  - Check to see if daily ascii2nc NetCDF output file already exists.  And if not, run ascii2nc.
  - Run point_stat for “state” variables to compare post-processed WRF GRIB2 output to ascii2nc output.

### Acceptance Testing ###
*List input data types and sources.*
**Raw ASCII obs input:** /glade/u/home/ishitas/met_obs/int_obs_met/<YYYYMMDD>/met_int_obs.<YYYYMMDD>.csv
**Post-processed WRF GRIB2 fcst input:** /glade/p/ral/wsap/jaredlee/Skymet/wrf/exp<01-05>/<YYYY-MM-DD_HH>/uppout/WRFPRS_d01.\<HH orHHH\>.grib2 
**MET NetCDF obs input:** /glade/p/ral/jntp/jpresto/Skymet/obs/ascii2nc/
**MET PointStat output:** /glade/p/ral/jntp/jpresto/Skymet/wrf/exp<01-05>/<YYYY-MM-DD_HH>/metout/point_stat
**MET config file:** /glade/p/ral/jntp/jpresto/Skymet/config/PointStatConfig_state_vars
**MET poly file:** /glade/p/ral/jntp/jpresto/Skymet/poly/Madhya_Pradesh_mask.nc

*Describe tests required for new functionality.*

### Time Estimate ###
1 - 3 days of work.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
ASAP

### Funding Source ###
Skymet Project 774115

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Julie Prestopnik
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: feature_435_skymet_state
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Funding for this work ran out before it was completed.  Closing issue for now.  Relevant files are being stored at kiowa:/d1/personal/jpresto/METplus/Skymet.tar and narya:/Users/jpresto/Projects/METplus/keep/Skymet.tar. Work was being done in feature_435_skymet_state.
