### ISSUE TITLE
Develop TC-RMW wrapper

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplus#437]
## Describe the New Feature ##
We need to develop a TC-RMW wrapper that provides configurability based on the tool conf options.  It's anticipated George will set-up the wrapper with guidance from David, Kathryn, and Tracy.  

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
~ 30 hours of work

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Needs to be done by 5/3/2020 - end of DTC AOP

### Funding Source ###
2780601

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required - Tracy Hertnekey can help with testing

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_437_tc_rmw`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
