### ISSUE TITLE
GridStat and other wrappers set input dir to OUTPUT_BASE if not set

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#446]
This should be set to an empty string if not set so the user can define the entire input path using the input template variable.

## Describe the Enhancement ##
Go through each wrapper and make sure the default value for *_INPUT_DIR is an empty string and not OUTPUT_BASE.

### Time Estimate ###
~ 1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by hankenstein2** [comment]
First step. OUTPUT_BASE is not set to INPUT_BASE anywhere
grep -r "OUTPUT_BASE =" * and
grep -r "OUTPUT_BASE=" *

show that only internal_tests have OUTPUT_BASE set to something explicit

**Comment by georgemccabe** [comment]
Sorry, there was a typo in the initial comment. _INPUT_DIR is set to OUTPUT_BASE by default when it should be set to an empty string so the full path to input data can be defined in the corresponding _INPUT_TEMPLATE. For example, currently we have:

```
        c_dict['FCST_INPUT_DIR'] = \
          self.config.getdir('FCST_GRID_STAT_INPUT_DIR', self.config.getdir('OUTPUT_BASE'))
        c_dict['FCST_INPUT_TEMPLATE'] = \
          self.config.getraw('filename_templates',
                             'FCST_GRID_STAT_INPUT_TEMPLATE')
```

The _INPUT_TEMPLATE is required and we tell users that the _INPUT_DIR is optional so you can put the full path in _INPUT_TEMPLATE. The way the above code works now, if you do that, then the path will be {OUTPUT_BASE}/some/full/path/to/input/data/filename.txt, when the intended path should be /some/full/path/to/input/data/filename.txt. It should look like this:

```
        c_dict['FCST_INPUT_DIR'] = \
          self.config.getdir('FCST_GRID_STAT_INPUT_DIR',
                             '')
        c_dict['FCST_INPUT_TEMPLATE'] = \
          self.config.getraw('filename_templates',
                             'FCST_GRID_STAT_INPUT_TEMPLATE')
        if not c_dict['FCST_INPUT_TEMPLATE']:
            self.log_error("FCST_GRID_STAT_INPUT_TEMPLATE is required to run")
```

getraw returns an empty string if it is not found, so we also need to check that it is set because it is required. If it is not set, then we call log_error and the initialization of the wrapper will fail. (A recent change I made in a branch sets self.isOK = False inside log_error, so you no longer need to explicitly set it to False if an error is found in the create_c_dict function).
