### ISSUE TITLE
Enhance PointStat to process one field at a time

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#451]
Currently PointStat only can process all fields specified in one call per run time.

## Describe the Enhancement ##
Other wrappers, like GridStat, have an option (GRID_STAT_ONCE_PER_FIELD) to specify whether to process once per field or once for all fields. This option could be made available for PointStat as well with a few modifications of the code:

* Read POINT_STAT_ONCE_PER_FIELD from config and set c_dict['ONCE_PER_FIELD'] in the create_c_dict function

* Remove PointStat wrapper's run_at_time_once function so that it calls its parent (CompareGridded) implementation

* Modify CommandBuilder.find_data to handle offsets by reading self.c_dict['OFFSETS'] and loop over the list of values to find data. It should use a default value of 0 if it is not set, i.e. self.c_dict.get('OFFSETS', 0) so that wrappers that don't set OFFSETS will still work.

* Modify CompareGridded.run_at_time_once to use a default for ONCE_PER_FIELD if it is not set to make sure it doesn't crash if that c_dict item is not set in a wrapper.

* Test to make sure this change does not break other wrappers and existing use cases.

### Time Estimate ###
Approximately 2 days of work

### Sub-Issues ###
None

### Relevant Deadlines ###
Skymet use case (#435)

### Funding Source ###
Skymet Project 774115

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] no scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  feature_451_point_stat_once_per_field
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature 451 point stat once per field`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by jprestop** [comment]
I don't know that we can use the Skymet funding for this task.  I was only allocated 20 hours and I'm sure I've gone through that.  We should check with Tara to see if another funding source can be used since this work will benefit others and be used by others.  If another funding source cannot be used, we should check with the Skymet folks before charging their account.
