### ISSUE TITLE
Reorganize data directories for met_tool_wrapper use cases

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#452]
Currently the met_test directory contains all of the data used for the met_tool_wrapper use cases. This data was based on the data used and generated by the MET make test runs. More data was needed to setup all of single wrapper use cases and was added, but the data is very disorganized.

## Describe the Enhancement ##
More info needed

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] Create a met_tool_wrapper directory to contain the new data
- [ ] Review the data in met_test (leaving it as-is) and adding what we want to met_tool_wrapper. this review includes:
  - [ ] replacing old data (i.e. RUC) with more current data
  - [ ] subsetting grib data to only contain the fields used in the tests/cases
  - [ ] Removing redundant data
  - [ ] reorganizing directories
- [ ] Update met_tool_wrapper use cases conf files to use new path to data
- [ ] What else?

Potential subtasks:
- [ ] Make met_tool_wrappers more comprehensive of what needs to be tested in MET
- [ ] Enhance METplus to keep track of commands that were called by a wrapper (exists as self.all_commands) with the corresponding environment variables needed to run. Then use this information to generate a file of all commands run in met_tool_wrappers to be used to run MET tests

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [MET] Need to update tests to be more comprehensive and obtain tarball of met_tool_wrapper data to run tests
- [ ] Others?

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
When we do this, we may want to consider moving the multi-variate MODE use case into the met_tool_wrapper area since it is demonstrating a new way to use that tool for the first time. This would involve moving the input data for that use case into this dataset.
