### ISSUE TITLE
GenVxMask wrapper doesn't handle commas within command line arguments properly

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#454]
The user provides command line arguments pass to gen_vx_mask for each call. The wrapper can be configured to run the tool multiple times, applying new filters for each call. The logic currently separates the arguments to these calls with a comma. However, if the command line arguments contain a comma within [] or (), the arguments will be split up incorrectly. Example: level="(*,*) or censor_thresh=[lt5,gt3] will be split up.

## Describe the Enhancement ##
While this is technically a bug, the wrapper is not available in 3.0, so the development should go into the 3.1 beta2 release.

### Time Estimate ###
2 days

### Sub-Issues ###
None

### Relevant Deadlines ###
Issue #427 needs this work done to be completed

### Funding Source ###
2770471 - SWPC

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  feature_427_gen_vx_mask_swpc
- [X] Complete the development and test your changes.
- [X] Add/update unit tests.
- [X] Add/update documentation.
- [X] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature 427 gen_vx_mask_swpc`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
Jonathan approved this pull request via email by ensuring his use case now works correctly after the fix.
