### ISSUE TITLE
Setup new location to house INPUT DATA for testing

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#461]
## Describe the Task ##
Currently the required input data to run the automated tests in Travis CI is pulling
down the test data from the v3.0 release assets ( attachments ). https://github.com/NCAR/METplus/releases/tag/v3.0  

**IMMEDIATE TERM**: 🚀 
- [ ] DETERMINE if Google Drive can Be used to meet the requirements of this task.

- [ ] Define a location (Where should we house the Binary Data required by METplus?)
        MUST BE Accessible to PULL IT IN TO TRAVIS CI (ie. curl).
  - Test Input data for running internal tests
  - Any other binary data that may be required ie.:
   GempakToCF.jar
   sphinx_rtd_theme-0.2.5b1.post1-py2.py3-none-any.wh  (Used for documentation version chooser)

- [ ] Define a structure to support the needs of releases, Consider:
  -How MET does this ?
  -Support Release Based and Branch specific Data Sets ... or One superdata set ?
  - METplus_3.0
     METplus_3.X
     develop  (this would support feature_* branches, and be used as new use cases and data is added for that use case ...)

- [ ] Add and use the new structure within the Continuous Integration framework.
    Will need to add logic to travis such that it will pull down the correct input data based on the branch (and tests) it is running the tests against. !! or in the short term just basically do what it is doing now, but grab the data from the new location ....  

**LONG TERM**: 🐢 
- Look in to the use, feasibility (will it meet requirements) and The how of docker data containers
- Would still need to support the above IMMEDIATE TERM requirements

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
In the last METplus engineering meeting, we discussed adding new sample data on beta releases that can be downloaded by Travis to run the new use cases.

**Comment by fentoad72** [comment]
taking over travis from jimfrimel

**Comment by georgemccabe** [comment]
Closing this issue since we now list the version of sample data tarballs on each release. New ones will be added as assets.
