### ISSUE TITLE
Add new use case for MTD with convection allowing models

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/METplus#463]
## Describe the Task ##
Add a new use case utilizing MODE Time Domain (MTD) under the model_applications/convection_allowing_models area of the use cases.

### Time Estimate ###
1-2 days

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
I assigned this to myself and @TaraJensen for now, but I think there may be a scientist better suited to this than myself because I'm not too familiar with MTD or where to source CAM data or what might be evaluated from CAM output using MTD.

**Comment by DanielAdriaansen** [comment]
@TaraJensen where should we start with this, or is it still needed? Is there a community user who might be able to help us with a CAM MTD use case? Or should we just acquire some CAM output and use accumulated precipitation? I can no longer remember what this use case specifically should be designed to evaluate from the CAM with MTD (i.e. the specific verification task to demonstrate).

**Comment by DanielAdriaansen** [comment]
@TaraJensen can you advise about this issue? Please see my last comment from 9/10/2020 above: https://github.com/dtcenter/METplus/issues/463#issuecomment-690584120

**Comment by DanielAdriaansen** [comment]
@TaraJensen, I was reviewing open METplus issues assigned to myself and found this one. Can you provide an update on whether this is still desirable to do and if so where to charge? Thanks!
