### ISSUE TITLE
Address Travis CI build and Docker image MET/METplus build timing

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#467]
## Describe the Task ##

This Task is also defined as a Sub-issue to: #478 
However, it can be considered/viewed and implemented as a separate task,
independent of the parent task.

Implement a solution and/or define a workflow that removes the timing dependency
between Docker Hub images and Travis CI pulling those images.

Currently, commits to METplus on GithHub trigger both a METplus Travis Build and a
METplus Docker Hub image build. Typically The Travis build runs before
DockerHub builds a new METplus image.

The point is that there exists the potential that the a Docker Hub image used by 
Travis CI (docker pull), may not be the current image required by the Travis CI Build 
that is running.

**NOTE: 99.9% of the time, this will not be an issue**, - since there will be no change to
the MET code and METplus image in DockerHub is for setting up its runtime environment,
and the runtime environment does not change with each commit to GitHub. 
So for that 0.1 % of the time, the Travis Build may show failures until the 
DockerHub image has been re-built.

This can be mitigated by having some Travis CI builds on branches run on 
specific cron definitions defined in the Travis CI website configuration ... 
ie. maybe develop branch builds run by cron once a day .... that way
any Docker Hub images will probably have been built. (needs more thought) ...

This can be solved by having Travis CI perform the docker builds within the workflow, instead of Docker pulls. Just change travis yml to build the Docker images.

This also has the potential to have Travis 'deploy:' key, Docker images to Docker Hub
if the build passes, something to consider?

**NOTE Remaining SUBTLE issue and Underlying Assumption:**  is that
the MET Docker image used by METplus is up to date.  Which means, there still exists the potential for the MET image on Docker Hub to also not yet be up to date, if
any changes were committed to the MET repository.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by fentoad72** [comment]
taking over travis from jimfrimel

**Comment by georgemccabe** [comment]
I completed this task with commit 8b240c153921ace55ef723fb56f6c15fbeaae11e with work done to finalize 3.1 release. We determined that while the MET docker build takes a very long time, the METplus docker build is relatively quick since it just pulls the latest MET docker build, installs a few packages/utilities, and sets up the environment. It is worthwhile to always build the docker image instead of pulling it from DockerHub through Travis to ensure that we are using the most up-to-date version of the image.
