### ISSUE TITLE
Tutorial testing on supported platforms

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#468]
The 2020 METplus Tutorial Beta is nearly finished, and will be current when MET 9.0.2 and METplus 3.0.2 are being released as early as Friday.  It's been changed to reflect changes in METplus wrappers and configuration files, with a platform-dependent setup script and "tutorial.conf" (called with master_metplus.py) declaring local directories and paths

## Describe the Task ##
Test the tutorial with on supported machines (NCAR RAL, NOAA Hera/Jet, NCAR Cheyenne, others?).  Check that the commands run and data is output successfully

### Time Estimate ###
1-3 days total, 1-2 hours per platform

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] NCAR Cheyenne
- [x] NOAA Hera
- [ ] NOAA Jet
- [x] RAL Dakota
- [ ] RAL Eyewall
- [ ] RAL Kiowa
- [ ] Other NCAR (please add)
- [ ] Other NOAA (please add)

### Relevant Deadlines ###
* METplus-3.0.2 bug fix*

### Funding Source ###
*NONE.*

### Assignee ###
- [ ] Please add additional scientists/engineers as needed

### Labels ###
- [ ] Training **component(s)**
- [ ] High **priority**
- [ ] No external **requestor(s)**

### Projects and Milestone ###
- [ ] Tutorial
- [ ] METplus-3.0.2 Bugfix

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.

Branch name:  `METplus-3.0.2 bugfix`
- [ ] Complete the task and verify your changes.
- [ ] Add/update documentation.

Pull request: `feature <Issue Number> <Description>`
- [ ] Close this issue.

**Comment by fentoad72** [comment]
Please wait until Tara finishes her review of the Tutorial.

It starts here:  [https://dtcenter.org/metplus-practical-session-guide-2020-beta](https://dtcenter.org/metplus-practical-session-guide-2020-beta)

**Comment by jprestop** [comment]
Should this be tested only with MET 9.0.2 and METplus 3.0.2?  Thanks!

**Comment by fentoad72** [comment]
METplus 3.0.2 contains fixes for MODE, MTD, and also the data patch, so it needs to be that.  (Also can you add the data patch to the global METplus_data directory if it hasn't been done already?  I don't have permission on any of the machines I listed.)

I didn't find any MET issues but I don't know if any of the MET part of the tutorial was changed or if it's using the METplus3.0.2 data patch.  Since they're being released together, I think they should be tested together.

**Comment by jprestop** [comment]
Thanks, Todd.  I will need to get these versions installed on those machines before folks can test with them.  Regarding any new data sets for the new METplus release, I'll take care of that on the new machines when I install the new MET/METplus software after they're released.

**Comment by fentoad72** [comment]
Thanks Julie!  Please let us know when everything's ready

**Comment by fentoad72** [comment]
Closing.  We are on 3.1.  Tutorial materials and videos are being created for the UK Met Office.  I'
