### ISSUE TITLE
Remove jlogger and postmsg

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#470]
We no longer need to use this functionality in METplus and users have set JLOGFILE incorrectly which causes cryptic errors, so we should just remove it from the code.

## Describe the Task ##
From an email from Jim Frimel:

Currently METplus is essentially NOT even using it, at least in the manner intended, so as such there is no
point to keeping what we do have.  
I think I just saw one 'jlogger' and 'postmsg' statement throughout the files and there may be some under the internal_tests ...

FYI ... (Rocoto and ecFlow is and will be used) but using the jlogger is NOT a requirement with a workflow manager.
Currently, Mallory is using ecFlow and Jeff Hamilton is using rocoto  ....  If it ever came to be needed
it can easily be added back in ....

To Remove jlogger ...
Just check ALL the files and make sure to remove jlogfile from ALL the produtil.setup.setup statements
throughout the modules  ...

jlogfile's default value is None ... so these are equivalent ...
produtil.setup.setup(send_dbn=False, jobname='run-METplus',jlogfile=None)
produtil.setup.setup(send_dbn=False, jobname='run-METplus')

However, setting it to None, still outputs any job messages to stderr, (from 'jlogger', or 'postmsg' calls)
so jlogger and postmsg statements need to be removed throughout the METplus files also ...
 
if __name__ == "__main__":
    try:
        # If jobname is not defined, in log it is 'NO-NAME'
        REMOVE if JLOGFILE ....
         if 'JLOGFILE' in os.environ:
            produtil.setup.setup(send_dbn=False, jobname='run-METplus',
                                 jlogfile=os.environ['JLOGFILE'])

         produtil.setup.setup(send_dbn=False, jobname='run-METplus',jlogfile=None)

        -----
        # Also, Either one of these would 'effectively' work ...
        option A
        produtil.setup.setup(send_dbn=False, jobname='run-METplus',jloglevel=logging.CRITICAL)
         -- OR --
        option B
        produtil.setup.setup(send_dbn=False, jobname='run-METplus',jlogfile='/dev/null')

NOTE:
option A
The jloglevel=logging.CRITICAL ... essentially works since it would only send output from
the regular logger (logging.logger.critical ... and we don't use critical ... for the most part ...

option B
The second option ... setting jlogfile='/dev/null') ... sends output to the bit bucket ... 
Which may be ok, but it is OS specific ... but we do use /dev/null in "other" places in the code ...

So one of those two options may be ok ... 
Ultimately we need to remove ALL 'jlogger' calls and/or any 'postmsg' calls (if there are any) ... ... 

Also any of the "other" if __name__ == "__main__": wrappers running stand-alone will
also need this change added ... etc ...

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
This was already completed.
