### ISSUE TITLE
Add additional Branch support to the Travis CI pipeline

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#478]
##  Describe the Task ##

This is a parent Task and is broken into  Sub-issues.
Add additional multi-branch support to the METplus Dockerfile and the Travis yml file.

Currently the Travis CI build runs on the develop branch, feature_ branches
and all pull_requests ..., ADD and define additional branches that you
would like to be able to support, ie. master_v3.0, master_vx.x, bugfix) etc ...
The pipeline should be able to support adding branches as needed.

This issue also addresses the potential 'timing' concern, (when Travis
may pull a image from DockerHub before it has been built, from the
commit trigger).

1. For immediate consideration
Address/confirm and possibly change the current METplus dtcenter/metplus:develop image being built on Docker Hub and used by Travis.

     Should the MET image referenced in the METplus Dockerfile be changed
     to use a different version of the MET Docker Image ?
     Currently it is using MET 9.0 image. 
     FROM dtcenter/met:9.0
     maybe instead use one of these ?
     FROM dtcenter/met:master_v9.0
     FROM dtcenter/met:develop

2. Add support to the METplus Dockerfile to build images based on specific branches.
see: Sub-issues

3. Add Multi branch Support to the Travis yml file.
see: Sub-issues

4. Address Travis CI Build and Docker Hub MET/METplus image build timing.
see: Sub-issues

    Consider:  A fix to the timing concern would be to  have
    travis build the image file instead of pulling it from DockerHub.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] #479  Docker Images
- [x] #480  Travis workflow
- [x] #467  Travis-Docker Hub timing

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
taking over travis from jimfrimel

**Comment by georgemccabe** [comment]
* Travis currently supports develop, feature_\*, master_\*, and bugfix_\*. That should cover the branches we want to trigger a build. Other branch regex can be added to the .travis.yml file.
* The timing concern was address when we changed Travis to build the docker image instead of pulling it from DockerHub (#479)
* Sub-issues #479 and #480 were completed in final preparation of the 3.1 release.
