### ISSUE TITLE
Consider Documenting the METPlus API with sphinx.

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#486]
## Describe the Task ##

Consider Documenting the METPlus API with sphinx.

Last conversation at the Engineering meeting: We were no longer going to do this and instead stay with doxygen ? If that is true, you can probably close this issue.

However, I'm not sure, and therefore just wanted to add this issues as a record.
I thought the plan was to move the METplus script layer to sphinx and keep the produtil package untouched since it is already fully commented, and setup with doxygen and will ultimately be treated as an external repo.

If we are still considering moving the METplus API to  Sphinx ...Do this using Sphinx Autosummary extension and templates.
  
https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html?highlight=autosummary#directive-autosummary

Look at METpy for how they use "templates"

Why use autosummary ?
IDEALLY you don't want to manage and generate the METplus API HTML with the sphinx_apidoc executable. Why? It is an added maintenance layer and burden on the code development process.  It requires managing and updating a set of RST files in the repository, every time there is a change to the scripts that needs documenting. If using Autosummary than, you skip managing and maintaining the interim set of RST generated by sphinx_apidoc.

Side Note inquiry:
How do you add/Integrate RST directly to python scripts ?
Knowing how to do this would be good for everyone to know and it allows added commenting to the METplus scripts that can be leveraged by sphinx, etc ...

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
For 3.1, I added a script called build_docs.py that can be run to build the documentation. This includes calling doxygen to generate the code documentation and copies in those files into _build/html so that it is available on the GitHub.io webpages. Closing the issue, but we can reopen if we eventually decide to use Sphinx to build the code documentation instead (I'm not sure what advantages come with this change).
