### ISSUE TITLE
Revisit and Review the default README badges

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#488]
## Describe the Task ##

Regarding the README.md and the badges discussion we had:
Currently the badges define ONLY the develop branch build info.

Figure out a way to to generalize the README.md so it doesn't have
to be edited specifically for each branch it lives on.

Research and review ...number of projects in GitHub try to do,
with no great success ... and I couldn't find a simple solution at the moment ...

As a NOTE:
The default badge displayed by Travis at the travis NCAR METplus webpage,
is set by default to show the status of the default GitHub  branch, ( which is
currently master_v3.0) and it CAN NOT be changed, it always just shows
the default branch.  So it will continue to display as gray, 
until the master_v3.0 branch has travis and successful testing added or whatever
the default branch is. 
https://travis-ci.org/github/NCAR/METplus 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
taking over travis from Jimfrimel

**Comment by fentoad72** [comment]
change travis-ci.org to travis-ci.com in the URL the badge points to
