### ISSUE TITLE
Add Support for running ALL runnable uses_cases within Travis

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#491]
## Describe the Task ##

Add Support for running ALL /parm/uses_cases (model_applications and met_tool_wrappers) within Travis.

NOTE:
The Majority of this issue is completed by this closed issue SEE: #460 
Consider this new issue as a record of completion and a minor cleanup.
  - [x] Added support for GempakToCF tests and pulling down GempakToCF.jar
  - [x] Added yum -y install java-1.8.0-openjdk to DockerFile
  - [x] Added SUPPORT TO CAPTURE and RETURN EXIT CODES

**ACTION REMAINING:**
The initial Travis setup was using the internal_tests/use_cases/metplus_test_docker.conf  AND internal_tests/use_cases/run_test_use_cases_docker.sh to run a sub sample
of use case tests. **CHECK with @georgemccabe **, but I believe these are now obsolete and can be removed, so they should be ?

Note: Now,  ci/travis_jobs scripts was added and calls internal_tests/use_cases/run_test_use_cases.sh  (note: no _docker in filename.)
as was the original intent (Thank You George) ! 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
taking over travisCI from jimfrimel

**Comment by georgemccabe** [comment]
This work was already completed.
