### ISSUE TITLE
Review, and refactor Travis yml file. 

### ISSUE THREAD

**Issue by jimfrimel** [dtcenter/METplus#493]
## Describe the Task ##

Note: This has been started.  This is really a clean-up and refactor/improvement issue. It will help support and simplify the maintenance of the METplus continuous integration framework that was started.

A ci/travis_jobs directory has been created.

Consider: IDEALLY

**MOVE script commands out of TRAVIS in to their own METplus/ci/travis_jobs  scripts**.  Github #606 

- This will allow easier migration to other CI systems.
- This will simplify maintenance and reduce duplication with
  travis.
- This will make it easier to add tests and extend functionality.
- It will simplify travis.yml
- It just makes more sense to pull stuff out of travis that doesn't
  need to be in Travis !!!!
- restructure directory paths in METplus to support ci
  (This had been discussed w/ John, George)
  METplus/ci
  METplus/ci/docker/Dockerfile  (maybe move docker director to here ?)
  Note: the ci/ directory also follows METpy structure and where the docs
                  version script resides which would be carped and
                  modified for METplus requirements)
  ci/ travis_jobs  (specific scripts called from travis)
    Pull as much of the scripting in the travis yml to the METplus repo
    ie. everything from the curl commands to docker run commands

**Migrate Docker run commands to the METplus ci/travis_jobs scripts/files**. Github #607
- Consider MOVEing complex (if they become complex) docker run commands in to their own file.
- Consider when appropriate that the command passed into docker be in its
  own script rather than have a long complex command...
  ie. **Current:** docker run --rm <blah>..<blah>  /bin/bash -c 'conda activate py3.7;<run tests>; command 3 ...'
  ie. **Instead do this:**  docker run --rm <blah>..<blah>  /bin/bash dockercommand1.sh
      where: dockercommand1.sh
      conda activate py3.7;
      <run tests>;
      command 3 ...'

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] https://github.com/dtcenter/METplus/issues/606 MOVE script commands out of TRAVIS in to their own METplus/ci/travis_jobs script

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
taking over travisCI from jimfrimel

**Comment by georgemccabe** [comment]
Some of this has already been done by me, but there are other tasks that still need to be done. Some other ideas that could be explored:

COMPLETED with #597 - Try to reconcile list of current sample data tarballs so that the information is in 1 place and referenced wherever it needs to be. Currently the tarballs as referenced in ci/travis_jobs/test_use_cases_m* files and internal_tests/docker_data/Dockerfile_data_* files. They should be put into a single file (under ci dir?) and referenced by both.

- Extract common code from scripts called by travis and put them in a common file to be referenced by all so that changes aren't needed in multiple files - this is partially done but could be expanded upon to reduce redundant code

- Move other script commands out of .travis.yml into their own scripts. - i.e. pytest calls

- Clean up .travis.yml file to remove things that may not be necessary
    - Only need 1 version of python
    - Remove stages that aren't needed
    - Remove comments that are unnecessary or no longer relevant
    - Review environment variables used and remove any that aren't needed
    - Determine if jobs/stages need to be under matrix keyword
    - Move before_\*, install, etc. sections above list of stages since they are run first
    - Instead of returning true after docs command, add to allow failures so it is more clear that it is failing and should be fixed

- Move Docker related files out of internal_tests directory and into ci directory. This involves:
    - Moving docker and docker_data directories
    - Updating any travis script that refer to the old paths
    - Updating the DockerHub build rules for dtcenter/metplus and dtcenter/metplus-data to use the new locations
    - Others?

**Comment by fentoad72** [comment]
Created subissues 606 and 607

**Comment by fentoad72** [comment]
gradually being done via subissues and Travis/Docker refinement

**Comment by georgemccabe** [comment]
The .travis.yml file has been cleaned up based on the tasks listed above.
