### ISSUE TITLE
Create Docker image for METplus release

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#498]
We currently have 1 docker image for METplus which is tied to the develop branch. It does not obtain the METplus code because we use Travis to obtain it based on the branch that triggered the build. 

We should create an image for METplus 3.0(.2) that is tied to MET 9.0(.2), obtains the METplus tarball for the release, and installs it (sets conf variables based on docker environment). Once that works, it would be a good next step to create a Docker volume to contain the sample input data and use that in the METplus image to automatically obtain the input data needed for the use cases. Then the use would just need to load the docker image, optionally mount the output directory to their local machine, and run use cases.

Having an image for the releases would allow us to run the test suite via Travis CI on those releases to ensure that any bugfixes do not break anything.

## Describe the New Feature ##
See description above. The following are steps (may be incomplete) to complete this task.
* Checkout the master_v3.0 branch of METplus from GitHub
* Create a feature branch off of master_v3.0 to do the work
* Obtain the internal_tests/docker/Dockerfile from the develop branch and put it in the same location on the feature branch
* Change the first line to pull the latest 9.x.y release of MET instead of develop
* Obtain METplus release and "install it" (see "Add to the Dockerfile")
* Verify that you can use docker to mount local input dir to /data/input, local output dir to /data/output, run a use case, and check if output data exists locally
* Create a docker volume that will contain the sample data for METplus
* Modify the Dockerfile to obtain the data volume and mount it (?) to /data/input so the input data will already be available
* Run use case again using data from docker volume

#### Add to the Dockerfile
* Download tarball of METplus release
* Untar release
* Use sed commands to replace defaults values in parm/metplus_config files:
* MET_INSTALL_DIR to /usr/local
* INPUT_BASE to /data/input
* OUTPUT_BASE to /data/output

### Acceptance Testing ###
Sample data tarballs attached to (or associated with) release

### Time Estimate ###
?
Sub issues are likely necessary

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_498_master_v3.0_docker and feature_498_docker`
- [X] Complete the development and test your changes.
- [X] Add/update unit tests.
- [ ] Add/update documentation.
- [X] Push local changes to GitHub.
- [X] Submit a pull request to merge into **master_v3.0**.
Pull request: `Feature 498 master v3.0 docker #528`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
