### ISSUE TITLE
Enhance StatAnalysis/MakePlots to handle data generated from NetCDF files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#500]
Currently when these 2 wrappers are run together, they generate a specific filename to be read by the plotting scripts. This filename contains level information, which contains commas for NetCDF data as is an invalid filename. These wrappers and plotting scripts should be enhanced to support a filename template as the input for MakePlots so NetCDF data can be used.

## Describe the Enhancement ##
See above

### Time Estimate ###
3-5 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] *Refactor StatAnalysis to isolate (or remove) functionality that run only when MakePlots is in the PROCESS_LIST*
- [x] *Refactor MakePlots wrapper and plotting scripts to allow a template to find the input files instead of using a predetermined path*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
Merged into develop with this PR: https://github.com/NCAR/METplus/pull/525
