### ISSUE TITLE
Review new METplus-3.0.2 tutorial

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#501]
*Replace italics below with details for this issue.*

## Describe the Task ##
Check new Tutorial for mistakes, unclear things

### Time Estimate ###
3 days

### Relevant Deadlines ###
ASAP for Input for METplus training videos

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET]

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Add/update documentation.

- [ ] Close this issue.

**Comment by fentoad72** [comment]
Assigned this to myself

**Comment by fentoad72** [comment]
Changing call order of METplus conf files so tutorial.conf is always called 1st

**Comment by fentoad72** [comment]
On this page: (https://dtcenter.org/metplus-practical-session-guide-version-3-0/session-2-grid-obs/met-tool-pb2nc)
It references a PrepBUFR document: from NOAA dated Feb 2018
http://www.emc.ncep.noaa.gov/mmb/data_processing/prepbufr.doc/document.htm 

The new Bufr page doesn't go into the detail of the 2018 document, but has links that do
https://emc.ncep.noaa.gov/emc/pages/infrastructure/bufrlib.php 
such as
https://emc.ncep.noaa.gov/emc/pages/infrastructure/bufrlib/docs/toc/index.php

Replaced old BUFR document link with new BUFR page link

**Comment by fentoad72** [comment]
Updating MET USERS GUIDE to 9.0.1 on all pages

**Comment by fentoad72** [comment]
Completed through Chapter 5.  Up to date for METplus3.0.2 and MET9.0.1

**Comment by fentoad72** [comment]
After METplus Engineering meeting, replacing links to MET User's Guide 9.0.1 to MET User's Guide 9.0_latest (can update manual without needing to update links every time)

**Comment by fentoad72** [comment]
added how to source /path/to/METplus_Tutorial/TutorialSetup.[machine].sh at the beginning of Chapters 2-5
