### ISSUE TITLE
Change the shebang lines from "#!/usr/bin/env python" to "#!/usr/bin/env python3"

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#503]
## Describe the Task ##
Change the shebang lines from "#!/usr/bin/env python" to "#!/usr/bin/env python3"
Best practice indicates that we should change python shebangs to python3 when Python 3.x is supported.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
METplus-3.1

### Funding Source ###
?

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_503_python3_shebang`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [X] Submit a pull request to merge into **develop**.
Pull request: `Feature 503 python3 shebang #508`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
From email thread: You can still obtain the same functionality as calling a wrapper directly by adding an explicit override of the PROCESS_LIST.

For example, if you have a use case that calls GridStat and StatAnalysis in the PROCESS_LIST, let's call it GridStat_StatAnalysis_together.conf. If you wanted to just call GridStat, previously you could call

grid_stat_wrapper.py -c GridStat_StatAnalysis_together.conf

You can get the same behavior by running:

master_metplus.py -c GridStat_StatAnalysis_together.conf -c config.PROCESS_LIST=GridStat

so we aren't losing that functionality, just losing the ability to directly call the script.

A few reasons others why I think we should make this change:

1. The rearrange of the wrapper and util files to allow METplus to be made into a package causes problems with the imports when trying to run the wrapper file directly. It complains that you are trying to import something that is above the top directory (where the wrappers live). If we really need to support calling the wrapper directly the old way, we would have to change all of the imports to not be relative imports and contain "from metplus.wrappers" or "from metplus.util" before each import.

2. It makes sense to have users only be able to call py files in the ush directory, which is now only master_metplus.py and validate_config.py.

3. I don't think anyone called the wrappers directly before.
