### ISSUE TITLE
Create  an Amazon AMI containing all METplus components.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#506]
## Describe the Task ##
This issue began as a task for creating an AMI for use in METplus tutorial videos.
However, it has evolved into creating a general-purpose AMI for all of the METplus components. Note that it should NOT be based on Docker containers. Instead, install all of the components directly on the AMI. The key task here is writing a highly automated script to make creation of the AMI as easy as possible. If possible, this script should heavily leverage the manage externals infrastructure. It should ultimately live somewhere in the METplus repo.

The AMI should contain...
- a pre-compiled version of MET, built using the compile_all.sh script
- a pre-installed version of METplus
- pre-installed versions of METplotpy, METcalcpy, and METviewer, including the database component locally, Apache and Tomcat
- also consider eventually adding the METdatadb and METexpress components
- any additional Linux utilities required by the METplus tutorial

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2760821 - burning out the funds so please use this key

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
On 12/15/20, DTC engineers met with Stylianos Flampouris to discuss NOAA's needs for a METplus AMI.
They'd like to use a METplus AMI to demonstrate the use and processing of UFS data that's provided by the BigData project on AWS. The timeline for the data to be available on the cloud is unclear.

Goal: Provide METplus AMI no later than the end of January 2021.

Stylianos will coordinate with Ken Sparrow to see if he can setup a development environment within the MDL-net for us to develop this AMI that contains MET, METviewer, METplotpy, METcaclpy, and METplus.

Since this will occur prior to the METplus-4.0 coordinated release, the AMI should be contain the most recent bugfix versions of the METplus-3.1 components.

**Comment by hankenstein2** [comment]
The general task of supplying UFS an EC2 instance with METviewer + all METplus components is done but the creation of a general script is not. Pushing that part to a future release.

**Comment by hankenstein2** [comment]
I need to either choose publishing it under my own account or get added to the DTC account umbrella

**Comment by hankenstein2** [comment]
AMI is finished and published. I need George, John and Keith to test various parts of this before I close the issue. 

There are two items that are not included in the AMI but requested in this issue. No database has been setup and Tomcat has not been configured to run METviewer. I will add separate issues for both of these to do in a future release.

**Comment by hankenstein2** [comment]
This has been tested and is ready. Any further work should go in a new issue.
