### ISSUE TITLE
Enable METplus to only process certain months of a year

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METplus#512]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
Enable METplus to only process certain months out of the year, and then move on to the next year.  For example, only process December, January, and February, skip the other months, and continue on to the next December.  I'm attaching the script below, which regrids data for December, January, February and skips the other months.
[comb.txt](https://github.com/NCAR/METplus/files/4795057/comb.txt)

### Acceptance Testing ###
Any dataset that runs for multiple years.  

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
None

### Relevant Deadlines ###
Needed for the UIUC blocking use case

### Funding Source ###
7705991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_512_skip_months`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [X] Submit a pull request to merge into **develop**.
Pull request: `Feature 512 implemented skip times functionality`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Work done in feature branch: feature_512_skip_months

**Comment by georgemccabe** [comment]
Merged into develop with this PR: https://github.com/NCAR/METplus/pull/519
