### ISSUE TITLE
Create a Feature Relative Use Case with User Diagnostics

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/METplus#522]
## Describe the Enhancement ##
The DTC is working with Brian Colle of Stony Brook University (SBU) to enhance METplus to be able to run use cases with user defined diagnostics, with a specific focus on tropical cyclone analysis. A new feature relative use case is needed that allows a user to use their own python derived diagnostic in the feature relative use case. To do this, the "PyEmbedIngest" tool will be added to the processes that already exist in feature relative use cases. This work was started by Taylor Mandelbaum of SBU and is now being finished by Lindsay Blank of the DTC. 

As of right now, the DTC have only been provided one diagnostic python script that calculates integrated vapor transport (IVT). Therefore, this use case will only perform series analysis based on this diagnostic, although it will be set up to run on more in the future, as they are provided. It will also run for Hurricane Dorian.

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] Get IVT diagnostic python script from Taylor Mandelbaum working.
- [x] Get adeck and bdeck track data for Hurricane Dorian.
- [x] Get forecast and observation model data for Hurricane Dorian
- [x] Set up feature relative use case to run with PyEmbedIngest tool
- [x] Run feature relative use case with PyEmbedIngest tool
- [x] Fix hardcoded paths/variables
- [x] Reconfigure use case for general use
- [x] ExtractTiles improvements

### Relevant Deadlines ###
TBD

### Funding Source ###
Stony Brook University (7791041)

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: George McCabe
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by lindsayrblank** [comment]
**PyEmbedIngest Changes:**
1. Added configurable options: "PY_EMBED_INGEST_{}_OUTPUT_FIELD_NAME" which allows user to specify what they want the output variable to be named
2. Fixed a bug where PyEmbedIngest was only running for the first forecast lead hour.

**ExtractTiles Changes:**
1. Added output file templates (fcst and obs) with support for referencing individual adeck model 
2. Added ability to specify variable name when calling RegridDataPlane ( -name )
3. Removed extra "_" from beginning of level value
4. Fixed a rounding bug in calculation of lat_ll and lon_ll

**SeriesByLead Changes:**
1. Removed extra "_" from beginning of level value
2. Sets input variable name as "name_level"
3. Sorted input files alphabetically so that the correct analysis and forecast files are compared.
