### ISSUE TITLE
Enhance User Diagnostic Feature Relative use case to Run Multiple Diagnostics

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/METplus#536]
## Describe the Enhancement ##
The user diagnostic feature relative use case only runs on one diagnostic. This enhancement will set up the use case to allow users to run this use case on as many diagnostics as they provide. Related to #522 

### Time Estimate ###
2 days

### Sub-Issues ###
- [x] Test user provided diagnostic script (calculates potential vorticity)
- [x] Add PyEmbedIngest commands/configurable options for second diagnostic
- [x] Run use case to make sure it produces statistics for both diagnostics
- [x] Confirm output of new use case matches original output
- [x] Add use case documentation
- [x] Update model data included in tarball to have the variables required to calculate PV.
- [x] Add an image  for the UG.

### Relevant Deadlines ###
NONE

### Funding Source ###
Stony Brook University

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: No engineer required
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
#522 

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
