### ISSUE TITLE
Clean up environment.yml and requirements.txt files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#555]
This has been discussed before but the introduction of a security risk with one of the dependencies that can't be resolved without creating conflicts has elevated this issue.

https://github.com/NCAR/METplus/network/alert/requirements.txt/Pillow/open
_Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update._

Our current environment files include many additional packages that are not required to run METplus. They are used to run tests, build documentation, run plotting scripts, etc. The only actual requirement of the METplus wrappers that does not come standard with python3 is dateutil.

Also, the current environment files are not cross-platform compatible, so it may not work on machines that differ from the environment they were created. There is a conda command that will generate a file that is cross-platform compatible (see 
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-an-environment-file-across-platforms)

## Describe the Enhancement ##
We should replace the existing env files with simple versions and create another environment that can be used for development. This environment can be expanded as needed as more packages are needed, but the files in the top level of the repo should remain as simple as possible.

### Time Estimate ###
1 - 3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] Create a baseline python 3.6.3 environment and install dateutil
- [x] Regenerate environment.yml (conda env export --from-history > environment.yml)
- [x] Regenerate requirements.txt (pip freeze > requirements.txt)
- [x] Replace existing files with the stripped-down versions
- [ ] Recreate an environment that has the packages needed for development, testing, building docs, plot wrappers (? at least for testing these tools until they move out of the METplus repo), etc. 
- [ ] Check that the new environment resolves the Pillow security issue. A branch could be used to set the dev environment files in the top-level to see if the security issue persists.
- [ ] Regenerate environment.yml and requirements.txt files and check them in (under internal_tests?) so they are readily available to developers

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] Consider doing the same for other repositories that use python to simplify the dependencies listed to the users
[METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

- [ ] Consider enhancing METplus wrappers time interval logic to only require dateutil if using time intervals of months or years. These intervals require using dateutil's relativedelta to determine the length of these dynamic intervals. Most use cases in METplus don't use these intervals, in which case datetime's timedelta (comes with baseline python) can be used. This would reduce the dependencies to run METplus wrappers to just python 3.6.3 unless user needs the additional functionality.

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Created pull requests to update environment.yml and requirements.txt for develop and master_v3.0 (delete requirements.txt in master) with changes we discussed in the METplus meeting today. 

Still need to create a conda environment.yml file to use for development and verify that security alert goes away.
