### ISSUE TITLE
Get SNAT to install Travis CLI on Dakota, Kiowa

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#566]
## Describe the Task ##
*Install command-line version of Travis on RAL machines dakota & kiowa *

### Time Estimate ###
*Depends on SNAT (ral-help)*

### Funding Source ###
*2791541*

### Assignee ###
- [Todd Arbetter] Select **engineer(s)** or **no engineer** required
- SNAT: Tor Mohling (rt: 96102)

### Labels ###
- [ mediium] Select **priority**
- [METplus/RAL/UCAR ] Select **requestor(s)**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] Travis CI

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Iterate with SNAT on functionality until it is available to interested users, performs as expected
- [ ] Close this issue.

**Comment by fentoad72** [comment]
Submitted 8/3
8/10 Tor Mohling responded looking for a grant to cover the work; he'd e-mailed Laurie Carson but I suggested Tara Jensen
8/13 Not sure if Tor e-mailed Tara and/or heard back from her; I e-mailed Tara to get the grant number 2791541

**Comment by fentoad72** [comment]
8/24. Tor Mohling let me know the install of Travis CLI is still going on; however there are difficulties in the RAL/SNAT environment.

**Comment by fentoad72** [comment]
Installation completed 8/26.  [Github #584](https://github.com/dtcenter/METplus/issues/584) is about learning Travis CLI
