### ISSUE TITLE
Support METplus to run from a driver script

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METplus#569]
## Describe the New Feature ##
Allow metplus to be run with a driver script and to have all parameters in one file with separate sections for different runs of metplus and for parameters read into the python code of the driver script

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [X] *#510*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [] If other MET components (like the ones listed below) are going to be used in this use case, we should figure out how to call these other tools from the driver script.

[METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_569_driver_config`
- [X] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
The changes for this issue involve modifications to the config get methods so that all variables are considered part of the [config] section while supporting the sections that currently exist ('config', 'dir', 'exe', 'filename_templates', 'regex_pattern', are there any others?). This will make it easier to implement the functionality to override certain variables from the user's additional config sections.
These changes are covered in issue #777
