### ISSUE TITLE
Add all use_cases to automated tests (eg Travis)

### ISSUE THREAD

**Issue by fentoad72** [dtcenter/METplus#571]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
Add support for use_cases that require additional python packages, see #483  

medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_IVT.conf (Q: Lindsay, what package(s) is needed for this?)
met_tool_wrapper/CyclonePlotter/CyclonePlotter.conf (Requires matplotlib and cartopy)

### Time Estimate ###
*3 working days (note: I split time between METplus and UFS)*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [O] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Lindsay's case requires pygrib and metpy to run. Installing metpy is pretty simple (run pip3 install metpy). pygrib was a little trickier, but I was able to install it using the following commands:

yum -y install eccodes-devel
pip3 install numpy
pip3 install pyproj
pip3 install eccodes-python
pip3 install pygrib

numpy was already installed in Docker since it is required to install MET, but I left it in these instructions in case we change the environment.

**Comment by fentoad72** [comment]
Add new job in test_use_cases_model_applications.sh independent of medium_range1 and medium_range2

**Comment by fentoad72** [comment]
Didn't we do a PR on this to merge with develop?  I can't see it here.  I think this issue is closed?

**Comment by georgemccabe** [comment]
@fentoad72 I just linked the 2 pull requests that are related to this issue. I am closing the issue now.
