### ISSUE TITLE
Move METplus repository from the NCAR to DTCenter organization.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#573]
## Describe the Task ##

Move the METplus repository from the NCAR organization to the DTCenter organization. Make 3 changes:
- change github.com/NCAR to github.com/dtcenter
- change ncar.github.io to dtcenter.github.io
- rename METdb to METdatadb

These changes should be made to both the develop and master_v3.1 branches.

After the documentation updates are complete, re-push the METplus 3.1 documentation from master_v3.1 to the gh-pages branch.

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
This change does not affect the other repositories, but similar changes will be required in those repos.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
There are many, many files to be updated here!

```
egrep -l "github.com/NCAR|ncar.github.io|METdb" `find ./ -type f` | sort -u

.//.github/ISSUE_TEMPLATE/bug_report.md
.//.github/ISSUE_TEMPLATE/enhancement_request.md
.//.github/ISSUE_TEMPLATE/new_feature_request.md
.//.github/ISSUE_TEMPLATE/task.md
.//README.md
.//build_components/Externals.cfg
.//ci/travis_jobs/test_use_cases_met_tool_wrapper.sh
.//ci/travis_jobs/test_use_cases_model_applications.sh
.//docs/Contributors_Guide/documentation.rst
.//docs/Contributors_Guide/github_workflow.rst
.//docs/README.md
.//docs/Users_Guide/index.rst
.//docs/Users_Guide/installation.rst
.//docs/Users_Guide/quicksearch.rst
.//docs/Users_Guide/release-notes.rst
.//docs/Users_Guide/systemconfiguration.rst
.//docs/doxygen/README_install.md
.//docs/doxygen/confguide.dox
.//docs/doxygen/install-main.dox
.//docs/doxygen/install.dox
.//docs/doxygen/mainpage.dox
.//docs/doxygen/metplus-conf.dox
.//docs/doxygen/metplus_data_conf.dox
.//docs/doxygen/metplus_runtime_conf.dox
.//docs/doxygen/metplus_system_conf.dox
.//docs/doxygen/overview.dox
.//docs/doxygen/run.dox
.//docs/doxygen/running_cli.dox
.//docs/index.rst
.//docs/use_cases/met_tool_wrapper/ASCII2NC/ASCII2NC.py
.//docs/use_cases/met_tool_wrapper/ASCII2NC/ASCII2NC_python_embedding.py
.//docs/use_cases/met_tool_wrapper/ASCII2NC/ASCII2NC_python_embedding_user_py.py
.//docs/use_cases/met_tool_wrapper/CyclonePlotter/CyclonePlotter.py
.//docs/use_cases/met_tool_wrapper/EnsembleStat/EnsembleStat.py
.//docs/use_cases/met_tool_wrapper/EnsembleStat/EnsembleStat_python_embedding.py
.//docs/use_cases/met_tool_wrapper/Example/Example.py
.//docs/use_cases/met_tool_wrapper/GempakToCF/GempakToCF.py
.//docs/use_cases/met_tool_wrapper/GenVxMask/GenVxMask.py
.//docs/use_cases/met_tool_wrapper/GenVxMask/GenVxMask_multiple.py
.//docs/use_cases/met_tool_wrapper/GenVxMask/GenVxMask_with_arguments.py
.//docs/use_cases/met_tool_wrapper/GridDiag/GridDiag.py
.//docs/use_cases/met_tool_wrapper/GridStat/GridStat.py
.//docs/use_cases/met_tool_wrapper/GridStat/GridStat_multiple_config_files.py
.//docs/use_cases/met_tool_wrapper/MODE/MODE.py
.//docs/use_cases/met_tool_wrapper/MTD/MTD.py
.//docs/use_cases/met_tool_wrapper/MTD/MTD_python_embedding.py
.//docs/use_cases/met_tool_wrapper/PB2NC/PB2NC.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_add.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_bucket.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_derive.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_loop_custom.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_python_embedding.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_subtract.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_sum.py
.//docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_user_defined.py
.//docs/use_cases/met_tool_wrapper/Point2Grid/Point2Grid.py
.//docs/use_cases/met_tool_wrapper/PointStat/PointStat.py
.//docs/use_cases/met_tool_wrapper/PointStat/PointStat_once_per_field.py
.//docs/use_cases/met_tool_wrapper/PyEmbedIngest/PyEmbedIngest.py
.//docs/use_cases/met_tool_wrapper/RegridDataPlane/RegridDataPlane.py
.//docs/use_cases/met_tool_wrapper/RegridDataPlane/RegridDataPlane_multi_field_multi_file.py
.//docs/use_cases/met_tool_wrapper/RegridDataPlane/RegridDataPlane_multi_field_one_file.py
.//docs/use_cases/met_tool_wrapper/RegridDataPlane/RegridDataPlane_python_embedding.py
.//docs/use_cases/met_tool_wrapper/SeriesAnalysis/SeriesAnalysis.py
.//docs/use_cases/met_tool_wrapper/SeriesAnalysis/SeriesAnalysis_python_embedding.py
.//docs/use_cases/met_tool_wrapper/StatAnalysis/StatAnalysis.py
.//docs/use_cases/met_tool_wrapper/StatAnalysis/StatAnalysis_python_embedding.py
.//docs/use_cases/met_tool_wrapper/TCGen/TCGen.py
.//docs/use_cases/met_tool_wrapper/TCMPRPlotter/TCMPRPlotter.py
.//docs/use_cases/met_tool_wrapper/TCPairs/TCPairs_extra_tropical.py
.//docs/use_cases/met_tool_wrapper/TCPairs/TCPairs_tropical.py
.//docs/use_cases/met_tool_wrapper/TCRMW/TCRMW.py
.//docs/use_cases/met_tool_wrapper/TCStat/TCStat.py
.//docs/use_cases/model_applications/climate/GridStat_fcstCESM_obsGFS_ConusTemp.py
.//docs/use_cases/model_applications/climate/MODE_fcstCESM_obsGPCP_AsianMonsoonPrecip.py
.//docs/use_cases/model_applications/convection_allowing_models/EnsembleStat_fcstHRRRE_obsHRRRE_Sfc_MultiField.py
.//docs/use_cases/model_applications/convection_allowing_models/GridStat_fcstHRRR_obsPracPerfect_SurrogateSevere.py
.//docs/use_cases/model_applications/convection_allowing_models/GridStat_fcstHRRR_obsPracPerfect_SurrogateSevereProb.py
.//docs/use_cases/model_applications/convection_allowing_models/MODE_fcstHRRR_obsMRMS_Hail_GRIB2.py
.//docs/use_cases/model_applications/convection_allowing_models/Point2Grid_obsLSR_ObsOnly_PracticallyPerfect.py
.//docs/use_cases/model_applications/cryosphere/GridStat_MODE_fcstIMS_obsNCEP_sea_ice.py
.//docs/use_cases/model_applications/medium_range/GridStat_fcstGFS_obsGFS_Sfc_MultiField.py
.//docs/use_cases/model_applications/medium_range/GridStat_fcstGFS_obsGFS_climoNCEP_MultiField.py
.//docs/use_cases/model_applications/medium_range/PointStat_fcstGFS_obsGDAS_UpperAir_MultiField_PrepBufr.py
.//docs/use_cases/model_applications/medium_range/PointStat_fcstGFS_obsNAM_Sfc_MultiField_PrepBufr.py
.//docs/use_cases/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByInit.py
.//docs/use_cases/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead.py
.//docs/use_cases/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_IVT.py
.//docs/use_cases/model_applications/precipitation/EnsembleStat_fcstHRRRE_FcstOnly_NetCDF.py
.//docs/use_cases/model_applications/precipitation/GridStat_fcstGFS_obsCCPA_GRIB.py
.//docs/use_cases/model_applications/precipitation/GridStat_fcstHREFmean_obsStgIV_Gempak.py
.//docs/use_cases/model_applications/precipitation/GridStat_fcstHREFmean_obsStgIV_NetCDF.py
.//docs/use_cases/model_applications/precipitation/GridStat_fcstHRRR-TLE_obsStgIV_GRIB.py
.//docs/use_cases/model_applications/precipitation/MTD_fcstHRRR-TLE_FcstOnly_RevisionSeries_GRIB.py
.//docs/use_cases/model_applications/precipitation/MTD_fcstHRRR-TLE_obsMRMS.py
.//docs/use_cases/model_applications/s2s/GridStat_SeriesAnalysis_fcstNMME_obsCPC_seasonal_forecast.py
.//docs/use_cases/model_applications/space_weather/GenVxMask_fcstGloTEC_FcstOnly_solar_altitude.py
.//docs/use_cases/model_applications/space_weather/GridStat_fcstGloTEC_obsGloTEC_vx7.py
.//docs/use_cases/model_applications/tc_and_extra_tc/Plotter_fcstGFS_obsGFS_ExtraTC.py
.//docs/use_cases/model_applications/tc_and_extra_tc/Plotter_fcstGFS_obsGFS_RPlotting.py
.//docs/use_cases/model_applications/tc_and_extra_tc/TCRMW_fcstGFS_fcstOnly_gonzalo.py
.//internal_tests/docker/Dockerfile
.//internal_tests/docker_data/Dockerfile_data_convection_allowing_models
.//internal_tests/docker_data/Dockerfile_data_medium_range
.//internal_tests/docker_data/Dockerfile_data_met_tool_wrapper
```
