### ISSUE TITLE
Filename templates that have other arguments besides a filename for python embedding fails

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#581]
@j-opatz brought this to attention. His use case had a template with additional arguments to pass to his python embedding script via MET_PYTHON_INPUT_ARG:

```
...
FCST_VAR1_NAME = /d1/projects/nrl_aerosol/forecast_embedded.py MET_PYTHON_INPUT_ARG
...
FCST_MTD_INPUT_DATATYPE = PYTHON_NUMPY
...
FCST_MTD_INPUT_TEMPLATE=
   /d1/projects/nrl_aerosol/input/icap_{init?fmt=%Y%m%d}00_aod.nc:total_aod:{valid?fmt=%Y%m%d%H%M}:0,
   /d1/projects/nrl_aerosol/input/icap_{init?fmt=%Y%m%d}00_aod.nc:total_aod:{valid?fmt=%Y%m%d%H%M}:1
...
```

## Describe the Enhancement ##
Added a check if the data type is set and it contains PYTHON in the text. If it does, then return the full path without checking if the file exists. This allows the text to contain other arguments that can be passed to the python embedding script.

### Time Estimate ###
2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above.
- [X] Fork this repository or create a branch of **develop**.
Branch name:  `feature_581_mtd_py_embed_error`
- [X] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
