### ISSUE TITLE
Learn how to use Travis CLI

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#584]
I assigned many people to this task in case anyone is already familiar or knows someone who is.

Travis command line interface is now installed on some of the NCAR machines. We need to learn how to use it, particularly how to run Travis jobs locally instead of relying on Travis-CI's web interface to debug issues.

## Describe the Task ##
If someone we know already knows how to use this tool, we should ask for a demo. If not, someone should research how to use the tool and create a demo to share with the other team members.

### Time Estimate ###
?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by fentoad72** [comment]
Read over Travis CLI summary of commands. Travis CLI lint looks promising, but not sure what the other commands provide in functionality over Travis CI web interface.  In search of a Travis CLI tutorial.  It would be nice if CLI could be used for debugging; currently we have to write an interactive bash script and set environment variables, but unlike real-world, datasets do not persist within Travis world, at least not in recent experience with [Github #597 ], which is disappointing (https://github.com/dtcenter/METplus/issues/597)

**Comment by fentoad72** [comment]
There is not a lot of documentation or tutorial material out there, which makes me think this is still pretty new.  Recommend keeping open and watching for new material.  Most of what is done is through the web interface.  Linting files is one thing that might be done with CLI, but I don't have it on apostrophe where I do my work

**Comment by fentoad72** [comment]
update with info on how I used travis log to pull builds and check timing flags

**Comment by fentoad72** [comment]
We are migrating from Travis CI/CLI to Github Actions; this issue is no longer relevant (closing)
