### ISSUE TITLE
Decouple PCPCombine, RegridDataPlane, and GridStat wrappers behavior

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#602]
Currently the behavior of RegridDataPlane and GridStat differ depending on if [FCST/OBS]_PCP_COMBINE_RUN is set to True. This is due to supporting legacy configuration where [FCST/OBS]_VAR1_[NAME/LEVELS] is used to control PCPCombine output accumulation, RegridDataPlane input and output names, and GridStat input name.

## Describe the Enhancement ##
PCPCombine and RegridDataPlane should be forced to use explicit values for input accum, input name, output name, etc. to remove the problematic logic that makes a lot of assumptions about the workflow. We will need to be sure that users that are using the old approach receive useful log errors to make it clear what should change in their config to avoid frustration.

### Time Estimate ###
3+ days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] *Remove logic that uses _PCP_COMBINE_RUN from PCPCombine and RegridDataPlane*
- [x] *Determine if required updates to config files can be automated via validate_config.py scripting*
- [x] *Update User's Guide instructions with details on how to update*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
Working in branch: feature_602_decouple_wrappers

Adding the python netCDF4 package allows the wrappers to check if an input file is a MET-generated NetCDF file. If it is and the _VAR<n>_LEVELS value is in GRIB format, then we can reformat the name/level values. This allows old config files to still work but removes the problematic behavior so more complex use cases can still be configured.

I also added warning messages when a value for PCPCombine or RegridDataPlane is pulled from [FCST_OBS]_VAR<n>_ variables so that it is clear what is being used and how you can reconfigure the config files to use explicit variables to configure each wrapper.

I still need to:
- get Brian's use case working
- Add tests for met_util.is_met_netcdf function
- Update requirements.txt and environment.yml files to include new python dependencies (netCDF4 which requires numpy, cftime, and six)

**Comment by georgemccabe** [comment]
Update: Brian's use case is now working.

**Comment by georgemccabe** [comment]
I decided to remove the netCDF4 dependency. The behavior was different depending if the package is available or not, so it was not a safe solution. Instead, I removed the logic that changes the output field name to {name}_{level} altogether. The user can update their config file to specify the output field name if they prefer that name.
