### ISSUE TITLE
Update METplus data container logic to pull tarballs from dtcenter.org instead of GitHub release assets.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#613]
## Describe the Enhancement ##
In issue #589, we added logic in the internal_tests/docker_data to prepare Docker data volumes for each of the 9 existing test data tarballs. The build_docker_images.sh script pull tarballs from the release page assets of DockerHub, converts them into data containers, and optionally, pushes them to DockerHub. Those data containers are then pulled and used by TravisCI.

This task it to improve, and when possible, automate these steps.
- Update the script to pull the tarfiles from https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/
- Configure dtcenter/metplus-data on DockerHub to watch the docker-data directory.
- Add a hooks/build file to define how the data images should be rebuilt... by calling the updated build_images.sh script.
- Define automated build rules on DockerHub so that newly created METplus versions cause Docker data volumes to AUTOMATICALLY be created.
- We'd also like to have a "develop" version of these data volumes... but we don't want them to be automatically rebuilt. See if there's an easy way to manually trigger a rebuild.
- Update the contributors guide with instructions for how to submit/accept data for new use cases. It's the PR reviewer's job to accept and organize new input data. They also need to make sure that the new data is as small as possible.

### Time Estimate ###
1 day.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No anticipated impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
