### ISSUE TITLE
Integrate GFDL tracker into METplus framework using manage_externals

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplus#614]
## Describe the New Feature ##
Several projects are dependent on having Adecks from the GFDL tracker and there's a deliverable in the StonyBrook project to integrate a tracker into METplus.  The first step is to use manage externals to make it easy for users to grab the component and compile.

### Acceptance Testing ###
GFDL tracker able to be pulled from SVN repository and compiled

### Time Estimate ###
About 10 hours

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
beta_1

### Funding Source ###
2785041 - 10 hours
7791041 - 10 hours
7790971 - 10 hours
2790541 - if more is needed

### Assignee ###
- [ x] Select **engineer(s)** or **no engineer** required
- [x ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ x] Select **component(s)**
- [x ] Select **priority**
- [x ] Select **requestor(s)**

### Projects and Milestone ###
- [x ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
