### ISSUE TITLE
Add stage to Travis to update or create data volumes when new sample data is available

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#633]
Full notes here: https://docs.google.com/document/d/1aiXzap39K2pU2WQB3VAkJnlNN1WKVOixpcZdhEUYe2Y/edit#heading=h.skvq0sd9rdg8

## Describe the Enhancement ##
Compare last modified time of tarfiles hosted on web server.
Check if docker data volume already exists
If it exists, compare creation time to tarfiles to determine if they need to be rebuilt.
If it doesn't exist, create the data volumes
Push the new volumes

### Time Estimate ###
3+ days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Write scripts to check times on web and DockerHub*
- [ ] *Set up credentials to push to DockerHub*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Changes in feature_633_travis_prepare_new_data were merged into feature_625_stat_analysis (#625) and modified to work out bugs.
