### ISSUE TITLE
Enhance the build_docker_images.sh script to support TravisCI updates.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#636]
## Describe the Enhancement ##
The METplus team is overhauling the logic for preparing input datasets for continuous integration testing with Travis. That overhaul is described in this Google Doc:
https://docs.google.com/document/d/1aiXzap39K2pU2WQB3VAkJnlNN1WKVOixpcZdhEUYe2Y/edit

Listed below are the specific changes related to the build_docker_images.sh script.

- [x] (1) Enhance build_docker_images.sh to support the following usage statement:
```
Usage: build_docker_images.sh
        -pull version
        [-dataset list]
        [-union]
        [-push repo]

        where:
          "-pull version" defines the version of the datasets to be pulled (required).
          "-dataset list" overrides the use of all datasets for this version with a comma-separated list (optional).
          "-union" also creates one data volume with all datasets for this version (optional).
          "-push repo" pushes the images to the specified DockerHub repository (optional).

  e.g. Pull from https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/<version>
       Push to DockerHub <repo>:<version>-<dataset>
```
- [x] (2) Delete the metplus_sample_data ascii file.
- [x] (3) Use “curl” to get a list of tarfiles to be processed for the requested version.
```
curl -s https://dtcenter.ucar.edu/dfiles/code/METplus/METplus_Data/develop/ | tr "<>" "\n" | grep sample_data | egrep -v href
```
Make sure to ignore the optional "-version" at the end of the tarfile name.
- [x] (4) Enhance the Dockerfile to search for a hidden ".VOLUME" file which specifies the directory that should be used as the VOLUME mount. 
- [x] (5) Update each existing tarfile by adding a hidden file named “.VOLUME” in the directory that should be mounted in the Dockerfile, i.e. model_applications/<category>/.VOLUME
Enhance that script to find the hidden “.VOLUME” file and define that directory as the mount point.
- [x] (6) Change ${MOUNTPT} from being a required Dockerfile argument to optional. If supplied (as in the union of tarfiles), use it. If not, find .VOLUME in the tarfile. If not found, exit with a useful error message.
- [x] (7) Update the build hooks files to run:
```
./build_docker_images.sh -pull $SOURCE_BRANCH -union -push dtcenter/metplus-data
```
- [x] (8) Update the DockerHub automated builds for dtcenter/metplus-data to ONLY build tagged version numbers, not the develop branch. Also delete the dtcenter/metplus-data:develop* images since the develop images will now live in metplus-data-dev.
- [x] (9) On mohawk, double-check to ensure that all version directories contain a full listing of tarfiles or links for all required input datasets.

### Time Estimate ###
2 days.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] #648 Reorganize use case tests so users can add new cases easily

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John HG
- [X] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
METplus #633 updates the TravisCI logic. These changes should be coordinate with those. No impacts to other repos.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Did the majority of this work on Friday, 9/25. Will test by running the script locally in the following ways to push images for develop and v3.1:
```
./build_docker_images.sh -pull develop -push dtcenter/metplus-data-dev
./build_docker_images.sh -pull v3.1 -union -push dtcenter/metplus-data
./build_docker_images.sh -pull v3.0 -union -push dtcenter/metplus-data
```

**Comment by JohnHalleyGotway** [comment]
The initial logic was not sufficient for defining VOLUME mount points correctly. So George and I brainstormed a solution... have a single file each <version> directory listing the mount points for each dataset. That change has been implemented and now works well.

**Comment by georgemccabe** [comment]
The changes related to this issue were merged into develop via PR #637 and additional changes mentioned in @JohnHalleyGotway 's last comment are included in PR #638

**Comment by JohnHalleyGotway** [comment]
Handing this issue over to George now for him to work on documentation. He'll migrate the instructions over from the Google Doc (https://docs.google.com/document/d/1aiXzap39K2pU2WQB3VAkJnlNN1WKVOixpcZdhEUYe2Y/edit) to the METplus contributor's guide.

**Comment by JohnHalleyGotway** [comment]
I reviewed George's documentation at this URL:
http://icculus.rap.ucar.edu/metplus-test3/Contributors_Guide/add_use_case.html

Overall looks very good. Here's some recommended tweaks.

- We should probably list something other than "Tara Jensen" for adding a new category. I would say to write met_help@ucar.edu, but that'll be replaced this year with a forum. So I'm not sure what to say there now.

- "the MET tool that performs the final analysis" is a bit confusing. Recommend replacing with "the MET tool that performs the primary statistical analysis". Otherwise, anything calling Stat-Analysis last would need be named as such... or is that what's intended?

- Replace "You can copy an existing documentation file and modify it to describe the new use case." with "Users are encouraged to copy...".

- Replace "Update list of run times" to "Update the list of run times"

- Re: "Make sure to build the documentation...". I do not think we should REQUIRE that people submitting be able to rebuild the Sphinx docs. Instead, say something like "If possible, users are encouraged to rebuild the documentation...". And actually, "Build the docs" should probably be a new section.

- So break 8.3 down into 3 sub-sections: 8.3.1 configure new use case, 8.3.2 document new use case, 8.3.3 build the use case docs (or something like that).

- Replace "paired down" with "pared down". Optional to provide an example of subsetting a GRIB2 file using wgrib2:
```
wgrib2 file.grib2 | grep TMP | wgrib2 -i file.grib2 -grib_out subset.grib2
```

- In 8.4.1, you reference met_test but plan to move that to a new location. This would be easier to forget to correct later.

- Replace "access to mohawk" with "access to the internal DTC web-server (currently, mohawk)".

- Update section 8.4.2 to indicate that the instructions are for developers with direct access to the internal DTC web-server. And a couple years from now it'll no longer be named mohawk... so minimize specific references that'll need to be changed later (or more likely, we'll forget to).

- In 8.4.2(and throughout) consider replacing "feature_XYZ" with "<feature branch>" to make sure we don't end up with directories literally named feature_XYZ. 

- In 8.4.3, replace "<category>-X.Y.tgz with "<category>-<version>.tgz". And say, where "<version>" is the METplus version number for which this use case is being added.

- In 8.4.8, clarify who's job this is. The person submitting the PR or the person who approved the PR? If it's different for internal vs external developers, state that fact.

**Comment by georgemccabe** [comment]
I made the changes listed above and reworked some of the instructions to use environment variables to make running the commands easier.

**Comment by georgemccabe** [comment]
PR #652 was submitted to resolve #648. Once these changes are merged, we can close this issue.

**Comment by georgemccabe** [comment]
Sub-issue was closed, so we can close this issue.
