### ISSUE TITLE
New Use Case: Feature Relative using MTD output for feature centroid lat/lon

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplus#641]
## Describe the Enhancement ##
Currently the Feature Relative use-cases identify the location of the feature from output from the GFDL tracker.  The SBU and UW-CIMSS projects would also like to have support for MTD centroid lat/lon.  I think we need to discuss if this can be handled in the python script that provides lat/lons to the script that cuts out the tile prior to passing into Series-Analysis, or if it requires modifications  to TC-pairs/TC-stat to allow for further refinement.    

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
December 2020

### Funding Source ###

7791041

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
The ExtractTiles wrapper (and optionally the SeriesAnalysis wrapper) reads a TCStat output file to get a list of storms and the lat/lon points along the track. The wrappers could be modified to read a MTD output file to parse out the lat/lon points from the appropriate columns. However, we will need to determine how to group these points.

**Comment by JohnHalleyGotway** [comment]
Here's some recommended logic for implementing this functionality in METplus. Please see this file to illustrate: 
[mtd_BASIC_20100517_010000V_2d.txt](https://github.com/dtcenter/METplus/files/6594477/mtd_BASIC_20100517_010000V_2d.txt)

The task here is to run Series-Analysis once for each pair of fcst/obs MTD space-time objects. So we need to construct a list of times along with fcst_lat, fcst_lon and obs_lat, obs_lon locations. This can be done by processing MTD files ending with _2d.txt. The rest of the MTD output files can be ignored.

1. First, figure out how many fcst/obs MTD object pairs there are to process by processing the "OBJECT_CAT" column. They contain values of "CF###" or "CO###". The maximum value of those ### indicates the number of series there are to process. If they are all 000, then there is no work to do.
2. Loop through the series of object numbers (001, 002, and so on), and for each...
3. Store the forecast locations by retrieving the the "CENTROID_LAT" and "CENTROID_LON" columns from the lines where "OBJECT_ID = CF###" (where ### is the current number).
4. Store the observations locations by retrieving the the "CENTROID_LAT" and "CENTROID_LON" columns from the lines where "OBJECT_ID = CO###" (where ### is the current number).

So for each timestep, we're storing the location of the centroid for the 2D cluster object of the forecast and the observation. My only question is whether or not the number of these time slices can differ. In the attached example, they correspond 1-to-1, but it seems conceivable to me that one could begin/end earlier/later than the other, making it so that the timesteps don't exactly correspond.

**Comment by DanielAdriaansen** [comment]
We will need to utilize the work in #968 to enhance existing feature relative use cases, but I'm not sure which ones those are. @TaraJensen may be able to help. We can either leave this issue open, or close it and open new issues for enhancing the use cases.

**Comment by georgemccabe** [comment]
Closed with #1153
