### ISSUE TITLE
Fix errors in METplus Documentation

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#644]
Running doc8 on the rst files reports many errors. We should clean up these errors.

## Describe the Task ##
Make doc8 happy. Most of the errors involve whitespace at the end of the line or lines that are too long. Work in a feature branch (feature_644_doc_errors) and check the Travis CI webpage to see if the errors have been resolved. When they are all resolved, the red X will change to a green check mark. The log files of the Travis builds show the list of errors.

When you are done, we need to remember to uncomment the "allow_failures" section in the .travis.yml file so that future failures of the documentation does not prevent other jobs from running.

### Time Estimate ###
3 days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
Ask Tara

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_644_doc_errors`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Putting the "line too long" issues on hold for now due to funding and hoping to find an automated solution.   doc8 complains if <=79 characters.

John HG suggested potentially using "fmt" (see below), however, George noted that formatting in Sphinx can be verify specific, especially with literals, so it would need some clean up.  There are potentially other ways to solve these issues, but we are not going to explore them right now.

NAME
       fmt - simple optimal text formatter
SYNOPSIS
       fmt [-WIDTH] [OPTION]... [FILE]...
DESCRIPTION
       Reformat each paragraph in the FILE(s), writing to standard output.  The option -WIDTH is an abbreviated form of --width=DIGITS.

**Comment by georgemccabe** [comment]
Lisa made all of the changes to resolve the errors except for the 'line too long' errors, which we have set to ignore. We moved this issue to the 4.0-beta2 project so we can discuss if we want to resolve the remaining errors or just resolve this issue.

**Comment by jprestop** [comment]
We discussed this issue at a meeting a few weeks ago.  Tara mentioned that documentation has gone over budget. It was said that we would not tackle this now, but at some point in the future we would revisit and decide if it was something we wanted to do when we had more funding for this task.  We discussed having Lisa do this task or trying to do it with a script, but noted that Sphinx has some subtleties that may not be handled well by a script.  Updating notes here so that we will remember for future meetings when we go over issues.

**Comment by jprestop** [comment]
Lisa took a thousand line file to add return lines to keep the characters under 79 per line and timed it to see how long it might take for her to do this work manually, as we suspect that Sphinx has some subtleties that may not be handled well by a script in doing this work.  She said she thought that a half hour seemed like a reasonable ball park estimate.  She noted, however, that the document she chose, METplus/docs/Users_Guide/systemconfiguration.rst, had a lot of formatting issues.  She corrected those as she went.  But, at the end, she reran 'make clean html' and had a bunch of new errors to contend with.  She fixed them all but that took another half hour.  She thought it was important to note this will take more time on incorrectly formatted files.

**Comment by georgemccabe** [comment]
While reviewing PR #826 @fisherhucar noticed that there are use case doc files (in docs/use_cases) that have lines that are very, very long. Those files likely don't show up in the errors from this issue, but if we decide to modify the doc files to limit the length of each line, we should review those files as well.

**Comment by georgemccabe** [comment]
Not completing. We have other documentation error/warning checking via GitHub Actions that is not as strict as doc8. If we decide we want to clean up the documentation files to avoid going over the max line length that doc8 complained about, we can create a new issue to handle that task.
