### ISSUE TITLE
Add a section to the METplus User's Guide about what questions to ask when applying METplus to a new testing and evaluation project. 

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#650]
## Describe the Enhancement ##
This idea arose during the METplus telecon with the UK MetOffice on 10/12/2020.
Over the years, we have applied MET, and now the METplus wrappers, to many testing and evaluation projects. And for each new application, we tend to ask a similar set of questions. A sample set of those questions is listed below. For users new to METplus or new to verification in general, the questions that should be considered may not be obvious.

This task to survey the current set of METplus developers and users and document the relevant questions. Specifically, these are the questions to be asked when setting applying METplus to a new testing and evaluation project, which may consist of one or more use cases. Organize the feedback into a new section (full chapter or sub-section of existing chapter?) of the METplus User's Guide with clear, consistent, and practical advice to users. Care should be taken to ensure the questions are scientifically relevant but specific enough to be actionable in a METplus configuration file.

Recommend that after each question, we provide some practical suggestions based on possible answers to that question. So, how will the answer to this question impact the user's METplus configuration file or files?

Sample questions include (PLEASE ADD TO THIS LIST):
- What are the questions you are trying to answer with this testing and evaluation project?
- How should the testing and evaluation project be broken down into METplus Use Cases? One large one or multiple smaller ones?
- How will METplus be run? Manually? Scheduled, through cron? Automated via a workflow manger (e.g. Rocoto, EC-Flow, Rose-Cylc)?
- Where will METplus be run? Local machine, project machine, HPC system, in the cloud (e.g. AWS)? Serial runs or parallelized?
- What is the evaluation time period? Retrospective with specific dates? Ongoing, near-realtime evaluation? Or both retrospective and realtime?
- What is the geographic location of the model data being evaluated?
- What observation or analysis datasets are available during this time period and which correspond to the model location? Is the verifying data point-based, gridded, or both?
- Do you want to evaluate on the model domain, observation domain (if gridded), or some other domain?
- ADD NEW QUESTIONS HERE.
- Can you please create a graphical flow chart for quick reference and for visual learners?

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2771021

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by TaraJensen** [comment]
[Here is a draft document.](https://docs.google.com/document/d/1Xv7RMLP59iE8pZFuD6kU-S4_iEnfPzCpBxT5TbFMvSM/edit#heading=h.ajee65jnq8p3)  It may not be mature enough or in time to include in METplus v4.1.0 release notes but at least we have a starting point.
