### ISSUE TITLE
Add a new document for METplus to inventory verification datasets for MET and METplus.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#662]
## Describe the Enhancement ##
This task relates to the 2019 Air Force datasets project for which we had a kickoff meeting on 10/14/21.

This task consists of the following steps:
- Add a new METplus document to describe input verification datasets (e.g. point observations, gridded verifying analyses, and gridded forecast products).
- Develop a template that can be used to describe each dataset. For that template, consider including:<br/>
description, type (point vs grid), file format, date, availability (public/private), scientific motivation for use in vx, pointer to python embedding scripts
- Ideally each dataset would be demonstrated by a METplus use case, and the template would point to that use case example.
- If that's not possible, then at least create an example of plotting the data through METplus. But where should that sample python script and input file live?
- Survey the DTC testing and evaluation projects as widely as possible to capture as many datasets as are feasible.
- Update the existing directions for "adding a new use case" to instruct developers to check/update this new document with novel datasets.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
Merging in initial version for METplus version 4.0.0-beta2, but created a separate METplus #715 issue to develop additional content.

### Relevant Deadlines ###
The funding for this task ends at the end of January 2021.
This work should be completed by the METplus-4.0-beta3 release, which is tentatively scheduled for 1/18/21.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Michelle Harrold to review PR.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
None.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
At the 10/29/2020 METplus meeting, we decided to organize this content into a new METplus document instead of an appendix to the METplus User's Guide. I update the title/body of this issue accordingly.
