### ISSUE TITLE
Internal: Consider automating some steps from Release Guide

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#665]
Note: This issue previously involved auto-updating the release date with an argument to the docs/build_docs.py script. However, we no longer use this script in favor of ReadTheDocs building the documentation, so I reopened the issue to be more general for automating release instructions.

Currently we have to update the release date and version number that is read by docs/conf.py by hand. It would be nice to automate this and other steps.

## Describe the Enhancement ##
Implement a GitHub Actions Workflow to trigger on a specific branch (release_vX.Y.Z?) and perform some of the steps from the Release Guide that involve changing content that is specific to a release and should not be made in the develop branch.

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider doing something similar for the other repositories
- [x] [MET](https://github.com/dtcenter/MET/issues/new/choose)
- [x] [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose)
- [x] [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose)
- [x] [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose)
- [x] [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose)
- [x] [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
Adding the following line to the docs/conf.py file will add the "Last modified time: " text to the footer automatically:

html_last_updated_fmt = '%c'

The datetime format specified in this variable will be used to format the timestamp.

**Comment by georgemccabe** [comment]
Closing this issue without fixing.

This issue was intended to automate some of the changes made for a release that will should not be applied to the develop branch. However, the release process now involves making changes for the release, merging them into develop, then updating the version number in develop after the release is created. These steps are well documented in the release guide. There would be little benefit to automating these steps compared to the work required to implement it. Also, it would require changes to the release process to name the branch for a pre-release to match a specific naming convention.
