### ISSUE TITLE
Clean up use case documentation files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#681]
There are a handful of text that are identical in every use case doc file that  should be cleaned up and improved in across the board. 

One example is the way we word the "Running METplus" section requires us to modify the name of the new config 4 times. We also have discussed improving how we show how METplus config variables correspond to MET config variables (#402).

## Describe the Task ##
We should clean up the information in these files so it is easier to create a new use case. Things to consider:

- If there is text that is the same in every file, consider if that text belongs in another file instead and linked to. If it does make sense in these files, consider pulling it out into an RST file and including it so it can be edited in one place.
- Reduce the number of times a config file path needs to be updated for a new use case. This is a tedious part of the process of adding a new use case.
- #402
- For example, "See the 'User Defined Config' section on the 'System Configuration' page of the METplus User's Guide for more information.", consider consider linking the user to this section directly. The instructions for doing this are listed under the [Internal Links](https://metplus.readthedocs.io/en/develop/Contributors_Guide/documentation.html#internal-links) in the Documentation section of the Documentation Overview and Conventions section of the Contributor's Guide.
- Add a period to this sentence "This must be in a location where you have write permissions"
- Add a period to this sentence "This is not required to run METplus, but it is required to run the examples in parm/use_cases"
- **add more here**

### Time Estimate ###
3+ days

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] #402
- [ ] **add more here**

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
From PR #882, we found a few minor edits to apply to the repeated content for each use case. To avoid redundancy, we could move the common content to another file to reference in each use case doc.

Suggested changes:

Change (Click here to **see** the METplus releases):

`# | **Location:** All of the input data required for this use case can be found in the met_test sample data tarball. Click here to the METplus releases page and download sample data for the appropriate release: https://github.com/dtcenter/METplus/releases`

to

`# | **Location:** All of the input data required for this use case can be found in the met_test sample data tarball. Click here to see the METplus releases page and download sample data for the appropriate release: https://github.com/dtcenter/METplus/releases`


Change (**parm/metplus_config, then** to **parm/metplus_config and then**):

`# 2) Modifying the configurations in parm/metplus_config, then passing in METdbLoad.conf::`

to

`# 2) Modifying the configurations in parm/metplus_config and then passing in METdbLoad.conf::`


Change (**Path where METplus** to **Path to directory where METplus**):

`# * **OUTPUT_BASE** - Path where METplus output will be written. This must be in a location where you have write permissions`

to

`# * **OUTPUT_BASE** - Path to directory where METplus output will be written. This must be in a location where you have write permissions`

**Comment by jprestop** [comment]
@georgemccabe I see a note above that says "[georgemccabe](https://github.com/georgemccabe) linked a pull request [on May 6, 2021](https://github.com/dtcenter/METplus/issues/681#event-4698458360) that will close this issue", but I see that this issue is still Open.  Should it be closed?

**Comment by georgemccabe** [comment]
@jprestop, no, I don't think that PR completes this work. I think that note was generated because the PR was linked to this issue under "Development."

This issue seems related to #918, which @j-opatz is working on. John, could you refer to this issue to ensure that the changes mentioned here are covered in the use case doc template work?

**Comment by jprestop** [comment]
Thanks for the clarification @georgemccabe. I've been trying to help go through issues with @lisagoodrich to help her find things to work on.
