### ISSUE TITLE
Add METplus use-case for HRD TDR data

### ISSUE THREAD

**Issue by mrinalbiswas** [dtcenter/METplus#686]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
*This use-case will validate TC model output (e.g. HWRF and HAFS) against TDR data available from HRD. The input dataset was provided by Andrew Hazelton (HRD).*

### Acceptance Testing ###
*The input data is NetCDF format. It contains zonal, meridional, tangential and meridional winds and radar reflectivity data. All data are available in lat-lon coordinates at every 0.5 km. *

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Python script to read the TDR file*
- [ ] *Get Filename template working.*
- [ ] *Wrap MET config file*
- [ ] *GridStat config file for python embedding*
- [ ] *Define sample data tarball*
- [ ] *Add to tc_and_extra_tc application directory*

### Relevant Deadlines ###
*November 2020*

### Funding Source ###
*NOAA Hurr-Supp.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Working on eyewall in branch feature_686_hdr_tdr

**Comment by georgemccabe** [comment]
Notes from meeting on 11-4-2020:
- Modifications are needed to METcalcpy so that the input model data can be read by the MET tools.
- Extract single mission from TDR data for use in the case

**Comment by georgemccabe** [comment]
In the meeting today we discussed the possibility of modifying the python script to extract the valid time information from a given mission ID, then using that time to trigger GridStat. A driver script could be written to call GridStat instead of using master_metplus.py.
