### ISSUE TITLE
Define a common set of GitHub labels that apply to all of the METplus component repos.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#690]
## Describe the Task ##
Maintaining 7+ separate lists of GitHub labels in 7+ repositories has become unwieldy and prone to error.
This task is to construct a list of labels which apply to ALL METplus repos and define them in the METplus repo... ideally in the .github directory.

Unfortunately there is no easy way of defining "organziation-wide" labels. So this task is the next best thing.

Individual repositories are encouraged to define additional "component" labels.

However, ideally, all issues of the following types would appear in the common list:
   alert, priority, reporting, requestor, and type

This task includes:

1. Define a list of common labels, formatted for easy interface with the GitHub Rest API:
Documentation: https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#labels
Example: https://github.com/iamerikjolson/GitHub-Issues-Process/blob/master/set-github-labels.sh
2. Add the list to METplus/.github/labels_common on the develop branch.
3. Consider adding METplus/.github/labels_components on the develop branch to define the METplus-specific component labels. Consider doing the same for all the other METplus related repositories.
4. Update the labels of all the METplus components to make them consistent with this list. Consider writing/saving scripts that use the Rest API to make these updates.

Shell commands to pull/process existing labels:
[get_labels.sh.txt](https://github.com/dtcenter/METplus/files/5490029/get_labels.sh.txt)
List of 114 unique labels:
[unique_labels.txt](https://github.com/dtcenter/METplus/files/5490030/unique_labels.txt)
Working version of 52 proposed common labels:
[common_labels.txt](https://github.com/dtcenter/METplus/files/5490049/common_labels.txt)

### Time Estimate ###
3 days.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
None yet. Could split off the creation of utility scripts, if they get complex.

### Relevant Deadlines ###
None.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG, but could be reassigned.
- [x] Select **scientist(s)** or **no scientist** required: Tara and Keith to decide on common labels.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Perhaps, but not yet.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Please update this Google Doc with common labels:
https://docs.google.com/document/d/1ZQ1cC0cnLdWMZxrR9wS-LddJSK-lshnYOEs3wolssNE/edit

**Comment by JohnHalleyGotway** [comment]
Finished coordinating with Tara and Keith on updates to the labels. The ball is back in John's court to commit them and write utility scripts for updating them.

**Comment by JohnHalleyGotway** [comment]
As of 12pm on 20201210, all 50 common labels have been pushed to the METplus repositories:
metplus, met, metviewer, metexpress, metdatadb, metcalcpy, metplotpy, metplus-training

Still need to DELETE some non-component labels from those other repos though.
