### ISSUE TITLE
Add use cases using python embedding for tools that do not currently have one

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#701]
There have been many requests for examples to configuring METplus to use python embedding for tools like GridStat, MODE, etc. A GridStat example has already been added to the develop branch.

## Describe the New Feature ##
Identify which tools support python embedding that do not currently have an example in parm/use_cases/met_tool_wrapper. Add examples for these tools.

### Acceptance Testing ###
The use cases should use data from met_test (met_tool_wrapper tarball).
The use cases should run without error.
They should be added to the automated test suite (internal_tests/use_cases/all_use_cases.txt) under the met_tool_wrapper category.
Verify that the Travis builds runs the new use cases and succeed without error.

### Time Estimate ###
~3 days

### Sub-Issues ###
The following are known tools that do not have an example (may not be a complete list):
- [x] PointStat
- [x] MODE
others?

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Added new use case for MODE using python embedding. Also added PointStat python embedding use case but the case produces no output lines because the sample data times do not match up. We should remedy this before adding this case.

**Comment by georgemccabe** [comment]
We are waiting for a full sample set of data to use for the PointStat use case. We need:
* Forecast data that can be processed with a Python Embedding script
* A Python Embedding script that can process the forecast data
* An observation file valid at the same time as the forecast data
