### ISSUE TITLE
Add support for multiple instances of tools in process list

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#704]
This is a sub-issue of #670 
Currently only 1 instance of each tool can be provided in the process list

PROCESS_LIST = TCPairs, TCStat, ExtractTiles, SeriesByInit

TCStat was pulled out of ExtractTiles to make it more clear when it is run. TCStat is also optionally called inside SeriesByInit and SeriesByLead. It would greatly simplify the logic of those wrappers if you could call TCStat right before in the process list and read the filtered output into SeriesBy*. If additional filtering is not needed, you could simply point to the output of the earlier TCStat run.

## Describe the Enhancement ##
Modify the PROCESS_LIST handling code to allow an optional instance name, specifying inside parenthesis after the process name, i.e. TCStat(for_series_analysis). The wrapper will be initialized with a variable called 'instance' as an instance variable (None if no instance if specified). If there is a section in the config file with the same name as the instance, i.e. 

```
[for_series_analysis]
TC_STAT_JOB_ARGS = ...
```

then all of the values in that section will overwrite the values for that instance only. This will allow the user to specify the same settings for multiple instances and only override the values they need to change. 

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Needed for #670 

### Funding Source ###
None

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
