### ISSUE TITLE
Create the METplus 4.0.0-beta2 release.

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#714]
## Describe the Task ##
This task is to create the METplus 4.0.0-beta2 release currently scheduled for 12/7/2020.

Please follow the release instructions posted here:
http://icculus.rap.ucar.edu/metplus-release/Release_Guide/metplus.html#development-release-e-g-vx-y-z-betan-or-vx-y-z-rcn

If the instructions are incorrect or unclear, please clarify them.

### Time Estimate ###
2 hours?

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issue required.

### Relevant Deadlines ###
None

### Funding Source ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Hank
- [x] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
Will need related issues for beta1 releases for each component.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [] Complete the development and test your changes.
- [x] Add/update documentation.
- [] Push local changes to GitHub.

Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [] Close this issue.

**Comment by hankenstein2** [comment]
The release has been created.
