### ISSUE TITLE
Update content in the METplus Verification Datasets Guide.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#715]
## Describe the Enhancement ##
This task relates to the 2019 Air Force datasets project for which we had a kickoff meeting on 10/14/21. METplus #662 created the initial framework for the Verification Datasets Guide. That was added for METplus version 4.0.0-beta2. This task is enhance that content and add new dataset descriptions.

Each new dataset can be added by:
1. Copy over the existing template.rst file to a new name for the new dataset.
2. Follow the instructions within the template to describe the dataset, including labelling the dataset by type, level, provider, and application.
3. If adding any new labels for type, level, provider, or application, be sure to add them to the list in template.rst.
4. Update datasets.rst to include the new dataset in the list.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

Each person working on this can consider defining a separate sub-issue... or they may all choose to work on the same feature branch... whichever is easier.

### Relevant Deadlines ###
The funding for this task ends at the end of January 2021.
This work should be completed by the METplus-4.0-beta3 release, which is tentatively scheduled for 1/18/21.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: no engineer required
- [x] Select **scientist(s)** or **no scientist** required: several scientists selected who are working on this project

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Any status updates for this issue? I see there have been a couple pull requests with changes already merged. Does anyone else have changes they are planning on making for this issue?

**Comment by michelleharrold** [comment]
There will likely be a few additional changes in the next 1-2 weeks, but after that work should be all complete.

**Comment by JohnHalleyGotway** [comment]
Met on 1/20/21 and defined the following action items for this task:

- @lindsayrblank will document ice/ptype data (migrate content over from [Verification Dataset Brainstorm](https://docs.google.com/document/d/1Ta3oYIAEw0Ofczy94mCy2jGwMJ7GRsWctthnD9Hv_GY/edit))

- @lindsayrblank will document IMERG data.

- @michelleharrold will document dust data.

**Comment by JohnHalleyGotway** [comment]
We've had several updates to the verification datasets guide. As of 1/29/21, @michelleharrold confirms that we can now close this issue.
