### ISSUE TITLE
Enhance PCPCombine wrapper to be able to process multiple fields in one command

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#718]
This has been discussed before, but we discovered an issue did not exist when handling Mallory's MET Help ticket 97764. 

You should be able to process multiple fields at once in derive mode (in 1 command) and process multiple fields by looping through in other modes. I believe this can be achieved in some modes by using [FCST/OBS]\_VAR<n>\_* variables, but the logic should be updated to use the recommended variables, i.e. [FCST/OBS]\_PCP_COMBINE_INPUT\_[NAMES/LEVELS/ACCUMS] should be [FCST/OBS]\_PCP\_COMBINE\_VAR\<n>\_INPUT_[NAMES/LEVELS/ACCUMS]

## Describe the Enhancement ##
*Provide a description of the enhancement request here.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2791541 

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
From MET Help ticket #99031, @LoganDawson-NOAA noted that the addition of extra input fields requires specifying additional output names, especially if there are multiple inputs from the same field (different levels). Logan suggested adding a new configuration variable called FCST_PCP_COMBINE_EXTRA_OUTPUT_NAMES to handle this, and I agree that would be a good solution.
