### ISSUE TITLE
Create a new METplus GitHub issue template for "New Use Case".

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#726]
## Describe the Task ##
We had intended to create a GitHub issue template to describe the steps for creating a new METplus Use Case.
This task is to add a new file in:
   METplus/.github/ISSUE_TEMPLATE/new_use_case.md

Recommend copying over new_feature_request.md to new_use_case.md and modifying it. Also, make sure to add a label for "task: new use case" and reference it in the new_use_case.md file.

Note that this new file should be added to both the main_v3.1 and develop branches. GitHub serves up the templates from the default branch, which is currently main_v3.1... but will be main_v4.0 after the 4.0 release has been created from develop.

Please refer to the existing steps in the Contributor's Guide:
https://dtcenter.github.io/METplus/latest/Contributors_Guide/add_use_case.html

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: no engineer required
- [x] Select **scientist(s)** or **no scientist** required: Tara

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
It looks like this has been created. @TaraJensen can this issue be closed or is there more work to be done?

**Comment by j-opatz** [comment]
Used commit 69637da313c6862f6f55acd48a6358bd1c1ea452 on develop branch to add new categories for discussion on use case category, input data size, run time, and develop-ref merging.
