### ISSUE TITLE
Improve logic of TCPairs wrapper

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#749]
There are two main things that could be improved in this wrapper.

1) Set cyclone to current cyclone if processing individually

Currently the wrapper passes in the full list of cyclones to process from the METplus config for every run. This works fine if the input files are sorted by cyclone since the input file contains only that cyclone. If the input file contains many cyclones and a list of cyclones are specified in the METplus config, the wrapper will loop over these values and process once for each. The same input file is read and the output files contain the cyclone in the filename (if included in the template), but each file will contain all cyclones listed in the config file.

If we are looping over a list of cyclones and processing once for each, the environment variable CYCLONE should only contain the current cyclone being processed, not the full list of cyclones.

2) \* added to output filename if processing all cyclones

If no cyclones are specified in the METplus config, all of the available cyclones will be processed. However, if the cyclone template is not specified in the input file template, the output file will contain * as the cyclone value. If * is set for the cyclone value in this case, it should be replaced with "all" or something similar to avoid created a problematic filename.

## Describe the Enhancement ##
See above

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
We noticed that there are a few lines of log output between the list of environment variables set for the tc_pairs command run and the command run. The env var list should be found immediately before the command. We should fix this when we refactor this wrapper.

**Comment by georgemccabe** [comment]
In PR dtcenter/MET#1750 the logic to handle genesis files changed to set the STORM_ID to the FOF value (i.e. 2020100700_F000_261N_1101W_FOF). Currently the wrapper assumes that if the user sets the storm ID explicitly that it matches the ATCF format and breaks down the string into year, basin, and cyclone. The wrapper logic should be improved to check if it matches this format and use it if so, otherwise pass through the storm ID to be referenced in filename template tags. The {storm_id} should likely be usable regardless of the format.

**Comment by georgemccabe** [comment]
Per MET Help ticket 99846, add support for setting consensus list.

**Comment by georgemccabe** [comment]
Lots of progress made in branch feature_749_tc_pairs_improvements to handle proper setting of env vars for cyclone, basin, and storm_id for each iteration instead of passing entire list for each run.
