### ISSUE TITLE
Add Verification Dataset Use Case: IMERG

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/METplus#753]
## Describe the New Use Case ##
A new METplus use case that processes and uses the IMERG has been requested as part of the Air Force verification dataset task. This use case will read in IMERG data and use it as verification data to compare model performance. 

### Acceptance Testing ###
Input observation data: IMERG
Input forecast data: GALWEM grib2 data 

Test:
Reproduce GridStat output found in dakota:/d4/projects/AF/CSM/dist_imerg/metprd/grid_stat/1P5KM_REGRID

### Time Estimate ###
2 - 3 full days of work

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] Get PCPCombine set up properly for fcst data
- [x] Get PyEmbedIngest/PCPCombine set up properly for IMERG data
- [x] Get GridStat working for both
- [x] Compare output data

### Relevant Deadlines ###
01/31/21

### Funding Source ###
AF Key

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: No engineer required
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

https://github.com/dtcenter/METplus/issues/715

## New Use Case Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
