### ISSUE TITLE
Fix Documentation Build Warnings

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#754]
## Describe the Task ##
Fix the warnings that appear when building the documentation, however this may be irrelevant when switching to ReadTheDocs.

### Time Estimate ###
1 to 3 days of work.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
NONE

### Funding Source ###
2712231

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ x Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label  
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by jprestop** [comment]
One of the warnings is ""WARNING: Undefined substitution referenced: "projectRepo". 

Correspondence from George:
"Those are expected warnings that I do not know how to avoid. It is frustrating that they clutter up the output. projectRepo is set in the top level .rst files, i.e. docs/Release_Guide/metplus.rst. This variable is referenced throughout the release instructions that are common to multiple repositories. They are properly substituted when the page containing the variable is rendered, which is what we view on the web. However, if you go into the actual page for that instruction, the variable is not set and the warning is thrown. We don't actually render those pages, they are components of the upper level page, so we don't ever need to view them directly.

Does that make sense? I'm not sure how to get around this. If there is a way to check if the variable is set and set it to some default value if it is not set, then we could do something like that, but we would have to add it to every single instruction rst file. Another option is to see if we can suppress the warnings from those directories, but I don't know if that is possible either."
