### ISSUE TITLE
Modify user diagnostic feature relative use case to use MetPy Python package

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/METplus#759]
## Describe the New Feature ##
Brian Colle from SBU wants us to change the user diagnostic input scripts to use MetPy. This means re-writing the follow scripts:

- gfs_pv_analysis.py
- gfs_pv_fcst.py

We should use the following function: https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.potential_vorticity_baroclinic.html

I have tried to do this myself, but the required format (P,M,N) is giving me trouble. 

### Acceptance Testing ###
Data: input data for TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_IVT.conf
Tests: Make sure the previous output of user diagnostic PyEmbedIngest match the output generated with MetPy in the scripts. 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
TBD

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
7791041 - SBU Key

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required: **Need to define who this is**
- [X] Select **scientist(s)** or **no scientist** required: Lindsay and Tara

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
@lindsayrblank were you working in a feature branch by chance? If not, could you point us to the two scripts mentioned in the issue description? And Tara mentioned you were working with MetPy on some questions- is there a GitHub issue in the MetPy repository or a discussion board in their repository where that conversation is documented or was it just via email so far? Thanks!

**Comment by lindsayrblank** [comment]
@DanielAdriaansen Hi Dan, I was not in working in a feature branch, unfortunately. I was first trying to get things working with an example to then implement into METplus, but that never happened. The scripts, including what I've done so far with MetPy are here: eyewall:/d1/lblank/SBU/metpy. As for the conversation, it was through email. I have forwarded that to you. Let me know if you need anything else!

**Comment by DanielAdriaansen** [comment]
Thanks @lindsayrblank! What version of MetPy were you using to develop with? And are there any requirements or restrictions I should know about? It looks like you're using pygrib and wondered if that was required or whether other options were OK. 

Was the sample GFS file provided for you?

Also- I thought both of the scripts listed in this issue description were provided to you and `gfs_pv_fcst_metpy.py` was your adaptation but it looks like all the scripts are your scripts?

**Comment by lindsayrblank** [comment]
@DanielAdriaansen No problem! Here are all the answers to your questions.

1. I was using MetPy v1.0.
2. There are no requirements that I can think of! 
3. You do not have to use pygrib.
4. The sample GFS file is one file from the larger Dorian GFS data (eyewall:/d1/lblank/SBU/dorian_data/model_data)
5. All of the scripts were originally provided to me by a graduate student at Stony Brook. I then adapted them for use by METplus for python embedding. The original scientific (the PV calculation) logic was not mine. I was then instructed by our sponsor to change everything to MetPy.

**Comment by DanielAdriaansen** [comment]
IVT use cases:
https://metplus.readthedocs.io/en/develop/generated/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_IVT.html#sphx-glr-generated-model-applications-medium-range-tcstat-seriesanalysis-fcstgfs-obsgfs-featurerelative-seriesbylead-pyembed-ivt-py

https://metplus.readthedocs.io/en/develop/generated/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_Multiple_Diagnostics.html#sphx-glr-generated-model-applications-medium-range-tcstat-seriesanalysis-fcstgfs-obsgfs-featurerelative-seriesbylead-pyembed-multiple-diagnostics-py

PV use case:
https://metplus.readthedocs.io/en/develop/generated/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_Multiple_Diagnostics.html#sphx-glr-generated-model-applications-medium-range-tcstat-seriesanalysis-fcstgfs-obsgfs-featurerelative-seriesbylead-pyembed-multiple-diagnostics-py

**Comment by DanielAdriaansen** [comment]
Working on branch feature_759_FR_MetPy.

We will be eliminating this use case:
https://metplus.readthedocs.io/en/develop/generated/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_IVT.html#sphx-glr-generated-model-applications-medium-range-tcstat-seriesanalysis-fcstgfs-obsgfs-featurerelative-seriesbylead-pyembed-ivt-py

And modifying this use case:
https://metplus.readthedocs.io/en/develop/generated/model_applications/medium_range/TCStat_SeriesAnalysis_fcstGFS_obsGFS_FeatureRelative_SeriesByLead_PyEmbed_Multiple_Diagnostics.html#sphx-glr-generated-model-applications-medium-range-tcstat-seriesanalysis-fcstgfs-obsgfs-featurerelative-seriesbylead-pyembed-multiple-diagnostics-py

by:
- [ ] changing PV calculation to use MetPy
- [ ] add new diagnostic of Theta-E* using MetPy
- [ ] leaving the existing IVT computation alone, since there currently is no MetPy equivalent
