### ISSUE TITLE
List external dependencies in use case documentation files

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#767]
There are currently only 3 use case docs that have an "External Dependencies" section.

* docs/use_cases/model_applications/precipitation/GridStat_fcstHREFmean_obsStgIV_Gempak.py
* docs/use_cases/met_tool_wrapper/GempakToCF/GempakToCF.py
* docs/use_cases/met_tool_wrapper/PCPCombine/PCPCombine_python_embedding.py

There are many more use cases that require additional Python packages that are used in the Python embedding scripts.

## Describe the Enhancement ##
Add information about external requirements to use case docs that have them. We should also make sure that any Python embedding scripts used in a use case are added to the use case doc file with a "literalinclude."

### Time Estimate ###
~2 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Ideally 4.0.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
@jopatz can this issue be closed? I see there was a pull request for this work.

**Comment by jopatz** [comment]
@georgemccabe I don't know, but maybe @j-opatz does :)

**Comment by georgemccabe** [comment]
Sorry for the accidental tag!
