### ISSUE TITLE
Change perspective of Contributor's Guide chapters to 3rd person

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#770]
## Describe the Task ##
Change the perspective of chapters 2, 3, 5, 6, 7, and 8 to third person (e.g. from "you" ("we", "our") to "the user" (etc.))

### Time Estimate ###
2-3 days of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*NONE*

### Funding Source ###
Split 2702691, 7740181, 2771021, 2792541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by lisagoodrich** [comment]
Lisa's estimate of time:
There are about 1200 changes to be made.  Below is the grep commands used to find the words to change.  I'm guessing this will take a couple of days to clean up.

/git/METplus/docs/Contributors_Guide$ grep "you " * | wc -w
grep: figure: Is a directory
1049
/git/METplus/docs/Contributors_Guide$ grep " our" * | wc -w
grep: figure: Is a directory
0
/git/METplus/docs/Contributors_Guide$ grep " we " * | wc -w
grep: figure: Is a directory
197

**Comment by lisagoodrich** [comment]
@TaraJensen please update the funding source and I'll start working on this.  Thanks!

**Comment by lisagoodrich** [comment]
Changes have been approved. Closing issue
