### ISSUE TITLE
Add support for many commonly changed MET config variables

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#779]
We would like to support setting MET config variables through the wrappers for values that are likely to be changed from the default. This will reduce the need for user's to create their own wrapped MET config files to configure.

Here is a list of variables from @malloryprow that she has changed:

*GridStat*: model, desc, obtype, regrid, fcst, obs, climo_mean, mask,
fourier, output_flag, grid_weight_flag, tmp_dir, output_prefix, version
*StatAnalysis*: model, fcst_lead, fcst_valid_beg, fcst_valid_end,
fcst_valid_hour, fcst_init_beg, fcst_init_end, fcst_init_hour, fcst_var,
obs_var, fcst_lev, obs_lev, obtype, vx_mask, interp_mthd, fcst_thresh,
line_type, jobs, tmp_dir, version
*PB2NC*: message_type, obs_window, pb_report_type, level_category,
obs_bufr_var, obs_prepbufr_map, quality_mark_thresh, tmp_dir, version
*PointStat*: model, regrid, fcst, obs, message_type, obs_window, mask,
output_flag, tmp_dir, version
*TcPairs*: model, storm_id, basin, cyclone, storm_name, init_beg, init_end,
init_inc, init_exc, valid_beg, valid_end, check_dup, interp12,
match_points, version
*SerisAnalysis*: model, obtype, regrid, fcst, obs, block_size,
output_stats, tmp_dir, version

## Describe the Enhancement ##
Add support for setting environment variables from METplus config settings.

### Time Estimate ###
> 3 days - we should divide this into sub-tasks for different tools.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Ideally for 4.0.0

### Funding Source ###
2791541 and 2799991

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
PR #888 handles unsupported MODE configs
* fcst.filter_attr_name
* fcst.filter_attr_thresh
* fcst.censor_thresh
* fcst.censor_val
* fcst.vld_thresh
* obs.filter_attr_name
* obs.filter_attr_thresh
* obs.censor_thresh
* obs.censor_val
* obs.vld_thresh
* mask dictionary (all values: grid, poly, grid_flag, poly_flag)
* weight dictionary (all values)
* nc_pairs dictionary (all values)
* match_flag
* max_centroid_dist
* total_interest_thresh
* interest_function.centroid_dist
* interest_function.boundary_dist
* interest_function.convex_hull_dist

It also handles unsupported PointStat configs:
* obs_quality
* output_flag dictionary (all values)
* interp dictionary (all values: vld_thresh, shape, type.method, and type.width)
* climo_mean.time_interp_method
* climo_stdev.time_interp_method

**Comment by georgemccabe** [comment]
PR #893 added support for PB2NC config variables:
* pb_report_type
* level_range dictionary (all items: beg and end)
* level_category
* quality_mark_thresh

PR #894 added support in GridStat wrapper for:

* interp dictionary (all items)
* nc_pairs_var_name
* grid_weight_flag
* fcst.file_type
* obs.file_type
* climo_mean and climo_stdev dictionaries (all items)

Also added support for all climo_mean and climo_stdev items for

* SeriesAnalysis wrapper
* PointStat wrapper
* EnsembleStat wrapper

**Comment by georgemccabe** [comment]
Closing this issue so it is tied to the 4.0.0 release. Remaining work will be documented in #896 for the 4.1.0 release.
