### ISSUE TITLE
PlotDataPlane use case utilizing Python embedding for tripolar coordinates

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#791]
## Describe the New Use Case ##
In the pursuit of getting EMC's ocean verification package capabilities transferred to METplus, tripolar coordinate systems were successfully read into MET with a user Python script. Now, a use case demonstrating that Python script with a PlotDataPlane wrapper is being created. This will also be a first entry in the new model application "marine_and_coastal"

### Acceptance Testing ###
Using a HYCOM netCDF file for ice coverage data, as well as two (optional) pre-created weight files, the Python script is called on from the METplus config file to output two images: one for the north projection, and one for the south.

### Time Estimate ###
~2 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.

### Relevant Deadlines ###
This use case needs to make the beta4 release of METplus

### Funding Source ###
2788881

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
