### ISSUE TITLE
Integrate NOAA marine verification package into METplus

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#800]
*Replace italics below with details for this issue.*

## Describe the Task ##
On 12/17/20, DTC staff met with NOAA/EMC staff to discuss the transition of the existing EMC Marine Verification functionality into METplus. After successfully embodying tripolar coordinate python wrappers into METplus (#737), a meeting on 02/03/21 laid out the remaining packages.
This Issue will serve as the central issue for the package, while the individual components become subtasks. Code repo to mimic is on VLAB/redmine, project "EMC Verif Marine, emc-ocean-verification repo"

### Time Estimate ###
2-4 weeks

### Sub-Issues ###
Sub-issues should have GitHub issue numbers added as they are created; the descriptions are meant to be general
- [x] Satellite package #1004 
- [x] Satellite package #1116 
- [x] Satellite package #1216
- [X]  Satellite package #1318 
- [ ] Ocean fronts #1494 
- [x] Ice verification #834
- [x] Cable transfer #1399 

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
To not continue to kick this issue further down the line, it is being closed. The remaining two use cases are listed here, and will be completed in the next beta
