### ISSUE TITLE
New Use Case: Python embedding for using the wrf-python package to pass gridded data to MET.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#820]
## Describe the New Use Case ##
This suggested new use case is the results of a met-help question:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=98795

Many users of WRF would prefer not to have to post-process their raw NetCDF wrfout files using the wrf_interp or UPP tools. And there is a [wrf-python](https://wrf-python.readthedocs.io/en/latest/) package to make processing wrfout files easier. There are many potential ways wrf-python could be used with MET and METplus, but I recommend starting with the simplest option using python-embedding in MET.

This issue is to do the following:
- write a MET python embedding script to load the wrf-python module, read the user-specified wrfout file, and interpolate the user-specified variable to the user-specified pressure level
- if wind variables (i.e. on staggered dimensions) are requested, also destagger the data
- serve up the interpolated and de-staggered data and metadata (including grid definition) via a NumPy array (or Xarray) for use by MET
- develop a new METplus use case to demonstrate this fucntionality

We first need to identify a user who would benefit by this functionality and work closely with them on the testing and development.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**
- [x] Select **privacy**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
