### ISSUE TITLE
New Use Case: Ice cover/concentration use case, part of marine layer verification integration

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/METplus#834]
## Describe the New Use Case ##
This new use case will duplicate the efforts of Todd Spindler's VLab-Redmine code, specifically its calculations for ice coverage and concentration (which includes extent and area calculations). This will need to utilize Python embedding for the data file ingest, as well as a possible need to convert between coordinate systems (if not available in METplus).
It still needs to be determined if the graphical output currently produced and displayed at the site listed below need to be produced in this use case.
As a final step, these new data sources will be logged in the METplus Verification Datasets Guide.

This is part of the larger Marine layer Verification package integration, which is tracked in #800 

### Acceptance Testing ###
Graphical output from current VLab code: https://polar.ncep.noaa.gov/global/ice/

Input files: The OSTIA files, which are archived here (https://podaac.jpl.nasa.gov/dataset/OSTIA-UKMO-L4-GLOB-v2.0), and the RTOFS files, which are not archived, and need to be pulled on the date desired.

A successful output from this use case will duplicate ongoing efforts currently completed with Todd's VLab code.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
This is a checklist for functions within the use case and is intended purely as a tracking system, and will not be broken into separate Github sub-issues
- [ ] Sea ice concentration of RTOFS, OSTIA (map)
- [ ] Difference between RTOFS, OSTIA Ice concentration (map)
- [x] Stats between the two models (weighted mean, bias, std dev, correlation coefficient, scatter index, RMSE)
- [ ] OSTIA, RTOFS Ice extent and Area (graph)

### Relevant Deadlines ###
None

### Funding Source ###
2788881

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**
- [x] Select **privacy**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Use Case Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by j-opatz** [comment]
This issue has spawned two other related issues: one to create the plot via METplotpy ([here](https://github.com/dtcenter/METplotpy/issues/118)) and one to calculate the Scatter Index ([here](https://github.com/dtcenter/MET/issues/1843)), which is the only output not calculated by MET currently.
In the meantime, the use case is being developed and should be included in the beta1 release.
