### ISSUE TITLE
Update TCStat config options and wrappers to filter data by excluding strings.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplus#857]
## Describe the Enhancement ##
The issue dtcenter/MET#1733 makes the following changes to MET:
- Add TC-Stat configuration file options: column_str_exc_name, column_str_exc_val, init_str_exc_name, init_str_exc_val
- Add TC-Stat job command options: -column_str_exc, -init_str_exc
- Add Stat-Analysis job command options: -column_str_exc
Please see the changed files here: https://github.com/dtcenter/MET/pull/1734/files

This task is to update METplus to accommodate these changes. Those changes may include changes to the wrapped TC-Stat config file and the python wrappers themselves.

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
METplus 4.0.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: George
- [x] Select **scientist(s)** or **no scientist** required: no scientist required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
