### ISSUE TITLE
New Use Case: RMM and OMI (driver scripts)

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METplus#892]
## Describe the New Use Case ##
Convert the example scripts (compute_omi_example.py, compute_rmm_example.py, phase_diagram_example.py)  into the METplus system as driver scripts using the UserScript command.  This will include running the model and obs through a MET tool to get a MET formatted netCDF and then reading in this with the new calcpy read_file.py

### Acceptance Testing ###
data is on kiowa:/d1/projects/METcalcpy/METcalcpy_Data/MJO_Indices

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] compute_omi_example.py
- [ ] compute_rmm_example.py
- [ ] phase_diagram_example.py
- [ ] fix data read-in for MET format and perhaps move read in to a separate utility script

### Relevant Deadlines ###
ASAP, METplus 4.1.0

### Funding Source ###
2785051

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**
- [ ] Select **privacy**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] [METcalcpy Issue](https://github.com/dtcenter/METcalcpy/issues/89)
- [ ] [METplotpy Issue](https://github.com/dtcenter/METplotpy/issues/109)

## New Use Case Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
The files for the 3 new use cases were added in beta1, but there are some outstanding tasks needed before closing this issue. See the pull request #1014 comments for details.
