### ISSUE TITLE
Add support for commonly changed MET config variables part 2

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#896]
Continuation of #779 to keep progress completed for the issue associated with METplus 4.0.0 and associate the remaining tasks with 4.1.0.

## Describe the Enhancement ##

From the original list @malloryprow provided, all of the MET config variables are supposed EXCEPT for the following:

GridStat:
- [x] fourier
- [x] censor_thresh
- [x] censor_val

PB2NC:
- [x] obs_prefbufr_map
- [x] obs_bufr_map

PointStat:
- [x] mask.llpnt
- [x] hira dictionary (@JohnHalleyGotway mentioned this one is used and would be good to implement)
- [x] message_type_group_map (used in use case in #635)

TCPairs:
- [x] check_dup
- [x] interp12
Note: match_points is not configurable in the config file but it is an option in the wrapper which sets the command line argument which has the same behavior

SeriesAnalysis:
- [x] output_stats (only cts and cnt lists are currently supported)

MODE:
- [x] ps_plot_flag
- [x] ct_stats_flag

### Time Estimate ###
~2-3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
4.1.0

### Funding Source ###
Split across open keys

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Closed via #1322
