### ISSUE TITLE
Documentation: Make Headers Consistent in METplus components User's Guides

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplus#898]
## Describe the Task ##
The headers for the METplus components User's Guides may not be consistent, but we want them to be. 

Here is the syntax from the RST docs (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections):

\# with overline, for parts (e.g. the RTD documentation for the component (i.e. docs/index.rst), each guide (e.g. User's Guide, Contributor's Guide) (i.e. docs/Users_Guide/index.rst, docs/Contributors_Guide/index.rst))
\* with overline, for chapters
=, for sections
-, for subsections
^, for subsubsections
", for paragraphs

### Time Estimate ###
1 to 3 days of work

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Start with the METcalcpy installation documentation: METcalcpy/docs/Users_Guide/installation.rst in the repository
        ([Documentation: Make Headers Consistent in METcalcpy User's Guides #313](https://github.com/dtcenter/METcalcpy/issues/313))
- [x] METplotpy - Lisa:They were all correct except Chapter 21 tcmw_cross_section.rst. 7/25/23 pull request submitted https://github.com/dtcenter/METplotpy/issues/371.  Julie found underlines that needed to be dashes.  Pull request approved 7/26/23 with changes.
- [x] METplus -   Please review "All" guides, including, 
       - [x] User's Guide (Please note, the usecases.rst file pulls converted text from python files located under the "use_cases" folder. These do not follow the standard protocol and are separate from all other forms of the documentation. It does not need to be reviewed.)
       - [x] Contributor's Guide (work completed 9/4/23), 
       - [x] Verification Datasets Guide - Julie: Lisa, you should still check every file to be detailed and thorough, but upon a quick glance I noticed that all of the Verification Dataset chapters have incorrect headers of underlining ===, but should be underlined and overlined ****. For this work, you can just use this existing issue for METplus for your feature branch.
       - [x] Release Guide, you may need help with this.  Lisa: This was very tricky and confusing. I created a sheet, [2023 Release Guide adventures](https://docs.google.com/spreadsheets/u/0/d/1LttGC1Xlw-2JEaQo7hMv8QdsyzjvvZ3_Xz4SvB98hC8/edit) to try and keep track of the 100 files linked across many different chapters.
       - [x] Lisa: I had questions about things outside of the scope of work.  I've captured them here for review: [2023 METplus oddities discovered while cleaning up header consistency](https://docs.google.com/document/u/0/d/13nvFrJoGVuUVngHiI9IGwb3vwO2ZStvG_16cgFHseo0/edit) Per Julie, it is okay to pass on these issues since they are outside of the scope of work.
- [x] MET (Lisa, you need to create a [Sub-Issue in the MET repository](https://github.com/dtcenter/MET/issues/new?assignees=&labels=alert%3A+NEED+ACCOUNT+KEY%2C+alert%3A+NEED+MORE+DEFINITION%2C+alert%3A+NEED+CYCLE+ASSIGNMENT%2C+type%3A+sub-issue&projects=&template=sub-issue.md&title=) for this work; Please use the following title **Documentation: Make Headers Consistent in All MET Guides**) By "All" guides, that means the 
       - [x] User's Guide,
       - [x] Contributor's Guide
   The above items were completed on 11/9/23.
- [x] In creating the description for the new issue please use the METcalcpy issue link above as an example.   MET issue created 10/16/23: https://github.com/dtcenter/MET/issues/2716
- [x] METdatio (Lisa, you need to create a [Sub-Issue in the METdataio repository](https://github.com/dtcenter/METdataio/issues/new?assignees=&labels=alert%3A+NEED+ACCOUNT+KEY%2C+alert%3A+NEED+MORE+DEFINITION%2C+alert%3A+NEED+CYCLE+ASSIGNMENT%2C+type%3A+sub-issue&projects=&template=sub-issue.md&title=) for this work; Please use the following title **Documentation: Make Headers Consistent in All METdataio Guides**) By "All" guides, that means the User's, Contributor's, etc. guides. In creating the description for the new issue please use the METcalcpy issue link above as an example.  Issue created 10/16/23: https://github.com/dtcenter/METdataio/issues/238. Work completed and pull request closed 10/19/23.
- [x] METviewer (Lisa, you need to create a [Sub-Issue in the METviewer repository](https://github.com/dtcenter/METviewer/issues/new?assignees=&labels=alert%3A+NEED+ACCOUNT+KEY%2C+alert%3A+NEED+MORE+DEFINITION%2C+alert%3A+NEED+CYCLE+ASSIGNMENT%2C+type%3A+sub-issue&projects=&template=sub-issue.md&title=) for this work; Please use the following title **Documentation: Make Headers Consistent in All METviewer Guides**) By "All" guides, that means the User's, Contributor's, etc. guides. In creating the description for the new issue please use the METcalcpy issue link above as an example.  Issue createdd 10/16/23: https://github.com/dtcenter/METviewer/issues/497 

### Relevant Deadlines ###
None

### Funding Source ###
2783543 - Lisa has hours on this account.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Check with @TaraJensen on when an appropriate time to work on this is, with regard to funding.

**Comment by jprestop** [comment]
@lisagoodrich This is another issue that could be worked on while I am gone with Tara's approval.

**Comment by lisagoodrich** [comment]
Tara said I can use my available time on 2702691 and 2792542 to do this work.  I'm updataing the account key with this information.

**Comment by lisagoodrich** [comment]
@bikegeek I've updated the METcalcpy documentation to match the Sphinx guidelines.  Would you like to look at this before I move onto METplotpy?  Oh, I didn't have to change anything in the release notes.  They are already updated in the develop branch, but not in the main branch.
https://metcalcpy.readthedocs.io/en/latest/Users_Guide/release-notes.html

**Comment by lisagoodrich** [comment]
@jprestop I spoke with @bikegeek about this task.  We thought you wanted me to update METcalcpy and METplotpy headings.  We didn't know what you meant my METpllus components User's Guides.  I tried searching for this and didn't get very far.  We thought you must mean METcalcpy and METplotpy. But now I'm not so sure.

METplotpy except one, tcmw_cross_section.rst.  I'm not sure I'm on the right track so I'm going to stop working on this task until I get further direction from you.  
I created a branch in METcalcpy, using this issue number.  However, I'm now realizing this is in METplus.  I don't know if this matters or not, but I wanted to point this out.
Sorry,
Lisa

**Comment by georgemccabe** [comment]
@lisagoodrich , can this issue be closed?

**Comment by jprestop** [comment]
@georgemccabe She is still working on subtasks.  I thought we'd leave it open until the subtasks are done.  Please note, however, that the METplus wrappers component work is done.  Based on that information, do you think we should close it or leave it open?

**Comment by georgemccabe** [comment]
@jprestop, it looks like there are issues for the other components. I think it is OK to close this one since the work for METplus is done. The other sub-tasks are not related to METplus wrappers.

**Comment by lisagoodrich** [comment]
@jprestop & @georgemccabe I'm really close to finishing the final MET portion of this issue.  I'm hoping I can double check my work tomorrow and submit a pull request for MET by Friday.  I understand if it makes more sense to just close this issue.
