### ISSUE TITLE
Improvements to TCMPRPlotter wrapper logging and output control

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#926]
There are a few improvements that could be made to TCMPRPlotter:
* Currently TCMPRPlotter does not call the functionality to run commands that the rest of the wrappers do, so it does not output any of the log information from the Rscript run
* The environment variable(s) set by the wrapper and the command called are not output in the logs in the same way as the other wrappers. This may be remedied with the changes for the first item.
* The error handling logic references a produtil item that has not been imported, so the wrapper crashes on error

We should consider if time is better spent updating this wrapper or implement the R logic in Python inside METplotpy and replace this wrapper with a call to METplotpy.

## Describe the Enhancement ##
Enhance the TCMPRPlotter wrapper to implement the improvements listed above.

### Time Estimate ###
~3 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
4.1.0

### Funding Source ###
2788881

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
If we decide to migrate this logic to METplotpy/METcalcpy instead of fixing the wrapper, we will need to create issues in the appropriate repositories:
- [ ] [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by georgemccabe** [comment]
From MET Help 99800, we should add quotation marks around the value set in TC_PAIRS_FILTER if they are not added already. Without this, tc_stat filter arguments cannot contain more than 1 string.

**Comment by georgemccabe** [comment]
Improvements to the wrapper have been made in branch feature_926_tcmprplotter_logging. This version was made available on Hera and Jet for 2 users to test and ensure that the changes allow them to create the plots they desire. Once I receive feedback I will make adjustments as needed and create a pull request to close this issue.
