### ISSUE TITLE
Fix documentation quick search links

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#963]
The quick search page (docs/Users_Guide/quicksearch.rst and use case documentation files (docs/use_cases) have hard-coded URLs to perform the search. They point to the develop version of the docs. These have to be updated when a new release is created. This also prevents testing that links work properly in a branch because the changed content doesn't exist in develop yet.

**Some of the URLs in the use case doc files still use dtcenter.github.io URLs which are broken!**

## Describe the Enhancement ##
Some thought/investigation is needed to come up with a good solution. My initial thoughts:

* URLs can be relative instead of a full hard-coded path
* URLs that start with / are relative to the "root" of the webpage. We should investigate what the "root" of a ReadTheDocs page is. Typically the root is the top level, i.e. metplus.readthedocs.io but we need to know the rest of the URL for the current branch/tag/version, i.e. metplus.readthedocs.io/en/develop. If ReadTheDocs somehow sets the root to be this location, then we can easily create paths relative to that for the searches. I think this would be the ideal solution if that is the case.
* URLs that start with ../ are relative to the current page. This would work great for the quicksearch.rst page, however the use case doc pages will have a different relative path. We typically copy links from the quicksearch page and paste them into the use case doc files (and modify the link text to match the actual keyword) so this would involve an extra step to add extra "../" to get the correct relative path. One option is to remove the links from the use case doc pages since the actual keyword text is the only required text so that the search finds the page. The URL on those pages are just for convenience to search for other related cases. We could add a link to the quick search page so that users can easily get to that page to search for that keyword.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
This works:
```
`ASCII2NCtest3 <../search.html?q=ASCII2NCToolUseCase&check_keywords=yes&area=default>`_
```

-------
This is the existing syntax that works, but points to develop:
```
`ASCII2NC <https://metplus.readthedocs.io/en/develop/search.html?q=ASCII2NCToolUseCase&check_keywords=yes&area=default>`_
```

@lisagoodrich and I tried this, which does not work:
```
`ASCII2NCtest </search.html?q=ASCII2NCToolUseCase&check_keywords=yes&area=default>`_
```

@lisagoodrich and I tried this, which does not work because of the pipe symbols:
```
.. |branch| replace:: feature_963_quick_search
   | `ASCII2NCtest2 </en/|branch|/search.html?q=ASCII2NCToolUseCase&check_keywords=yes&area=default>`_
```

**Comment by jprestop** [comment]
@georgemccabe We found a solution for the quicksearch page.  As you suggested ../ works.  Regarding the use case pages, would you prefer to have the extra step of adding another "../" to get the correct relative path, to remove the links from the use case doc pages and add a link on the use case doc pages to the quick search page so that users can easily get to that page to search for that keyword?

**Comment by georgemccabe** [comment]
@jprestop I am leaning towards removing the links on the use case pages in favor of having just the keyword values and a link to the quick search page. It is often confusing for new use case developers to add keywords because copying the link from the quick search page is not sufficient. The actual link text must match the keyword or it will not show up in a search. While it is convenient to be able to click the link and see the search results, I feel that it is more important that the keyword is correctly added. I fear that adding another step for adding a keyword (update the link text AND update the relative path in the URL) will lead to more unintended errors that the benefit of the link provides.

**Comment by jprestop** [comment]
@georgemccabe That makes sense and sounds good.  Could you please provide an example for @lisagoodrich on the text for the link to the quick search page that you would like to use in place of the links on the use case pages?

**Comment by georgemccabe** [comment]
I think could include something like this:

> Navigate to the :ref:\`quick-search\` page to discover other similar use cases.

The quick search page has a label so you should be able to reference that label to create the link and the title of that page will be used as the text.

**Comment by jprestop** [comment]
@georgemccabe On this page: https://metplus.readthedocs.io/en/feature_963_quick_search/generated/model_applications/climate/MODE_fcstCESM_obsGPCP_AsianMonsoonPrecip.html#sphx-glr-generated-model-applications-climate-mode-fcstcesm-obsgpcp-asianmonsoonprecip-py
Do you want the text under "Note" that says "MODEToolUseCase, ClimateAppUseCase, NetCDFFileUseCase, NCAROrgUseCase" to be removed entirely, or should those key words remain (without the links)?  If they should remain, should it list the key words and then "Navigate to the :ref:`quick-search` page to discover other similar use cases." underneath?  I just want to make sure we're doing it correctly.

**Comment by georgemccabe** [comment]
@jprestop  the text under "Note" for each keyword must be present so that the quick search will find the file. The ordering is up to you, but I think it makes sense to have the "Navigate to.." text under the "Note" section.

**Comment by jprestop** [comment]
@georgemccabe Can you please confirm that it looks the way you expect it to look on the following page?
https://metplus.readthedocs.io/en/feature_963_quick_search/generated/model_applications/climate/MODE_fcstCESM_obsGPCP_AsianMonsoonPrecip.html#sphx-glr-generated-model-applications-climate-mode-fcstcesm-obsgpcp-asianmonsoonprecip-py
Please let us know if you'd like any changes made.
On a side note, do you know why it lists the following under "Keywords":
> sphinx_gallery_thumbnail_path = ‘_static/climate-MODE_fcstCESM_obsGPCP_AsianMonsoonPrecip.png’

Is that necessary?

**Comment by georgemccabe** [comment]
It may look better to remove the "Note" section all together and just list the keywords and the link text under the "Keywords" heading.

The sphinx_gallery_thumbnail_path is required to set the image of the thumbnail for the use case on the webpage that displays all of the use cases. It should not be under the Keywords section, but it does need to be in the document somewhere. A while ago we discussed trying to figure out a way to hide that text from the document but still have the value read to set the image thumbnail, but I don't think we created a GitHub issue to address it.

**Comment by jprestop** [comment]
@georgemccabe Ok.  I removed the "Note" section all together and just listed the keywords and the link text under the "Keywords" heading.  Please take a look and let us know if this is how you'd like it:
https://metplus.readthedocs.io/en/feature_963_quick_search/generated/model_applications/climate/MODE_fcstCESM_obsGPCP_AsianMonsoonPrecip.html#sphx-glr-generated-model-applications-climate-mode-fcstcesm-obsgpcp-asianmonsoonprecip-py

Regarding the sphinx_gallery_thumbnail_path, @lisagoodrich  can look into a way to hide that text from the document but still have the value read to set the image thumbnail, if you'd like.  Please let us know.

**Comment by georgemccabe** [comment]
@jprestop Hmmm, we may want to get feedback from the rest of the team on this. Without the "Note" section the keywords and link text sort of blend together. Perhaps we should put the keywords inside a note and have the link text below it outside of the note section?

**Comment by jprestop** [comment]
@georgemccabe I have no preference.  However you and the team would like it, works for me.

**Comment by jprestop** [comment]
This work is complete.  We discussed trying to make sphinx_gallery_thumbnail_path invisible.  @lisagoodrich found a solution but we tested it and it did not work.  If it is important @georgemccabe, an issue for this should be created.
