### ISSUE TITLE
Enhance logic for setting mask.poly to allow MET list characters (square braces and semi-colon)

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METplus#966]
A question from Deanna Spindler in a NOAA telecon brought up an improvement to the logic that reads lists to be more flexible. The following value will produce an error because the logic for reading lists from the METplus config files automatically adds square braces and a semicolon:

POINT_STAT_POLY = [“{ENV[MET_BUILD_BASE]}/share/met/poly/CAR.poly”, "{ENV[MET_BUILD_BASE]}/share/met/poly/GLF.poly", "{ENV[MET_BUILD_BASE]}/share/met/poly/NAO.poly", "{ENV[MET_BUILD_BASE]}/share/met/poly/SAO.poly"  ];

The correct format for this variable is currently:

POINT_STAT_POLY = “{ENV[MET_BUILD_BASE]}/share/met/poly/CAR.poly”, "{ENV[MET_BUILD_BASE]}/share/met/poly/GLF.poly", "{ENV[MET_BUILD_BASE]}/share/met/poly/NAO.poly", "{ENV[MET_BUILD_BASE]}/share/met/poly/SAO.poly"

however, it would be good to enhance the logic that parses a list to check if a semicolon and/or square braces already exist in the value and do not add them if so.

## Describe the Enhancement ##
Add logic to the getlist (met_util) function to handle the formatting properly so that both of the above values would be handled properly.

### Time Estimate ###
~1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [X] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required
- [X] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [X] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
